In [2]:
from ams_background_tasks.tools.common import PIXEL_LAND_USE_AREA
from ams_background_tasks.tools.prodes_utils import (
    PRODES_DEFORESTATION_PIXEL_BASE_YEAR, PRODES_REMAINING_DEFORESTATION_PIXEL_REFERENCE_YEAR, PRODES_DB_FIRST_YEAR, PRODES_LAST_YEAR
)

import numpy as np
import pandas as pd

from pathlib import Path

# vars
___

In [3]:
ROOT_DIR = Path("/home/marcosilva/terrabrasilis/prodes/")
CACHE_DIR = ROOT_DIR / "cache"

In [4]:
LAND_USE_TYPE = "ams"  # ams, ppcdam

In [5]:
reference = {}

biome = "Amazônia"

spatial_units = ["cs_5km", "cs_25km", "cs_150km", "states", "municipalities"]

YEARS_TO_IGNORE = [2001, 2003, 2005]

# helpers
___

In [6]:
def get_deforestation_pixels(year: int) -> np.ndarray:
    deforestation_pixel_value = year - PRODES_DEFORESTATION_PIXEL_BASE_YEAR
    remaining_deforestation_pixel_value = (
        year - PRODES_REMAINING_DEFORESTATION_PIXEL_REFERENCE_YEAR
    )
    return [deforestation_pixel_value, remaining_deforestation_pixel_value]

In [7]:
def get_deforestation_pixels_by_land_use_filename(year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/count/spatial_unit_deforestation_landuse_counts_b{biome}_y{year}.pkl"


def get_vegetation_pixels_by_land_use_filename(year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/count/spatial_unit_vegetation_landuse_counts_b{biome}_y{year}.pkl"


def get_annual_increase_in_deforestation_indicator_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/annual_increase_in_deforestation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_accumulated_deforestation_indicator_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/accumulated_deforestation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_vegetation_from_mask_filename(biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/vegetation_from_mask_b{biome}.pkl"


def get_vegetation_from_deforestation(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/vegetation_from_deforestation_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_total_vegetation_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/vegetation_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_original_vegetation_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/original_vegetation_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_ratio_deforestation_to_vegetation_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/ratio_accumulated_deforestation_to_vegetation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_ratio_annual_increase_deforestation_to_remaining_vegetation_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/ratio_annual_increase_deforestation_to_remaining_vegetation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_ratio_accumulated_deforestation_to_original_vegetation_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/ratio_accumulated_deforestation_to_original_vegetation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def load_dfr(filename, filters={}):
    assert filename.exists()
    
    dfr = pd.read_pickle(filename)

    mask = pd.Series(True, index=dfr.index)

    for col, value in filters.items():
        if isinstance(value, list):
            mask &= dfr[col].isin(value)
        else:
            mask &= dfr[col] == value

    return dfr[mask]

# histogram
___

In [8]:
hist = {
    "0": 14828887,
    "1": 0,
    "2": 3547561,
    "3": 0,
    "4": 3163554,
    "5": 0,
    "6": 2146609,
    "7": 741560049,
    "8": 15423937,
    "9": 6662302,
    "10": 7462510,
    "11": 6117409,
    "12": 4682061,
    "13": 7050904,
    "14": 6259108,
    "15": 6707760,
    "16": 9205524,
    "17": 7666207,
    "18": 9154802,
    "19": 12904011,
    "20": 12502450,
    "21": 14638486,
    "22": 14971904,
    "23": 9523109,
    "24": 7507240,
    "25": 5795798,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 0,
    "33": 0,
    "34": 0,
    "35": 0,
    "36": 0,
    "37": 0,
    "38": 0,
    "39": 0,
    "40": 0,
    "41": 0,
    "42": 0,
    "43": 0,
    "44": 0,
    "45": 0,
    "46": 0,
    "47": 0,
    "48": 0,
    "49": 0,
    "50": 337812,
    "51": 165933,
    "52": 76185,
    "53": 100243,
    "54": 75485,
    "55": 1714008,
    "56": 313332,
    "57": 105461,
    "58": 99681,
    "59": 563763,
    "60": 131873,
    "61": 88686,
    "62": 225676,
    "63": 127585,
    "64": 390057,
    "65": 1157232,
    "66": 0,
    "67": 0,
    "68": 0,
    "69": 0,
    "70": 0,
    "71": 0,
    "72": 0,
    "73": 0,
    "74": 0,
    "75": 0,
    "76": 0,
    "77": 0,
    "78": 0,
    "79": 0,
    "80": 0,
    "81": 0,
    "82": 0,
    "83": 0,
    "84": 0,
    "85": 0,
    "86": 0,
    "87": 0,
    "88": 0,
    "89": 0,
    "90": 0,
    "91": 123414796,
    "92": 0,
    "93": 0,
    "94": 0,
    "95": 0,
    "96": 0,
    "97": 0,
    "98": 0,
    "99": 0,
    "100": 3427851126,
    "101": 281389326,
  }

# deforestation pixels by land use (counts)
___

In [ ]:
filename = get_deforestation_pixels_by_land_use_filename(year=2000, biome=biome)
print(filename)
assert filename.exists()

dfr = load_dfr(filename)
dfr

In [ ]:
for year in range(2000, 2026):
    if year in YEARS_TO_IGNORE:
        continue

    print(f"\nPRODES {year} ...")
        
    pixels = get_deforestation_pixels(year=year)
    total_hist = hist[str(pixels[0])] + hist[str(pixels[1])]

    filename = get_deforestation_pixels_by_land_use_filename(year=year, biome=biome)
    print(filename)
    assert filename.exists()

    dfr = load_dfr(filename)

    for spatial_unit in spatial_units:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
        total = dfr["num_pixels"].sum()
        delta = total - total_hist
        percent = abs(delta) / total_hist * 100
        print(f"{spatial_unit}: num_pixels={total}, reference={total_hist}, delta={delta}, percent={percent:.4f}")
        assert percent < 0.01

# annual increase in deforestation indicator (relative counts)
___

In [ ]:
filename = get_annual_increase_in_deforestation_indicator_filename(2000, 2025, biome)
assert filename.exists()
print(filename)

dfr = load_dfr(filename)
dfr

In [ ]:
filename = get_annual_increase_in_deforestation_indicator_filename(2000, 2025, biome)
assert filename.exists()
print(filename)

for year in range(2000, 2026):
    if year in YEARS_TO_IGNORE:
        continue

    print(f"\nPRODES {year} ...")

    pixels = get_deforestation_pixels(year=year)
    total_from_hist = hist[str(pixels[0])] + hist[str(pixels[1])]

    for spatial_unit in spatial_units:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        reference = total_from_hist
        total = dfr["deforestation_pixels"].sum()
        delta = total - reference
        percent = abs(delta) / reference * 100
        print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}, percent={percent:.4f}")
        assert percent < 0.01

# accumulated deforestation indicator (absolute counts)
___

In [9]:
filename = get_annual_increase_in_deforestation_indicator_filename(2000, 2025, biome)
print(filename)
assert filename.exists()

years = np.arange(2000, 2025+1, 1).tolist()

annual_dfr = load_dfr(filename)

acc_dict = {}

for spatial_unit in spatial_units:
    _abs = 0
    acc_dict[spatial_unit] = {}
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        
        _rel = dfr["deforestation_pixels"].sum()
        _abs = _abs + _rel

        acc_dict[spatial_unit].update({
            year: {
                "relative": _rel,
                "absolute": _abs,
            }
        })

/home/marcosilva/terrabrasilis/prodes/cache/ams/annual_increase_in_deforestation_indicator_bAmazônia_from_y2000_to_y2025.pkl

#### validating dict

In [11]:
acc_dict

{'cs_5km': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547556, 'absolute': 18376443},
  2003: {'relative': 0, 'absolute': 18376443},
  2004: {'relative': 3163541, 'absolute': 21539984},
  2005: {'relative': 0, 'absolute': 21539984},
  2006: {'relative': 2146606, 'absolute': 23686590},
  2007: {'relative': 741549271, 'absolute': 765235861},
  2008: {'relative': 15423926, 'absolute': 780659787},
  2009: {'relative': 6662302, 'absolute': 787322089},
  2010: {'relative': 7800315, 'absolute': 795122404},
  2011: {'relative': 6283340, 'absolute': 801405744},
  2012: {'relative': 4758246, 'absolute': 806163990},
  2013: {'relative': 7151143, 'absolute': 813315133},
  2014: {'relative': 6334591, 'absolute': 819649724},
  2015: {'relative': 8421766, 'absolute': 828071490},
  2016: {'relative': 9518856, 'absolute': 837590346},
  2017: {'relative': 7771668, 'absolute': 845362014},
  2018: {'relative': 9254478, 'absolute': 854616492},
  2019: {'relative': 13467766, 'absolute': 868084258},
  2020: {'relative': 12634323, 'absolute': 880718581},
  2021: {'relative': 14727172, 'absolute': 895445753},
  2022: {'relative': 15197575, 'absolute': 910643328},
  2023: {'relative': 9650694, 'absolute': 920294022},
  2024: {'relative': 7897297, 'absolute': 928191319},
  2025: {'relative': 6953030, 'absolute': 935144349}},
 'cs_25km': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547556, 'absolute': 18376443},
  2003: {'relative': 0, 'absolute': 18376443},
  2004: {'relative': 3163541, 'absolute': 21539984},
  2005: {'relative': 0, 'absolute': 21539984},
  2006: {'relative': 2146606, 'absolute': 23686590},
  2007: {'relative': 741549271, 'absolute': 765235861},
  2008: {'relative': 15423926, 'absolute': 780659787},
  2009: {'relative': 6662302, 'absolute': 787322089},
  2010: {'relative': 7800315, 'absolute': 795122404},
  2011: {'relative': 6283340, 'absolute': 801405744},
  2012: {'relative': 4758246, 'absolute': 806163990},
  2013: {'relative': 7151143, 'absolute': 813315133},
  2014: {'relative': 6334591, 'absolute': 819649724},
  2015: {'relative': 8421766, 'absolute': 828071490},
  2016: {'relative': 9518856, 'absolute': 837590346},
  2017: {'relative': 7771668, 'absolute': 845362014},
  2018: {'relative': 9254478, 'absolute': 854616492},
  2019: {'relative': 13467766, 'absolute': 868084258},
  2020: {'relative': 12634323, 'absolute': 880718581},
  2021: {'relative': 14727172, 'absolute': 895445753},
  2022: {'relative': 15197575, 'absolute': 910643328},
  2023: {'relative': 9650694, 'absolute': 920294022},
  2024: {'relative': 7897297, 'absolute': 928191319},
  2025: {'relative': 6953030, 'absolute': 935144349}},
 'cs_150km': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547556, 'absolute': 18376443},
  2003: {'relative': 0, 'absolute': 18376443},
  2004: {'relative': 3163541, 'absolute': 21539984},
  2005: {'relative': 0, 'absolute': 21539984},
  2006: {'relative': 2146606, 'absolute': 23686590},
  2007: {'relative': 741549271, 'absolute': 765235861},
  2008: {'relative': 15423926, 'absolute': 780659787},
  2009: {'relative': 6662302, 'absolute': 787322089},
  2010: {'relative': 7800315, 'absolute': 795122404},
  2011: {'relative': 6283340, 'absolute': 801405744},
  2012: {'relative': 4758246, 'absolute': 806163990},
  2013: {'relative': 7151143, 'absolute': 813315133},
  2014: {'relative': 6334591, 'absolute': 819649724},
  2015: {'relative': 8421766, 'absolute': 828071490},
  2016: {'relative': 9518856, 'absolute': 837590346},
  2017: {'relative': 7771668, 'absolute': 845362014},
  2018: {'relative': 9254478, 'absolute': 854616492},
  2019: {'relative': 13467766, 'absolute': 868084258},
  2020: {'relative': 12634323, 'absolute': 880718581},
  2021: {'relative': 14727172, 'absolute': 895445753},
  2022: {'relative': 15197575, 'absolute': 910643328},
  2023: {'relative': 9650694, 'absolute': 920294022},
  2024: {'relative': 7897297, 'absolute': 928191319},
  2025: {'relative': 6953030, 'absolute': 935144349}},
 'states': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547556, 'absolute': 18376443},
  2003: {'relative': 0, 'absolute': 18376443},
  2004: {'relative': 3163541, 'absolute': 21539984},
  2005: {'relative': 0, 'absolute': 21539984},
  2006: {'relative': 2146606, 'absolute': 23686590},
  2007: {'relative': 741549271, 'absolute': 765235861},
  2008: {'relative': 15423926, 'absolute': 780659787},
  2009: {'relative': 6662302, 'absolute': 787322089},
  2010: {'relative': 7800315, 'absolute': 795122404},
  2011: {'relative': 6283340, 'absolute': 801405744},
  2012: {'relative': 4758246, 'absolute': 806163990},
  2013: {'relative': 7151143, 'absolute': 813315133},
  2014: {'relative': 6334591, 'absolute': 819649724},
  2015: {'relative': 8421766, 'absolute': 828071490},
  2016: {'relative': 9518856, 'absolute': 837590346},
  2017: {'relative': 7771668, 'absolute': 845362014},
  2018: {'relative': 9254478, 'absolute': 854616492},
  2019: {'relative': 13467766, 'absolute': 868084258},
  2020: {'relative': 12634323, 'absolute': 880718581},
  2021: {'relative': 14727172, 'absolute': 895445753},
  2022: {'relative': 15197575, 'absolute': 910643328},
  2023: {'relative': 9650694, 'absolute': 920294022},
  2024: {'relative': 7897297, 'absolute': 928191319},
  2025: {'relative': 6953030, 'absolute': 935144349}},
 'municipalities': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547556, 'absolute': 18376443},
  2003: {'relative': 0, 'absolute': 18376443},
  2004: {'relative': 3163541, 'absolute': 21539984},
  2005: {'relative': 0, 'absolute': 21539984},
  2006: {'relative': 2146606, 'absolute': 23686590},
  2007: {'relative': 741549271, 'absolute': 765235861},
  2008: {'relative': 15423926, 'absolute': 780659787},
  2009: {'relative': 6662302, 'absolute': 787322089},
  2010: {'relative': 7800315, 'absolute': 795122404},
  2011: {'relative': 6283340, 'absolute': 801405744},
  2012: {'relative': 4758246, 'absolute': 806163990},
  2013: {'relative': 7151143, 'absolute': 813315133},
  2014: {'relative': 6334591, 'absolute': 819649724},
  2015: {'relative': 8421766, 'absolute': 828071490},
  2016: {'relative': 9518856, 'absolute': 837590346},
  2017: {'relative': 7771668, 'absolute': 845362014},
  2018: {'relative': 9254478, 'absolute': 854616492},
  2019: {'relative': 13467766, 'absolute': 868084258},
  2020: {'relative': 12634323, 'absolute': 880718581},
  2021: {'relative': 14727172, 'absolute': 895445753},
  2022: {'relative': 15197575, 'absolute': 910643328},
  2023: {'relative': 9650694, 'absolute': 920294022},
  2024: {'relative': 7897297, 'absolute': 928191319},
  2025: {'relative': 6953030, 'absolute': 935144349}}}

In [ ]:
pixels = get_deforestation_pixels(year=2000)
total_from_hist = hist[str(pixels[0])] + hist[str(pixels[1])]
reference_2000 = total_from_hist

In [ ]:
for su in spatial_units:
    assert acc_dict[su][2000]['relative'] - reference_2000 < abs(30)
    assert acc_dict[su][2000]['absolute'] - reference_2000 < abs(30)

    assert acc_dict[su][2002]['absolute'] == acc_dict[su][2000]['relative'] + acc_dict[su][2002]['relative']
    assert acc_dict[su][2002]['absolute'] == acc_dict[su][2000]['relative'] + acc_dict[su][2002]['relative']
    assert acc_dict[su][2004]['absolute'] == acc_dict[su][2000]['relative'] + acc_dict[su][2002]['relative'] + acc_dict[su][2004]['relative']

### validation
___

In [ ]:
filename = get_accumulated_deforestation_indicator_filename(2000, 2025, biome)
assert filename.exists()
print(filename)

dfr = load_dfr(filename)
dfr

In [ ]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        total = dfr["deforestation_pixels"].sum()
        reference = acc_dict["cs_5km"][year]['absolute']
        delta = total - reference
        assert delta == 0
        print(f"{spatial_unit}: year: {year}, accumulated={total}, reference={reference}, delta={delta}")

In [ ]:
# 935144349 * PIXEL_LAND_USE_AREA

# remaining native vegetation from mask (counts)
___

In [ ]:
reference = hist["100"] + hist["101"]
reference

In [ ]:
filename = get_vegetation_pixels_by_land_use_filename(year=2025, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

In [ ]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["num_pixels"].sum()
    delta = total - reference
    percent = abs(delta) / reference * 100
    print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}, percent={percent:.4f}")
    assert percent < 0.01

# remaining native vegetation from future deforestation (counts)
___

In [ ]:
filename = get_vegetation_from_deforestation(first_year=2000, last_year=2025, biome=biome)
print(filename)
assert filename.exists()

dfr = load_dfr(filename)
dfr

In [ ]:
vegetation_from_deforestation = {}
years_dict = {}
for year1 in years:
    total = 0
    years_dict[year1] = ""
    for year2 in years:
        if year2 <= year1:
            continue
        total = total + acc_dict["cs_5km"][year2]['relative']
        years_dict[year1] = years_dict[year1] + f",{year2}"
    vegetation_from_deforestation[year1] = total

In [ ]:
years_dict

In [ ]:
vegetation_from_deforestation

In [ ]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        total = dfr["vegetation_pixels"].sum()
        reference = vegetation_from_deforestation[year]
        delta = total - reference
        assert delta == 0
        print(f"{spatial_unit}: {year}: num_pixels={total}, reference={reference}, delta={delta}")

# total remaining native vegetation by year
___

In [ ]:
filename = get_vegetation_pixels_by_land_use_filename(year=2025, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

In [ ]:
total_vegetation = {}
for year in years:
    dfr = load_dfr(filename, filters={"spatial_unit": "cs_5km"})
    total_vegetation[year] = dfr["num_pixels"].sum() + vegetation_from_deforestation[year]

In [ ]:
total_vegetation

In [ ]:
filename = get_total_vegetation_filename(2000, 2025, biome)
print(filename)
assert filename.exists()

dfr = load_dfr(filename)
dfr

In [ ]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        total = dfr["vegetation_pixels"].sum()
        reference = total_vegetation[year]
        delta = total - reference
        percent = abs(delta) / reference * 100
        assert percent < 0.003
        print(f"{spatial_unit}: year: {year}, total={total}, reference={reference}, delta={delta}, percent={percent:.4f}")

# original native vegetation
___

In [10]:
reference = hist["100"] + hist["101"] + acc_dict["cs_150km"][2025]['absolute']
reference

4644384801

In [11]:
filename = get_original_vegetation_filename(2000, 2025, biome)
print(filename)
assert filename.exists()

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ams/original_vegetation_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,biome,vegetation_pixels,source
0,1,1,5105507,cs_150km,Amazônia,98920,deforestation_and_mask
1,1,1,5106752,cs_150km,Amazônia,115005,deforestation_and_mask
2,1,1,5106828,cs_150km,Amazônia,223728,deforestation_and_mask
3,1,2,5106752,cs_150km,Amazônia,1400,deforestation_and_mask
4,1,2,5106828,cs_150km,Amazônia,3215,deforestation_and_mask
...,...,...,...,...,...,...,...
386750,173075,2,1200427,cs_5km,Amazônia,4018,deforestation_and_mask
386751,173075,8,1200427,cs_5km,Amazônia,22778,deforestation_and_mask
386752,173075,9,1200427,cs_5km,Amazônia,36,deforestation_and_mask
386753,173076,8,1200427,cs_5km,Amazônia,10005,deforestation_and_mask
386754,173076,9,1200427,cs_5km,Amazônia,16830,deforestation_and_mask

In [12]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["vegetation_pixels"].sum()
    delta = total - reference
    percent = abs(delta) / reference * 100
    print(f"{spatial_unit}: total={total}, reference={reference}, delta={delta}, percent={percent:.4f}")
    assert percent < 0.005

cs_5km: total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
cs_25km: total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
cs_150km: total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
states: total=4644255185, reference=4644384801, delta=-129616, percent=0.0028
municipalities: total=4644255251, reference=4644384801, delta=-129550, percent=0.0028

# annual increase in deforestation to remaining native vegetation indicator
___

In [ ]:
filename = get_ratio_annual_increase_deforestation_to_remaining_vegetation_filename(2000, 2025, biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

In [ ]:
assert dfr.isna().sum().sum() == 0

In [ ]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        
        total1 = dfr["deforestation_pixels"].sum()
        reference1 = acc_dict["cs_5km"][year]['relative']
        delta1 = total1 - reference1
        print(f"deforestation: {spatial_unit}: year: {year}, total={total1}, reference={reference1}, delta={delta1}")
        assert delta1 == 0

        total2 = dfr["vegetation_pixels"].sum()
        reference2 = total_vegetation[year]
        delta2 = total2 - reference2
        percent2 = abs(delta2) / reference2 * 100
        print(f"vegetation: {spatial_unit}: year: {year}, total={total2}, reference={reference2}, delta={delta2}, percent={percent2}")
        assert percent2 < 0.003        

    print("_")

# accumulated deforestation to original native vegetation indicator
___

In [13]:
filename = get_ratio_accumulated_deforestation_to_original_vegetation_filename(2000, 2025, biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ams/ratio_accumulated_deforestation_to_original_vegetation_indicator_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,biome,deforestation_pixels,year,vegetation_pixels,source,counts,area,counts2
0,1,1,5105507,cs_150km,Amazônia,17368.0,2019,98920,deforestation_and_mask,17368.0,15.501211,98920
1,1,1,5105507,cs_150km,Amazônia,17826.0,2020,98920,deforestation_and_mask,17826.0,15.909984,98920
2,1,1,5105507,cs_150km,Amazônia,17988.0,2021,98920,deforestation_and_mask,17988.0,16.054571,98920
3,1,1,5105507,cs_150km,Amazônia,18077.0,2022,98920,deforestation_and_mask,18077.0,16.134005,98920
4,1,1,5105507,cs_150km,Amazônia,18215.0,2023,98920,deforestation_and_mask,18215.0,16.257172,98920
...,...,...,...,...,...,...,...,...,...,...,...,...
2692776,173076,9,1200427,cs_5km,Amazônia,409.0,2021,16830,deforestation_and_mask,409.0,0.365039,16830
2692777,173076,9,1200427,cs_5km,Amazônia,409.0,2022,16830,deforestation_and_mask,409.0,0.365039,16830
2692778,173076,9,1200427,cs_5km,Amazônia,409.0,2023,16830,deforestation_and_mask,409.0,0.365039,16830
2692779,173076,9,1200427,cs_5km,Amazônia,409.0,2024,16830,deforestation_and_mask,409.0,0.365039,16830
2692780,173076,9,1200427,cs_5km,Amazônia,409.0,2025,16830,deforestation_and_mask,409.0,0.365039,16830

In [15]:
assert dfr.isna().sum().sum() == 0

In [16]:
dfr["year"].unique()

array([2019, 2020, 2021, 2022, 2023, 2024, 2025])

In [17]:
reference2 = hist["100"] + hist["101"] + acc_dict["cs_150km"][2025]['absolute']
reference2

4644384801

In [24]:
for spatial_unit in spatial_units:
    for year in range(PRODES_DB_FIRST_YEAR, PRODES_LAST_YEAR+1):
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        
        total1 = dfr["deforestation_pixels"].sum()
        reference1 = acc_dict["cs_5km"][year]['absolute']
        delta1 = total1 - reference1
        print(f"deforestation: {spatial_unit}: year: {year}, total={total1}, reference={reference1}, delta={delta1}")
        assert delta1 == 0

        total2 = dfr["vegetation_pixels"].sum()
        delta2 = total2 - reference2
        percent2 = abs(delta2) / reference2 * 100
        print(f"vegetation: {spatial_unit}: year: {year}, total={total2}, reference={reference2}, delta={delta2}, percent={percent2:.4f}")
        assert percent2 < 0.005

    print("_")

deforestation: cs_5km: year: 2019, total=868084258.0, reference=868084258, delta=0.0
vegetation: cs_5km: year: 2019, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_5km: year: 2020, total=880718581.0, reference=880718581, delta=0.0
vegetation: cs_5km: year: 2020, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_5km: year: 2021, total=895445753.0, reference=895445753, delta=0.0
vegetation: cs_5km: year: 2021, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_5km: year: 2022, total=910643328.0, reference=910643328, delta=0.0
vegetation: cs_5km: year: 2022, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_5km: year: 2023, total=920294022.0, reference=920294022, delta=0.0
vegetation: cs_5km: year: 2023, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_5km: year: 2024, total=928191319.0, reference=928191319, delta=0.0
vegetation: cs_5km: year: 2024, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_5km: year: 2025, total=935144349.0, reference=935144349, delta=0.0
vegetation: cs_5km: year: 2025, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
_
deforestation: cs_25km: year: 2019, total=868084258.0, reference=868084258, delta=0.0
vegetation: cs_25km: year: 2019, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_25km: year: 2020, total=880718581.0, reference=880718581, delta=0.0
vegetation: cs_25km: year: 2020, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_25km: year: 2021, total=895445753.0, reference=895445753, delta=0.0
vegetation: cs_25km: year: 2021, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_25km: year: 2022, total=910643328.0, reference=910643328, delta=0.0
vegetation: cs_25km: year: 2022, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_25km: year: 2023, total=920294022.0, reference=920294022, delta=0.0
vegetation: cs_25km: year: 2023, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_25km: year: 2024, total=928191319.0, reference=928191319, delta=0.0
vegetation: cs_25km: year: 2024, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_25km: year: 2025, total=935144349.0, reference=935144349, delta=0.0
vegetation: cs_25km: year: 2025, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
_
deforestation: cs_150km: year: 2019, total=868084258.0, reference=868084258, delta=0.0
vegetation: cs_150km: year: 2019, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_150km: year: 2020, total=880718581.0, reference=880718581, delta=0.0
vegetation: cs_150km: year: 2020, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_150km: year: 2021, total=895445753.0, reference=895445753, delta=0.0
vegetation: cs_150km: year: 2021, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_150km: year: 2022, total=910643328.0, reference=910643328, delta=0.0
vegetation: cs_150km: year: 2022, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_150km: year: 2023, total=920294022.0, reference=920294022, delta=0.0
vegetation: cs_150km: year: 2023, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_150km: year: 2024, total=928191319.0, reference=928191319, delta=0.0
vegetation: cs_150km: year: 2024, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: cs_150km: year: 2025, total=935144349.0, reference=935144349, delta=0.0
vegetation: cs_150km: year: 2025, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
_
deforestation: states: year: 2019, total=868084258.0, reference=868084258, delta=0.0
vegetation: states: year: 2019, total=4644255185, reference=4644384801, delta=-129616, percent=0.0028
deforestation: states: year: 2020, total=880718581.0, reference=880718581, delta=0.0
vegetation: states: year: 2020, total=4644255185, reference=4644384801, delta=-129616, percent=0.0028
deforestation: states: year: 2021, total=895445753.0, reference=895445753, delta=0.0
vegetation: states: year: 2021, total=4644255185, reference=4644384801, delta=-129616, percent=0.0028
deforestation: states: year: 2022, total=910643328.0, reference=910643328, delta=0.0
vegetation: states: year: 2022, total=4644255185, reference=4644384801, delta=-129616, percent=0.0028
deforestation: states: year: 2023, total=920294022.0, reference=920294022, delta=0.0
vegetation: states: year: 2023, total=4644255185, reference=4644384801, delta=-129616, percent=0.0028
deforestation: states: year: 2024, total=928191319.0, reference=928191319, delta=0.0
vegetation: states: year: 2024, total=4644255185, reference=4644384801, delta=-129616, percent=0.0028
deforestation: states: year: 2025, total=935144349.0, reference=935144349, delta=0.0
vegetation: states: year: 2025, total=4644255185, reference=4644384801, delta=-129616, percent=0.0028
_
deforestation: municipalities: year: 2019, total=868084258.0, reference=868084258, delta=0.0
vegetation: municipalities: year: 2019, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: municipalities: year: 2020, total=880718581.0, reference=880718581, delta=0.0
vegetation: municipalities: year: 2020, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: municipalities: year: 2021, total=895445753.0, reference=895445753, delta=0.0
vegetation: municipalities: year: 2021, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: municipalities: year: 2022, total=910643328.0, reference=910643328, delta=0.0
vegetation: municipalities: year: 2022, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: municipalities: year: 2023, total=920294022.0, reference=920294022, delta=0.0
vegetation: municipalities: year: 2023, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: municipalities: year: 2024, total=928191319.0, reference=928191319, delta=0.0
vegetation: municipalities: year: 2024, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
deforestation: municipalities: year: 2025, total=935144349.0, reference=935144349, delta=0.0
vegetation: municipalities: year: 2025, total=4644255251, reference=4644384801, delta=-129550, percent=0.0028
_