In [1]:
import numpy as np
import pandas as pd

from pathlib import Path

# vars
___

In [2]:
ROOT_DIR = Path("/home/marcosilva/terrabrasilis/prodes/")
CACHE_DIR = ROOT_DIR / "cache"

In [3]:
reference = {}

biome = "Amazônia"

spatial_units = ["cs_5km", "cs_25km", "cs_150km", "states", "municipalities"]

# helpers
___

In [4]:
def get_deforestation_pixels_by_land_use_filename(year, biome):
    return CACHE_DIR / f"count/spatial_unit_deforestation_landuse_counts_b{biome}_y{year}.pkl"


def get_vegetation_pixels_by_land_use_filename(year, biome):
    return CACHE_DIR / f"count/spatial_unit_vegetation_landuse_counts_b{biome}_y{year}.pkl"


def get_annual_increase_in_deforestation_indicator_filename(first_year, last_year, biome):
    return CACHE_DIR / f"annual_increase_in_deforestation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_accumulated_deforestation_indicator_filename(first_year, last_year, biome):
    return CACHE_DIR / f"accumulated_deforestation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_vegetation_from_mask_filename(biome):
    return CACHE_DIR / f"vegetation_from_mask_b{biome}.pkl"


def get_vegetation_from_deforestation(first_year, last_year, biome):
    return CACHE_DIR / f"vegetation_from_deforestation_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_total_vegetation_filename(first_year, last_year, biome):
    return CACHE_DIR / f"vegetation_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_ratio_deforestation_to_vegetation_filename(first_year, last_year, biome):
    return CACHE_DIR / f"ratio_accumulated_deforestation_to_vegetation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def load_dfr(filename, filters={}):
    assert filename.exists()
    
    dfr = pd.read_pickle(filename)

    mask = pd.Series(True, index=dfr.index)

    for col, value in filters.items():
        if isinstance(value, list):
            mask &= dfr[col].isin(value)
        else:
            mask &= dfr[col] == value

    return dfr[mask]

# deforestation pixels by land use (counts)
___

## prodes 2000

### hist (gdalinfo -hist)

(gdal1) marcosilva@like01:~/terrabrasilis/prodes/tmp$ gdalinfo -hist prodes_2000.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
Driver: GTiff/GeoTIFF
Files: prodes_2000.tif
       prodes_2000.tif.aux.xml
Size is 113737, 81560
Coordinate System is:
GEOGCRS["SIRGAS 2000",
    DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
        ELLIPSOID["GRS 1980",6378137,298.257222101004,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4674]]
Data axis to CRS axis mapping: 2,1
Origin = (-73.983180000000004,5.269580000000000)
Pixel Size = (0.000268900006155,-0.000268899950956)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -73.9831800,   5.2695800) ( 73d58'59.45"W,  5d16'10.49"N)
Lower Left  ( -73.9831800, -16.6619000) ( 73d58'59.45"W, 16d39'42.84"S)
Upper Right ( -43.3993000,   5.2695800) ( 43d23'57.48"W,  5d16'10.49"N)
Lower Right ( -43.3993000, -16.6619000) ( 43d23'57.48"W, 16d39'42.84"S)
Center      ( -58.6912400,  -5.6961600) ( 58d41'28.46"W,  5d41'46.18"S)
Band 1 Block=113737x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=1.000 
  256 buckets from -0.00196078 to 1.00196:
  4752981555 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 14828887 
  NoData Value=-3.4028235e+38
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=0.0031102090111207
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=0.055682453340745
    STATISTICS_VALID_PERCENT=51.4

### validation

In [9]:
reference = 14828887
reference_2000 = reference

year = 2000

filename = get_deforestation_pixels_by_land_use_filename(year=year, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/count/spatial_unit_deforestation_landuse_counts_bAmazônia_y2000.pkl

         suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0           1            1  5105507     cs_150km  2000  Amazônia        8775
1           1            1  5106752     cs_150km  2000  Amazônia        9371
2           1            1  5106828     cs_150km  2000  Amazônia        4841
3           1            2  5106828     cs_150km  2000  Amazônia         248
4           1            7  5105507     cs_150km  2000  Amazônia      401828
...       ...          ...      ...          ...   ...       ...         ...
20006  172910            5  1302405       cs_5km  2000  Amazônia          12
20007  172911            5  1302405       cs_5km  2000  Amazônia          96
20008  173019            7  1506583       cs_5km  2000  Amazônia         521
20009  173027            7  1506583       cs_5km  2000  Amazônia        1786
20010  173032            7  1506583       cs_5km  2000  Amazônia         685

[20011 rows x 7 columns]

In [10]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["num_pixels"].sum()
    delta = total - reference
    assert delta == 0
    print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}")

cs_5km: num_pixels=14828887, reference=14828887, delta=0
cs_25km: num_pixels=14828887, reference=14828887, delta=0
cs_150km: num_pixels=14828887, reference=14828887, delta=0
states: num_pixels=14828887, reference=14828887, delta=0
municipalities: num_pixels=14828887, reference=14828887, delta=0

## prodes 2015

### hist (gdalinfo -hist)

(gdal1) marcosilva@like01:~/terrabrasilis/prodes/tmp$ gdalinfo -hist prodes_2015.tif 
0...10...20...30...40...50...60...70...80...90...100 - done.
Driver: GTiff/GeoTIFF
Files: prodes_2015.tif
Size is 113737, 81560
Coordinate System is:
GEOGCRS["SIRGAS 2000",
    DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
        ELLIPSOID["GRS 1980",6378137,298.257222101004,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4674]]
Data axis to CRS axis mapping: 2,1
Origin = (-73.983180000000004,5.269580000000000)
Pixel Size = (0.000268900006155,-0.000268899950956)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -73.9831800,   5.2695800) ( 73d58'59.45"W,  5d16'10.49"N)
Lower Left  ( -73.9831800, -16.6619000) ( 73d58'59.45"W, 16d39'42.84"S)
Upper Right ( -43.3993000,   5.2695800) ( 43d23'57.48"W,  5d16'10.49"N)
Lower Right ( -43.3993000, -16.6619000) ( 43d23'57.48"W, 16d39'42.84"S)
Center      ( -58.6912400,  -5.6961600) ( 58d41'28.46"W,  5d41'46.18"S)
Band 1 Block=113737x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=1.000 
  256 buckets from -0.00196078 to 1.00196:
  4759388674 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8421768 
  NoData Value=-3.4028235e+38
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MINIMUM=0
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=0.0017809442728521
    STATISTICS_STDDEV=0.042163639671511
    STATISTICS_VALID_PERCENT=51.25

### validation

In [11]:
reference = 8421768
reference_2015 = reference

year = 2015

filename = get_deforestation_pixels_by_land_use_filename(year=year, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/count/spatial_unit_deforestation_landuse_counts_bAmazônia_y2015.pkl

         suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0           1            1  5106752     cs_150km  2015  Amazônia         120
1           1            1  5106828     cs_150km  2015  Amazônia        3336
2           1            2  5106828     cs_150km  2015  Amazônia          83
3           1            7  5106828     cs_150km  2015  Amazônia         170
4           1            8  5106828     cs_150km  2015  Amazônia           2
...       ...          ...      ...          ...   ...       ...         ...
48071  173031            5  1506583       cs_5km  2015  Amazônia          23
48072  173031            9  1506583       cs_5km  2015  Amazônia          92
48073  173032            7  1506583       cs_5km  2015  Amazônia         362
48074  173032            8  1506583       cs_5km  2015  Amazônia           7
48075  173032            9  1506583       cs_5km  2015  Amazônia          70

[48076 rows x 7 columns]

In [12]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["num_pixels"].sum()
    delta = total - reference
    assert delta == 0
    print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}")

cs_5km: num_pixels=8421768, reference=8421768, delta=0
cs_25km: num_pixels=8421768, reference=8421768, delta=0
cs_150km: num_pixels=8421768, reference=8421768, delta=0
states: num_pixels=8421768, reference=8421768, delta=0
municipalities: num_pixels=8421768, reference=8421768, delta=0

## prodes 2024

### hist (gdalinfo -hist)

(gdal1) marcosilva@like01:~/terrabrasilis/prodes/tmp$ gdalinfo -hist prodes_2024.tif 
0...10...20...30...40...50...60...70...80...90...100 - done.
Driver: GTiff/GeoTIFF
Files: prodes_2024.tif
Size is 113737, 81560
Coordinate System is:
GEOGCRS["SIRGAS 2000",
    DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
        ELLIPSOID["GRS 1980",6378137,298.257222101004,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4674]]
Data axis to CRS axis mapping: 2,1
Origin = (-73.983180000000004,5.269580000000000)
Pixel Size = (0.000268900006155,-0.000268899950956)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -73.9831800,   5.2695800) ( 73d58'59.45"W,  5d16'10.49"N)
Lower Left  ( -73.9831800, -16.6619000) ( 73d58'59.45"W, 16d39'42.84"S)
Upper Right ( -43.3993000,   5.2695800) ( 43d23'57.48"W,  5d16'10.49"N)
Lower Right ( -43.3993000, -16.6619000) ( 43d23'57.48"W, 16d39'42.84"S)
Center      ( -58.6912400,  -5.6961600) ( 58d41'28.46"W,  5d41'46.18"S)
Band 1 Block=113737x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=1.000 
  256 buckets from -0.00196078 to 1.00196:
  4759913145 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7897297 
  NoData Value=-3.4028235e+38
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MINIMUM=0
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=0.0016761617485929
    STATISTICS_STDDEV=0.040906628196237
    STATISTICS_VALID_PERCENT=51.25

### validation

In [13]:
reference = 7897297
reference_2024 = reference

year = 2024

filename = get_deforestation_pixels_by_land_use_filename(year=year, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/count/spatial_unit_deforestation_landuse_counts_bAmazônia_y2024.pkl

         suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0           1            1  5105507     cs_150km  2024  Amazônia          60
1           1            1  5106752     cs_150km  2024  Amazônia         682
2           1            1  5106828     cs_150km  2024  Amazônia         195
3           1            7  5105507     cs_150km  2024  Amazônia         834
4           1            7  5106828     cs_150km  2024  Amazônia         431
...       ...          ...      ...          ...   ...       ...         ...
45045  172982            5  1506583       cs_5km  2024  Amazônia         114
45046  172984            5  1506583       cs_5km  2024  Amazônia         410
45047  172985            5  1506583       cs_5km  2024  Amazônia         189
45048  173029            5  1506583       cs_5km  2024  Amazônia         171
45049  173030            5  1506583       cs_5km  2024  Amazônia         199

[45050 rows x 7 columns]

In [14]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["num_pixels"].sum()
    delta = total - reference
    assert delta == 0
    print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}")

cs_5km: num_pixels=7897297, reference=7897297, delta=0
cs_25km: num_pixels=7897297, reference=7897297, delta=0
cs_150km: num_pixels=7897297, reference=7897297, delta=0
states: num_pixels=7897297, reference=7897297, delta=0
municipalities: num_pixels=7897297, reference=7897297, delta=0

# annual increase in deforestation indicator (relative counts)
___

In [15]:
filename = get_annual_increase_in_deforestation_indicator_filename(2000, 2025, biome)
assert filename.exists()
print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/annual_increase_in_deforestation_indicator_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,year,biome,num_pixels,counts
0,1,1,5105507,cs_150km,2000,Amazônia,8775,8775
1,1,1,5106752,cs_150km,2000,Amazônia,9371,9371
2,1,1,5106828,cs_150km,2000,Amazônia,4841,4841
3,1,2,5106828,cs_150km,2000,Amazônia,248,248
4,1,7,5105507,cs_150km,2000,Amazônia,401828,401828
...,...,...,...,...,...,...,...,...
34183,172961,7,1502764,cs_5km,2025,Amazônia,161,161
34184,172961,7,1507300,cs_5km,2025,Amazônia,127,127
34185,172980,5,1506583,cs_5km,2025,Amazônia,80,80
34186,172982,5,1506583,cs_5km,2025,Amazônia,9,9
34187,173030,5,1506583,cs_5km,2025,Amazônia,81,81

In [16]:
reference_dict = {
    2000: reference_2000,
    2015: reference_2015,
    2024: reference_2024,
}
    
for year in [2000, 2015, 2024]:
    for spatial_unit in spatial_units:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        reference = reference_dict[year]
        total = dfr["num_pixels"].sum()
        delta = total - reference
        assert delta == 0
        print(f"{spatial_unit}: year: {year}, num_pixels={total}, reference={reference}, delta={delta}")

cs_5km: year: 2000, num_pixels=14828887, reference=14828887, delta=0
cs_25km: year: 2000, num_pixels=14828887, reference=14828887, delta=0
cs_150km: year: 2000, num_pixels=14828887, reference=14828887, delta=0
states: year: 2000, num_pixels=14828887, reference=14828887, delta=0
municipalities: year: 2000, num_pixels=14828887, reference=14828887, delta=0
cs_5km: year: 2015, num_pixels=8421768, reference=8421768, delta=0
cs_25km: year: 2015, num_pixels=8421768, reference=8421768, delta=0
cs_150km: year: 2015, num_pixels=8421768, reference=8421768, delta=0
states: year: 2015, num_pixels=8421768, reference=8421768, delta=0
municipalities: year: 2015, num_pixels=8421768, reference=8421768, delta=0
cs_5km: year: 2024, num_pixels=7897297, reference=7897297, delta=0
cs_25km: year: 2024, num_pixels=7897297, reference=7897297, delta=0
cs_150km: year: 2024, num_pixels=7897297, reference=7897297, delta=0
states: year: 2024, num_pixels=7897297, reference=7897297, delta=0
municipalities: year: 2024, num_pixels=7897297, reference=7897297, delta=0

# accumulated deforestation indicator (absolute counts)
___

In [17]:
filename = get_annual_increase_in_deforestation_indicator_filename(2000, 2025, biome)
print(filename)
assert filename.exists()

years = np.arange(2000, 2025+1, 1).tolist()

annual_dfr = load_dfr(filename)

acc_dict = {}

for spatial_unit in spatial_units:
    _abs = 0
    acc_dict[spatial_unit] = {}
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        
        _rel = dfr["num_pixels"].sum()
        _abs = _abs + _rel

        acc_dict[spatial_unit].update({
            year: {
                "relative": _rel,
                "absolute": _abs,
            }
        })

/home/marcosilva/terrabrasilis/prodes/cache/annual_increase_in_deforestation_indicator_bAmazônia_from_y2000_to_y2025.pkl

#### validating dict

In [18]:
acc_dict

{'cs_5km': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547561, 'absolute': 18376448},
  2003: {'relative': 0, 'absolute': 18376448},
  2004: {'relative': 3163554, 'absolute': 21540002},
  2005: {'relative': 0, 'absolute': 21540002},
  2006: {'relative': 2146609, 'absolute': 23686611},
  2007: {'relative': 741550200, 'absolute': 765236811},
  2008: {'relative': 15423937, 'absolute': 780660748},
  2009: {'relative': 6662302, 'absolute': 787323050},
  2010: {'relative': 7800322, 'absolute': 795123372},
  2011: {'relative': 6283342, 'absolute': 801406714},
  2012: {'relative': 4758246, 'absolute': 806164960},
  2013: {'relative': 7151147, 'absolute': 813316107},
  2014: {'relative': 6334593, 'absolute': 819650700},
  2015: {'relative': 8421768, 'absolute': 828072468},
  2016: {'relative': 9518856, 'absolute': 837591324},
  2017: {'relative': 7771668, 'absolute': 845362992},
  2018: {'relative': 9254483, 'absolute': 854617475},
  2019: {'relative': 13467774, 'absolute': 868085249},
  2020: {'relative': 12634323, 'absolute': 880719572},
  2021: {'relative': 14727172, 'absolute': 895446744},
  2022: {'relative': 15197580, 'absolute': 910644324},
  2023: {'relative': 9650694, 'absolute': 920295018},
  2024: {'relative': 7897297, 'absolute': 928192315},
  2025: {'relative': 6953030, 'absolute': 935145345}},
 'cs_25km': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547561, 'absolute': 18376448},
  2003: {'relative': 0, 'absolute': 18376448},
  2004: {'relative': 3163554, 'absolute': 21540002},
  2005: {'relative': 0, 'absolute': 21540002},
  2006: {'relative': 2146609, 'absolute': 23686611},
  2007: {'relative': 741550200, 'absolute': 765236811},
  2008: {'relative': 15423937, 'absolute': 780660748},
  2009: {'relative': 6662302, 'absolute': 787323050},
  2010: {'relative': 7800322, 'absolute': 795123372},
  2011: {'relative': 6283342, 'absolute': 801406714},
  2012: {'relative': 4758246, 'absolute': 806164960},
  2013: {'relative': 7151147, 'absolute': 813316107},
  2014: {'relative': 6334593, 'absolute': 819650700},
  2015: {'relative': 8421768, 'absolute': 828072468},
  2016: {'relative': 9518856, 'absolute': 837591324},
  2017: {'relative': 7771668, 'absolute': 845362992},
  2018: {'relative': 9254483, 'absolute': 854617475},
  2019: {'relative': 13467774, 'absolute': 868085249},
  2020: {'relative': 12634323, 'absolute': 880719572},
  2021: {'relative': 14727172, 'absolute': 895446744},
  2022: {'relative': 15197580, 'absolute': 910644324},
  2023: {'relative': 9650694, 'absolute': 920295018},
  2024: {'relative': 7897297, 'absolute': 928192315},
  2025: {'relative': 6953030, 'absolute': 935145345}},
 'cs_150km': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547561, 'absolute': 18376448},
  2003: {'relative': 0, 'absolute': 18376448},
  2004: {'relative': 3163554, 'absolute': 21540002},
  2005: {'relative': 0, 'absolute': 21540002},
  2006: {'relative': 2146609, 'absolute': 23686611},
  2007: {'relative': 741550200, 'absolute': 765236811},
  2008: {'relative': 15423937, 'absolute': 780660748},
  2009: {'relative': 6662302, 'absolute': 787323050},
  2010: {'relative': 7800322, 'absolute': 795123372},
  2011: {'relative': 6283342, 'absolute': 801406714},
  2012: {'relative': 4758246, 'absolute': 806164960},
  2013: {'relative': 7151147, 'absolute': 813316107},
  2014: {'relative': 6334593, 'absolute': 819650700},
  2015: {'relative': 8421768, 'absolute': 828072468},
  2016: {'relative': 9518856, 'absolute': 837591324},
  2017: {'relative': 7771668, 'absolute': 845362992},
  2018: {'relative': 9254483, 'absolute': 854617475},
  2019: {'relative': 13467774, 'absolute': 868085249},
  2020: {'relative': 12634323, 'absolute': 880719572},
  2021: {'relative': 14727172, 'absolute': 895446744},
  2022: {'relative': 15197580, 'absolute': 910644324},
  2023: {'relative': 9650694, 'absolute': 920295018},
  2024: {'relative': 7897297, 'absolute': 928192315},
  2025: {'relative': 6953030, 'absolute': 935145345}},
 'states': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547561, 'absolute': 18376448},
  2003: {'relative': 0, 'absolute': 18376448},
  2004: {'relative': 3163554, 'absolute': 21540002},
  2005: {'relative': 0, 'absolute': 21540002},
  2006: {'relative': 2146609, 'absolute': 23686611},
  2007: {'relative': 741550200, 'absolute': 765236811},
  2008: {'relative': 15423937, 'absolute': 780660748},
  2009: {'relative': 6662302, 'absolute': 787323050},
  2010: {'relative': 7800322, 'absolute': 795123372},
  2011: {'relative': 6283342, 'absolute': 801406714},
  2012: {'relative': 4758246, 'absolute': 806164960},
  2013: {'relative': 7151147, 'absolute': 813316107},
  2014: {'relative': 6334593, 'absolute': 819650700},
  2015: {'relative': 8421768, 'absolute': 828072468},
  2016: {'relative': 9518856, 'absolute': 837591324},
  2017: {'relative': 7771668, 'absolute': 845362992},
  2018: {'relative': 9254483, 'absolute': 854617475},
  2019: {'relative': 13467774, 'absolute': 868085249},
  2020: {'relative': 12634323, 'absolute': 880719572},
  2021: {'relative': 14727172, 'absolute': 895446744},
  2022: {'relative': 15197580, 'absolute': 910644324},
  2023: {'relative': 9650694, 'absolute': 920295018},
  2024: {'relative': 7897297, 'absolute': 928192315},
  2025: {'relative': 6953030, 'absolute': 935145345}},
 'municipalities': {2000: {'relative': 14828887, 'absolute': 14828887},
  2001: {'relative': 0, 'absolute': 14828887},
  2002: {'relative': 3547561, 'absolute': 18376448},
  2003: {'relative': 0, 'absolute': 18376448},
  2004: {'relative': 3163554, 'absolute': 21540002},
  2005: {'relative': 0, 'absolute': 21540002},
  2006: {'relative': 2146609, 'absolute': 23686611},
  2007: {'relative': 741550200, 'absolute': 765236811},
  2008: {'relative': 15423937, 'absolute': 780660748},
  2009: {'relative': 6662302, 'absolute': 787323050},
  2010: {'relative': 7800322, 'absolute': 795123372},
  2011: {'relative': 6283342, 'absolute': 801406714},
  2012: {'relative': 4758246, 'absolute': 806164960},
  2013: {'relative': 7151147, 'absolute': 813316107},
  2014: {'relative': 6334593, 'absolute': 819650700},
  2015: {'relative': 8421768, 'absolute': 828072468},
  2016: {'relative': 9518856, 'absolute': 837591324},
  2017: {'relative': 7771668, 'absolute': 845362992},
  2018: {'relative': 9254483, 'absolute': 854617475},
  2019: {'relative': 13467774, 'absolute': 868085249},
  2020: {'relative': 12634323, 'absolute': 880719572},
  2021: {'relative': 14727172, 'absolute': 895446744},
  2022: {'relative': 15197580, 'absolute': 910644324},
  2023: {'relative': 9650694, 'absolute': 920295018},
  2024: {'relative': 7897297, 'absolute': 928192315},
  2025: {'relative': 6953030, 'absolute': 935145345}}}

In [19]:
for su in spatial_units:
    assert acc_dict[su][2000]['relative'] == reference_2000
    assert acc_dict[su][2000]['absolute'] == reference_2000

    assert acc_dict[su][2002]['absolute'] == acc_dict[su][2000]['relative'] + acc_dict[su][2002]['relative']
    assert acc_dict[su][2002]['absolute'] == acc_dict[su][2000]['relative'] + acc_dict[su][2002]['relative']
    assert acc_dict[su][2004]['absolute'] == acc_dict[su][2000]['relative'] + acc_dict[su][2002]['relative'] + acc_dict[su][2004]['relative']

### validation
___

In [20]:
filename = get_accumulated_deforestation_indicator_filename(2000, 2025, biome)
assert filename.exists()
print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/accumulated_deforestation_indicator_bAmazônia_from_y2000_to_y2025.pkl

          suid  land_use_id  geocode spatial_unit     biome  counts  year
0            1            1  5105507     cs_150km  Amazônia    8775  2000
1            1            1  5106752     cs_150km  Amazônia    9371  2000
2            1            1  5106828     cs_150km  Amazônia    4841  2000
3            1            2  5106828     cs_150km  Amazônia     248  2000
4            1            7  5105507     cs_150km  Amazônia  401828  2000
...        ...          ...      ...          ...       ...     ...   ...
224950  173068            5  1200203       cs_5km  Amazônia      32  2025
224951  173069            1  1200203       cs_5km  Amazônia      47  2025
224952  173069            5  1200203       cs_5km  Amazônia     161  2025
224953  173071            2  1200427       cs_5km  Amazônia     521  2025
224954  173076            9  1200427       cs_5km  Amazônia     409  2025

[4175289 rows x 7 columns]

In [21]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        total = dfr["counts"].sum()
        reference = acc_dict["cs_5km"][year]['absolute']
        delta = total - reference
        print(f"{spatial_unit}: year: {year}, accumulated={total}, reference={reference}, delta={delta}")

cs_5km: year: 2000, accumulated=14828887, reference=14828887, delta=0
cs_5km: year: 2001, accumulated=14828887, reference=14828887, delta=0
cs_5km: year: 2002, accumulated=18376448, reference=18376448, delta=0
cs_5km: year: 2003, accumulated=18376448, reference=18376448, delta=0
cs_5km: year: 2004, accumulated=21540002, reference=21540002, delta=0
cs_5km: year: 2005, accumulated=21540002, reference=21540002, delta=0
cs_5km: year: 2006, accumulated=23686611, reference=23686611, delta=0
cs_5km: year: 2007, accumulated=765236811, reference=765236811, delta=0
cs_5km: year: 2008, accumulated=780660748, reference=780660748, delta=0
cs_5km: year: 2009, accumulated=787323050, reference=787323050, delta=0
cs_5km: year: 2010, accumulated=795123372, reference=795123372, delta=0
cs_5km: year: 2011, accumulated=801406714, reference=801406714, delta=0
cs_5km: year: 2012, accumulated=806164960, reference=806164960, delta=0
cs_5km: year: 2013, accumulated=813316107, reference=813316107, delta=0
cs_5km: year: 2014, accumulated=819650700, reference=819650700, delta=0
cs_5km: year: 2015, accumulated=828072468, reference=828072468, delta=0
cs_5km: year: 2016, accumulated=837591324, reference=837591324, delta=0
cs_5km: year: 2017, accumulated=845362992, reference=845362992, delta=0
cs_5km: year: 2018, accumulated=854617475, reference=854617475, delta=0
cs_5km: year: 2019, accumulated=868085249, reference=868085249, delta=0
cs_5km: year: 2020, accumulated=880719572, reference=880719572, delta=0
cs_5km: year: 2021, accumulated=895446744, reference=895446744, delta=0
cs_5km: year: 2022, accumulated=910644324, reference=910644324, delta=0
cs_5km: year: 2023, accumulated=920295018, reference=920295018, delta=0
cs_5km: year: 2024, accumulated=928192315, reference=928192315, delta=0
cs_5km: year: 2025, accumulated=935145345, reference=935145345, delta=0
cs_25km: year: 2000, accumulated=14828887, reference=14828887, delta=0
cs_25km: year: 2001, accumulated=14828887, reference=14828887, delta=0
cs_25km: year: 2002, accumulated=18376448, reference=18376448, delta=0
cs_25km: year: 2003, accumulated=18376448, reference=18376448, delta=0
cs_25km: year: 2004, accumulated=21540002, reference=21540002, delta=0
cs_25km: year: 2005, accumulated=21540002, reference=21540002, delta=0
cs_25km: year: 2006, accumulated=23686611, reference=23686611, delta=0
cs_25km: year: 2007, accumulated=765236811, reference=765236811, delta=0
cs_25km: year: 2008, accumulated=780660748, reference=780660748, delta=0
cs_25km: year: 2009, accumulated=787323050, reference=787323050, delta=0
cs_25km: year: 2010, accumulated=795123372, reference=795123372, delta=0
cs_25km: year: 2011, accumulated=801406714, reference=801406714, delta=0
cs_25km: year: 2012, accumulated=806164960, reference=806164960, delta=0
cs_25km: year: 2013, accumulated=813316107, reference=813316107, delta=0
cs_25km: year: 2014, accumulated=819650700, reference=819650700, delta=0
cs_25km: year: 2015, accumulated=828072468, reference=828072468, delta=0
cs_25km: year: 2016, accumulated=837591324, reference=837591324, delta=0
cs_25km: year: 2017, accumulated=845362992, reference=845362992, delta=0
cs_25km: year: 2018, accumulated=854617475, reference=854617475, delta=0
cs_25km: year: 2019, accumulated=868085249, reference=868085249, delta=0
cs_25km: year: 2020, accumulated=880719572, reference=880719572, delta=0
cs_25km: year: 2021, accumulated=895446744, reference=895446744, delta=0
cs_25km: year: 2022, accumulated=910644324, reference=910644324, delta=0
cs_25km: year: 2023, accumulated=920295018, reference=920295018, delta=0
cs_25km: year: 2024, accumulated=928192315, reference=928192315, delta=0
cs_25km: year: 2025, accumulated=935145345, reference=935145345, delta=0
cs_150km: year: 2000, accumulated=14828887, reference=14828887, delta=0
cs_150km: year: 2001, accumulated=14828887, reference=14828887, delta=0
cs_150km: year: 2002, accumulated=18376448, reference=18376448, delta=0
cs_150km: year: 2003, accumulated=18376448, reference=18376448, delta=0
cs_150km: year: 2004, accumulated=21540002, reference=21540002, delta=0
cs_150km: year: 2005, accumulated=21540002, reference=21540002, delta=0
cs_150km: year: 2006, accumulated=23686611, reference=23686611, delta=0
cs_150km: year: 2007, accumulated=765236811, reference=765236811, delta=0
cs_150km: year: 2008, accumulated=780660748, reference=780660748, delta=0
cs_150km: year: 2009, accumulated=787323050, reference=787323050, delta=0
cs_150km: year: 2010, accumulated=795123372, reference=795123372, delta=0
cs_150km: year: 2011, accumulated=801406714, reference=801406714, delta=0
cs_150km: year: 2012, accumulated=806164960, reference=806164960, delta=0
cs_150km: year: 2013, accumulated=813316107, reference=813316107, delta=0
cs_150km: year: 2014, accumulated=819650700, reference=819650700, delta=0
cs_150km: year: 2015, accumulated=828072468, reference=828072468, delta=0
cs_150km: year: 2016, accumulated=837591324, reference=837591324, delta=0
cs_150km: year: 2017, accumulated=845362992, reference=845362992, delta=0
cs_150km: year: 2018, accumulated=854617475, reference=854617475, delta=0
cs_150km: year: 2019, accumulated=868085249, reference=868085249, delta=0
cs_150km: year: 2020, accumulated=880719572, reference=880719572, delta=0
cs_150km: year: 2021, accumulated=895446744, reference=895446744, delta=0
cs_150km: year: 2022, accumulated=910644324, reference=910644324, delta=0
cs_150km: year: 2023, accumulated=920295018, reference=920295018, delta=0
cs_150km: year: 2024, accumulated=928192315, reference=928192315, delta=0
cs_150km: year: 2025, accumulated=935145345, reference=935145345, delta=0
states: year: 2000, accumulated=14828887, reference=14828887, delta=0
states: year: 2001, accumulated=14828887, reference=14828887, delta=0
states: year: 2002, accumulated=18376448, reference=18376448, delta=0
states: year: 2003, accumulated=18376448, reference=18376448, delta=0
states: year: 2004, accumulated=21540002, reference=21540002, delta=0
states: year: 2005, accumulated=21540002, reference=21540002, delta=0
states: year: 2006, accumulated=23686611, reference=23686611, delta=0
states: year: 2007, accumulated=765236811, reference=765236811, delta=0
states: year: 2008, accumulated=780660748, reference=780660748, delta=0
states: year: 2009, accumulated=787323050, reference=787323050, delta=0
states: year: 2010, accumulated=795123372, reference=795123372, delta=0
states: year: 2011, accumulated=801406714, reference=801406714, delta=0
states: year: 2012, accumulated=806164960, reference=806164960, delta=0
states: year: 2013, accumulated=813316107, reference=813316107, delta=0
states: year: 2014, accumulated=819650700, reference=819650700, delta=0
states: year: 2015, accumulated=828072468, reference=828072468, delta=0
states: year: 2016, accumulated=837591324, reference=837591324, delta=0
states: year: 2017, accumulated=845362992, reference=845362992, delta=0
states: year: 2018, accumulated=854617475, reference=854617475, delta=0
states: year: 2019, accumulated=868085249, reference=868085249, delta=0
states: year: 2020, accumulated=880719572, reference=880719572, delta=0
states: year: 2021, accumulated=895446744, reference=895446744, delta=0
states: year: 2022, accumulated=910644324, reference=910644324, delta=0
states: year: 2023, accumulated=920295018, reference=920295018, delta=0
states: year: 2024, accumulated=928192315, reference=928192315, delta=0
states: year: 2025, accumulated=935145345, reference=935145345, delta=0
municipalities: year: 2000, accumulated=14828887, reference=14828887, delta=0
municipalities: year: 2001, accumulated=14828887, reference=14828887, delta=0
municipalities: year: 2002, accumulated=18376448, reference=18376448, delta=0
municipalities: year: 2003, accumulated=18376448, reference=18376448, delta=0
municipalities: year: 2004, accumulated=21540002, reference=21540002, delta=0
municipalities: year: 2005, accumulated=21540002, reference=21540002, delta=0
municipalities: year: 2006, accumulated=23686611, reference=23686611, delta=0
municipalities: year: 2007, accumulated=765236811, reference=765236811, delta=0
municipalities: year: 2008, accumulated=780660748, reference=780660748, delta=0
municipalities: year: 2009, accumulated=787323050, reference=787323050, delta=0
municipalities: year: 2010, accumulated=795123372, reference=795123372, delta=0
municipalities: year: 2011, accumulated=801406714, reference=801406714, delta=0
municipalities: year: 2012, accumulated=806164960, reference=806164960, delta=0
municipalities: year: 2013, accumulated=813316107, reference=813316107, delta=0
municipalities: year: 2014, accumulated=819650700, reference=819650700, delta=0
municipalities: year: 2015, accumulated=828072468, reference=828072468, delta=0
municipalities: year: 2016, accumulated=837591324, reference=837591324, delta=0
municipalities: year: 2017, accumulated=845362992, reference=845362992, delta=0
municipalities: year: 2018, accumulated=854617475, reference=854617475, delta=0
municipalities: year: 2019, accumulated=868085249, reference=868085249, delta=0
municipalities: year: 2020, accumulated=880719572, reference=880719572, delta=0
municipalities: year: 2021, accumulated=895446744, reference=895446744, delta=0
municipalities: year: 2022, accumulated=910644324, reference=910644324, delta=0
municipalities: year: 2023, accumulated=920295018, reference=920295018, delta=0
municipalities: year: 2024, accumulated=928192315, reference=928192315, delta=0
municipalities: year: 2025, accumulated=935145345, reference=935145345, delta=0

# native vegetation from mask (counts)
___

## hist (gdalinfo -hist)

(gdal1) marcosilva@like01:~/terrabrasilis/prodes/tmp$ gdalinfo -hist prodes_vegetation.tif 
0...10...20...30...40...50...60...70...80...90...100 - done.
Driver: GTiff/GeoTIFF
Files: prodes_vegetation.tif
Size is 113737, 81560
Coordinate System is:
GEOGCRS["SIRGAS 2000",
    DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
        ELLIPSOID["GRS 1980",6378137,298.257222101004,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4674]]
Data axis to CRS axis mapping: 2,1
Origin = (-73.983180000000004,5.269580000000000)
Pixel Size = (0.000268900006155,-0.000268899950956)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -73.9831800,   5.2695800) ( 73d58'59.45"W,  5d16'10.49"N)
Lower Left  ( -73.9831800, -16.6619000) ( 73d58'59.45"W, 16d39'42.84"S)
Upper Right ( -43.3993000,   5.2695800) ( 43d23'57.48"W,  5d16'10.49"N)
Lower Right ( -43.3993000, -16.6619000) ( 43d23'57.48"W, 16d39'42.84"S)
Center      ( -58.6912400,  -5.6961600) ( 58d41'28.46"W,  5d41'46.18"S)
Band 1 Block=113737x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=1.000 
  256 buckets from -0.00196078 to 1.00196:
  1058569990 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3709240452 
  NoData Value=-3.4028235e+38
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MINIMUM=0
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=0.77764538664898
    STATISTICS_STDDEV=0.41582813670134
    STATISTICS_VALID_PERCENT=51.25

## validation

In [22]:
reference = 3709240452

filename = get_vegetation_pixels_by_land_use_filename(year=2025, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/count/spatial_unit_vegetation_landuse_counts_bAmazônia_y2025.pkl

          suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0            1            1  5105507     cs_150km  2025  Amazônia       80645
1            1            1  5106752     cs_150km  2025  Amazônia       73245
2            1            1  5106828     cs_150km  2025  Amazônia      159911
3            1            2  5106752     cs_150km  2025  Amazônia        1394
4            1            2  5106828     cs_150km  2025  Amazônia         618
...        ...          ...      ...          ...   ...       ...         ...
365368  173075            2  1200427       cs_5km  2025  Amazônia        4018
365369  173075            8  1200427       cs_5km  2025  Amazônia       22778
365370  173075            9  1200427       cs_5km  2025  Amazônia          36
365371  173076            8  1200427       cs_5km  2025  Amazônia       10005
365372  173076            9  1200427       cs_5km  2025  Amazônia       16421

[365373 rows x 7 columns]

In [23]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["num_pixels"].sum()
    delta = total - reference
    percent = delta / reference * 100
    assert delta / reference * 100 < 0.0025
    print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}, percent={percent}")

cs_5km: num_pixels=3709147548, reference=3709240452, delta=-92904, percent=-0.0025046637229977024
cs_25km: num_pixels=3709147548, reference=3709240452, delta=-92904, percent=-0.0025046637229977024
cs_150km: num_pixels=3709147548, reference=3709240452, delta=-92904, percent=-0.0025046637229977024
states: num_pixels=3709147479, reference=3709240452, delta=-92973, percent=-0.0025065239421151442
municipalities: num_pixels=3709147548, reference=3709240452, delta=-92904, percent=-0.0025046637229977024

# native vegetation from future deforestation (counts)
___

In [24]:
filename = get_vegetation_from_deforestation(first_year=2000, last_year=2025, biome=biome)
print(filename)
assert filename.exists()

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/vegetation_from_deforestation_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,biome,num_pixels,year,source
0,1,1,5105507,cs_150km,Amazônia,9500,2000,deforestation
1,1,1,5106752,cs_150km,Amazônia,32389,2000,deforestation
2,1,1,5106828,cs_150km,Amazônia,58976,2000,deforestation
3,1,2,5106752,cs_150km,Amazônia,6,2000,deforestation
4,1,2,5106828,cs_150km,Amazônia,2349,2000,deforestation
...,...,...,...,...,...,...,...,...
34183,172961,7,1502764,cs_5km,Amazônia,161,2024,deforestation
34184,172961,7,1507300,cs_5km,Amazônia,127,2024,deforestation
34185,172980,5,1506583,cs_5km,Amazônia,80,2024,deforestation
34186,172982,5,1506583,cs_5km,Amazônia,9,2024,deforestation
34187,173030,5,1506583,cs_5km,Amazônia,81,2024,deforestation

In [25]:
vegetation_from_deforestation = {}
years_dict = {}
for year1 in years:
    total = 0
    years_dict[year1] = ""
    for year2 in years:
        if year2 <= year1:
            continue
        total = total + acc_dict["cs_5km"][year2]['relative']
        years_dict[year1] = years_dict[year1] + f",{year2}"
    vegetation_from_deforestation[year1] = total

In [26]:
years_dict

{2000: ',2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2001: ',2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2002: ',2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2003: ',2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2004: ',2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2005: ',2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2006: ',2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2007: ',2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2008: ',2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2009: ',2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2010: ',2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2011: ',2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2012: ',2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2013: ',2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2014: ',2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2015: ',2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2016: ',2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2017: ',2018,2019,2020,2021,2022,2023,2024,2025',
 2018: ',2019,2020,2021,2022,2023,2024,2025',
 2019: ',2020,2021,2022,2023,2024,2025',
 2020: ',2021,2022,2023,2024,2025',
 2021: ',2022,2023,2024,2025',
 2022: ',2023,2024,2025',
 2023: ',2024,2025',
 2024: ',2025',
 2025: ''}

In [27]:
vegetation_from_deforestation

{2000: 920316458,
 2001: 920316458,
 2002: 916768897,
 2003: 916768897,
 2004: 913605343,
 2005: 913605343,
 2006: 911458734,
 2007: 169908534,
 2008: 154484597,
 2009: 147822295,
 2010: 140021973,
 2011: 133738631,
 2012: 128980385,
 2013: 121829238,
 2014: 115494645,
 2015: 107072877,
 2016: 97554021,
 2017: 89782353,
 2018: 80527870,
 2019: 67060096,
 2020: 54425773,
 2021: 39698601,
 2022: 24501021,
 2023: 14850327,
 2024: 6953030,
 2025: 0}

In [28]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        total = dfr["num_pixels"].sum()
        reference = vegetation_from_deforestation[year]
        delta = total - reference
        assert delta == 0
        print(f"{spatial_unit}: {year}: num_pixels={total}, reference={reference}, delta={delta}")

cs_5km: 2000: num_pixels=920316458, reference=920316458, delta=0
cs_5km: 2001: num_pixels=920316458, reference=920316458, delta=0
cs_5km: 2002: num_pixels=916768897, reference=916768897, delta=0
cs_5km: 2003: num_pixels=916768897, reference=916768897, delta=0
cs_5km: 2004: num_pixels=913605343, reference=913605343, delta=0
cs_5km: 2005: num_pixels=913605343, reference=913605343, delta=0
cs_5km: 2006: num_pixels=911458734, reference=911458734, delta=0
cs_5km: 2007: num_pixels=169908534, reference=169908534, delta=0
cs_5km: 2008: num_pixels=154484597, reference=154484597, delta=0
cs_5km: 2009: num_pixels=147822295, reference=147822295, delta=0
cs_5km: 2010: num_pixels=140021973, reference=140021973, delta=0
cs_5km: 2011: num_pixels=133738631, reference=133738631, delta=0
cs_5km: 2012: num_pixels=128980385, reference=128980385, delta=0
cs_5km: 2013: num_pixels=121829238, reference=121829238, delta=0
cs_5km: 2014: num_pixels=115494645, reference=115494645, delta=0
cs_5km: 2015: num_pixels=107072877, reference=107072877, delta=0
cs_5km: 2016: num_pixels=97554021, reference=97554021, delta=0
cs_5km: 2017: num_pixels=89782353, reference=89782353, delta=0
cs_5km: 2018: num_pixels=80527870, reference=80527870, delta=0
cs_5km: 2019: num_pixels=67060096, reference=67060096, delta=0
cs_5km: 2020: num_pixels=54425773, reference=54425773, delta=0
cs_5km: 2021: num_pixels=39698601, reference=39698601, delta=0
cs_5km: 2022: num_pixels=24501021, reference=24501021, delta=0
cs_5km: 2023: num_pixels=14850327, reference=14850327, delta=0
cs_5km: 2024: num_pixels=6953030, reference=6953030, delta=0
cs_5km: 2025: num_pixels=0, reference=0, delta=0
cs_25km: 2000: num_pixels=920316458, reference=920316458, delta=0
cs_25km: 2001: num_pixels=920316458, reference=920316458, delta=0
cs_25km: 2002: num_pixels=916768897, reference=916768897, delta=0
cs_25km: 2003: num_pixels=916768897, reference=916768897, delta=0
cs_25km: 2004: num_pixels=913605343, reference=913605343, delta=0
cs_25km: 2005: num_pixels=913605343, reference=913605343, delta=0
cs_25km: 2006: num_pixels=911458734, reference=911458734, delta=0
cs_25km: 2007: num_pixels=169908534, reference=169908534, delta=0
cs_25km: 2008: num_pixels=154484597, reference=154484597, delta=0
cs_25km: 2009: num_pixels=147822295, reference=147822295, delta=0
cs_25km: 2010: num_pixels=140021973, reference=140021973, delta=0
cs_25km: 2011: num_pixels=133738631, reference=133738631, delta=0
cs_25km: 2012: num_pixels=128980385, reference=128980385, delta=0
cs_25km: 2013: num_pixels=121829238, reference=121829238, delta=0
cs_25km: 2014: num_pixels=115494645, reference=115494645, delta=0
cs_25km: 2015: num_pixels=107072877, reference=107072877, delta=0
cs_25km: 2016: num_pixels=97554021, reference=97554021, delta=0
cs_25km: 2017: num_pixels=89782353, reference=89782353, delta=0
cs_25km: 2018: num_pixels=80527870, reference=80527870, delta=0
cs_25km: 2019: num_pixels=67060096, reference=67060096, delta=0
cs_25km: 2020: num_pixels=54425773, reference=54425773, delta=0
cs_25km: 2021: num_pixels=39698601, reference=39698601, delta=0
cs_25km: 2022: num_pixels=24501021, reference=24501021, delta=0
cs_25km: 2023: num_pixels=14850327, reference=14850327, delta=0
cs_25km: 2024: num_pixels=6953030, reference=6953030, delta=0
cs_25km: 2025: num_pixels=0, reference=0, delta=0
cs_150km: 2000: num_pixels=920316458, reference=920316458, delta=0
cs_150km: 2001: num_pixels=920316458, reference=920316458, delta=0
cs_150km: 2002: num_pixels=916768897, reference=916768897, delta=0
cs_150km: 2003: num_pixels=916768897, reference=916768897, delta=0
cs_150km: 2004: num_pixels=913605343, reference=913605343, delta=0
cs_150km: 2005: num_pixels=913605343, reference=913605343, delta=0
cs_150km: 2006: num_pixels=911458734, reference=911458734, delta=0
cs_150km: 2007: num_pixels=169908534, reference=169908534, delta=0
cs_150km: 2008: num_pixels=154484597, reference=154484597, delta=0
cs_150km: 2009: num_pixels=147822295, reference=147822295, delta=0
cs_150km: 2010: num_pixels=140021973, reference=140021973, delta=0
cs_150km: 2011: num_pixels=133738631, reference=133738631, delta=0
cs_150km: 2012: num_pixels=128980385, reference=128980385, delta=0
cs_150km: 2013: num_pixels=121829238, reference=121829238, delta=0
cs_150km: 2014: num_pixels=115494645, reference=115494645, delta=0
cs_150km: 2015: num_pixels=107072877, reference=107072877, delta=0
cs_150km: 2016: num_pixels=97554021, reference=97554021, delta=0
cs_150km: 2017: num_pixels=89782353, reference=89782353, delta=0
cs_150km: 2018: num_pixels=80527870, reference=80527870, delta=0
cs_150km: 2019: num_pixels=67060096, reference=67060096, delta=0
cs_150km: 2020: num_pixels=54425773, reference=54425773, delta=0
cs_150km: 2021: num_pixels=39698601, reference=39698601, delta=0
cs_150km: 2022: num_pixels=24501021, reference=24501021, delta=0
cs_150km: 2023: num_pixels=14850327, reference=14850327, delta=0
cs_150km: 2024: num_pixels=6953030, reference=6953030, delta=0
cs_150km: 2025: num_pixels=0, reference=0, delta=0
states: 2000: num_pixels=920316458, reference=920316458, delta=0
states: 2001: num_pixels=920316458, reference=920316458, delta=0
states: 2002: num_pixels=916768897, reference=916768897, delta=0
states: 2003: num_pixels=916768897, reference=916768897, delta=0
states: 2004: num_pixels=913605343, reference=913605343, delta=0
states: 2005: num_pixels=913605343, reference=913605343, delta=0
states: 2006: num_pixels=911458734, reference=911458734, delta=0
states: 2007: num_pixels=169908534, reference=169908534, delta=0
states: 2008: num_pixels=154484597, reference=154484597, delta=0
states: 2009: num_pixels=147822295, reference=147822295, delta=0
states: 2010: num_pixels=140021973, reference=140021973, delta=0
states: 2011: num_pixels=133738631, reference=133738631, delta=0
states: 2012: num_pixels=128980385, reference=128980385, delta=0
states: 2013: num_pixels=121829238, reference=121829238, delta=0
states: 2014: num_pixels=115494645, reference=115494645, delta=0
states: 2015: num_pixels=107072877, reference=107072877, delta=0
states: 2016: num_pixels=97554021, reference=97554021, delta=0
states: 2017: num_pixels=89782353, reference=89782353, delta=0
states: 2018: num_pixels=80527870, reference=80527870, delta=0
states: 2019: num_pixels=67060096, reference=67060096, delta=0
states: 2020: num_pixels=54425773, reference=54425773, delta=0
states: 2021: num_pixels=39698601, reference=39698601, delta=0
states: 2022: num_pixels=24501021, reference=24501021, delta=0
states: 2023: num_pixels=14850327, reference=14850327, delta=0
states: 2024: num_pixels=6953030, reference=6953030, delta=0
states: 2025: num_pixels=0, reference=0, delta=0
municipalities: 2000: num_pixels=920316458, reference=920316458, delta=0
municipalities: 2001: num_pixels=920316458, reference=920316458, delta=0
municipalities: 2002: num_pixels=916768897, reference=916768897, delta=0
municipalities: 2003: num_pixels=916768897, reference=916768897, delta=0
municipalities: 2004: num_pixels=913605343, reference=913605343, delta=0
municipalities: 2005: num_pixels=913605343, reference=913605343, delta=0
municipalities: 2006: num_pixels=911458734, reference=911458734, delta=0
municipalities: 2007: num_pixels=169908534, reference=169908534, delta=0
municipalities: 2008: num_pixels=154484597, reference=154484597, delta=0
municipalities: 2009: num_pixels=147822295, reference=147822295, delta=0
municipalities: 2010: num_pixels=140021973, reference=140021973, delta=0
municipalities: 2011: num_pixels=133738631, reference=133738631, delta=0
municipalities: 2012: num_pixels=128980385, reference=128980385, delta=0
municipalities: 2013: num_pixels=121829238, reference=121829238, delta=0
municipalities: 2014: num_pixels=115494645, reference=115494645, delta=0
municipalities: 2015: num_pixels=107072877, reference=107072877, delta=0
municipalities: 2016: num_pixels=97554021, reference=97554021, delta=0
municipalities: 2017: num_pixels=89782353, reference=89782353, delta=0
municipalities: 2018: num_pixels=80527870, reference=80527870, delta=0
municipalities: 2019: num_pixels=67060096, reference=67060096, delta=0
municipalities: 2020: num_pixels=54425773, reference=54425773, delta=0
municipalities: 2021: num_pixels=39698601, reference=39698601, delta=0
municipalities: 2022: num_pixels=24501021, reference=24501021, delta=0
municipalities: 2023: num_pixels=14850327, reference=14850327, delta=0
municipalities: 2024: num_pixels=6953030, reference=6953030, delta=0
municipalities: 2025: num_pixels=0, reference=0, delta=0

# total native vegetation
___

In [29]:
filename = get_vegetation_pixels_by_land_use_filename(year=2025, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/count/spatial_unit_vegetation_landuse_counts_bAmazônia_y2025.pkl

          suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0            1            1  5105507     cs_150km  2025  Amazônia       80645
1            1            1  5106752     cs_150km  2025  Amazônia       73245
2            1            1  5106828     cs_150km  2025  Amazônia      159911
3            1            2  5106752     cs_150km  2025  Amazônia        1394
4            1            2  5106828     cs_150km  2025  Amazônia         618
...        ...          ...      ...          ...   ...       ...         ...
365368  173075            2  1200427       cs_5km  2025  Amazônia        4018
365369  173075            8  1200427       cs_5km  2025  Amazônia       22778
365370  173075            9  1200427       cs_5km  2025  Amazônia          36
365371  173076            8  1200427       cs_5km  2025  Amazônia       10005
365372  173076            9  1200427       cs_5km  2025  Amazônia       16421

[365373 rows x 7 columns]

In [30]:
total_vegetation = {}
for year in years:
    dfr = load_dfr(filename, filters={"spatial_unit": "cs_5km"})
    total_vegetation[year] = dfr["num_pixels"].sum() + vegetation_from_deforestation[year]

In [31]:
total_vegetation

{2000: 4629464006,
 2001: 4629464006,
 2002: 4625916445,
 2003: 4625916445,
 2004: 4622752891,
 2005: 4622752891,
 2006: 4620606282,
 2007: 3879056082,
 2008: 3863632145,
 2009: 3856969843,
 2010: 3849169521,
 2011: 3842886179,
 2012: 3838127933,
 2013: 3830976786,
 2014: 3824642193,
 2015: 3816220425,
 2016: 3806701569,
 2017: 3798929901,
 2018: 3789675418,
 2019: 3776207644,
 2020: 3763573321,
 2021: 3748846149,
 2022: 3733648569,
 2023: 3723997875,
 2024: 3716100578,
 2025: 3709147548}

In [32]:
filename = get_total_vegetation_filename(2000, 2025, biome)
print(filename)
assert filename.exists()

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/vegetation_bAmazônia_from_y2000_to_y2025.pkl

          suid  land_use_id  geocode spatial_unit     biome  num_pixels  year
0            1            1  5105507     cs_150km  Amazônia       90145  2000
1            1            1  5106752     cs_150km  Amazônia      105634  2000
2            1            1  5106828     cs_150km  Amazônia      218887  2000
3            1            2  5106752     cs_150km  Amazônia        1400  2000
4            1            2  5106828     cs_150km  Amazônia        2967  2000
...        ...          ...      ...          ...       ...         ...   ...
365368  173075            2  1200427       cs_5km  Amazônia        4018  2025
365369  173075            8  1200427       cs_5km  Amazônia       22778  2025
365370  173075            9  1200427       cs_5km  Amazônia          36  2025
365371  173076            8  1200427       cs_5km  Amazônia       10005  2025
365372  173076            9  1200427       cs_5km  Amazônia       16421  2025

[9669058 rows x 7 columns]

In [33]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        total = dfr["num_pixels"].sum()
        reference = total_vegetation[year]
        delta = total - reference
        percent = delta / reference * 100
        assert delta / reference * 100 < 0.0025
        print(f"{spatial_unit}: year: {year}, total={total}, reference={reference}, delta={delta}, percent={percent}")

cs_5km: year: 2000, total=4629464006, reference=4629464006, delta=0, percent=0.0
cs_5km: year: 2001, total=4629464006, reference=4629464006, delta=0, percent=0.0
cs_5km: year: 2002, total=4625916445, reference=4625916445, delta=0, percent=0.0
cs_5km: year: 2003, total=4625916445, reference=4625916445, delta=0, percent=0.0
cs_5km: year: 2004, total=4622752891, reference=4622752891, delta=0, percent=0.0
cs_5km: year: 2005, total=4622752891, reference=4622752891, delta=0, percent=0.0
cs_5km: year: 2006, total=4620606282, reference=4620606282, delta=0, percent=0.0
cs_5km: year: 2007, total=3879056082, reference=3879056082, delta=0, percent=0.0
cs_5km: year: 2008, total=3863632145, reference=3863632145, delta=0, percent=0.0
cs_5km: year: 2009, total=3856969843, reference=3856969843, delta=0, percent=0.0
cs_5km: year: 2010, total=3849169521, reference=3849169521, delta=0, percent=0.0
cs_5km: year: 2011, total=3842886179, reference=3842886179, delta=0, percent=0.0
cs_5km: year: 2012, total=3838127933, reference=3838127933, delta=0, percent=0.0
cs_5km: year: 2013, total=3830976786, reference=3830976786, delta=0, percent=0.0
cs_5km: year: 2014, total=3824642193, reference=3824642193, delta=0, percent=0.0
cs_5km: year: 2015, total=3816220425, reference=3816220425, delta=0, percent=0.0
cs_5km: year: 2016, total=3806701569, reference=3806701569, delta=0, percent=0.0
cs_5km: year: 2017, total=3798929901, reference=3798929901, delta=0, percent=0.0
cs_5km: year: 2018, total=3789675418, reference=3789675418, delta=0, percent=0.0
cs_5km: year: 2019, total=3776207644, reference=3776207644, delta=0, percent=0.0
cs_5km: year: 2020, total=3763573321, reference=3763573321, delta=0, percent=0.0
cs_5km: year: 2021, total=3748846149, reference=3748846149, delta=0, percent=0.0
cs_5km: year: 2022, total=3733648569, reference=3733648569, delta=0, percent=0.0
cs_5km: year: 2023, total=3723997875, reference=3723997875, delta=0, percent=0.0
cs_5km: year: 2024, total=3716100578, reference=3716100578, delta=0, percent=0.0
cs_5km: year: 2025, total=3709147548, reference=3709147548, delta=0, percent=0.0
cs_25km: year: 2000, total=4629464006, reference=4629464006, delta=0, percent=0.0
cs_25km: year: 2001, total=4629464006, reference=4629464006, delta=0, percent=0.0
cs_25km: year: 2002, total=4625916445, reference=4625916445, delta=0, percent=0.0
cs_25km: year: 2003, total=4625916445, reference=4625916445, delta=0, percent=0.0
cs_25km: year: 2004, total=4622752891, reference=4622752891, delta=0, percent=0.0
cs_25km: year: 2005, total=4622752891, reference=4622752891, delta=0, percent=0.0
cs_25km: year: 2006, total=4620606282, reference=4620606282, delta=0, percent=0.0
cs_25km: year: 2007, total=3879056082, reference=3879056082, delta=0, percent=0.0
cs_25km: year: 2008, total=3863632145, reference=3863632145, delta=0, percent=0.0
cs_25km: year: 2009, total=3856969843, reference=3856969843, delta=0, percent=0.0
cs_25km: year: 2010, total=3849169521, reference=3849169521, delta=0, percent=0.0
cs_25km: year: 2011, total=3842886179, reference=3842886179, delta=0, percent=0.0
cs_25km: year: 2012, total=3838127933, reference=3838127933, delta=0, percent=0.0
cs_25km: year: 2013, total=3830976786, reference=3830976786, delta=0, percent=0.0
cs_25km: year: 2014, total=3824642193, reference=3824642193, delta=0, percent=0.0
cs_25km: year: 2015, total=3816220425, reference=3816220425, delta=0, percent=0.0
cs_25km: year: 2016, total=3806701569, reference=3806701569, delta=0, percent=0.0
cs_25km: year: 2017, total=3798929901, reference=3798929901, delta=0, percent=0.0
cs_25km: year: 2018, total=3789675418, reference=3789675418, delta=0, percent=0.0
cs_25km: year: 2019, total=3776207644, reference=3776207644, delta=0, percent=0.0
cs_25km: year: 2020, total=3763573321, reference=3763573321, delta=0, percent=0.0
cs_25km: year: 2021, total=3748846149, reference=3748846149, delta=0, percent=0.0
cs_25km: year: 2022, total=3733648569, reference=3733648569, delta=0, percent=0.0
cs_25km: year: 2023, total=3723997875, reference=3723997875, delta=0, percent=0.0
cs_25km: year: 2024, total=3716100578, reference=3716100578, delta=0, percent=0.0
cs_25km: year: 2025, total=3709147548, reference=3709147548, delta=0, percent=0.0
cs_150km: year: 2000, total=4629464006, reference=4629464006, delta=0, percent=0.0
cs_150km: year: 2001, total=4629464006, reference=4629464006, delta=0, percent=0.0
cs_150km: year: 2002, total=4625916445, reference=4625916445, delta=0, percent=0.0
cs_150km: year: 2003, total=4625916445, reference=4625916445, delta=0, percent=0.0
cs_150km: year: 2004, total=4622752891, reference=4622752891, delta=0, percent=0.0
cs_150km: year: 2005, total=4622752891, reference=4622752891, delta=0, percent=0.0
cs_150km: year: 2006, total=4620606282, reference=4620606282, delta=0, percent=0.0
cs_150km: year: 2007, total=3879056082, reference=3879056082, delta=0, percent=0.0
cs_150km: year: 2008, total=3863632145, reference=3863632145, delta=0, percent=0.0
cs_150km: year: 2009, total=3856969843, reference=3856969843, delta=0, percent=0.0
cs_150km: year: 2010, total=3849169521, reference=3849169521, delta=0, percent=0.0
cs_150km: year: 2011, total=3842886179, reference=3842886179, delta=0, percent=0.0
cs_150km: year: 2012, total=3838127933, reference=3838127933, delta=0, percent=0.0
cs_150km: year: 2013, total=3830976786, reference=3830976786, delta=0, percent=0.0
cs_150km: year: 2014, total=3824642193, reference=3824642193, delta=0, percent=0.0
cs_150km: year: 2015, total=3816220425, reference=3816220425, delta=0, percent=0.0
cs_150km: year: 2016, total=3806701569, reference=3806701569, delta=0, percent=0.0
cs_150km: year: 2017, total=3798929901, reference=3798929901, delta=0, percent=0.0
cs_150km: year: 2018, total=3789675418, reference=3789675418, delta=0, percent=0.0
cs_150km: year: 2019, total=3776207644, reference=3776207644, delta=0, percent=0.0
cs_150km: year: 2020, total=3763573321, reference=3763573321, delta=0, percent=0.0
cs_150km: year: 2021, total=3748846149, reference=3748846149, delta=0, percent=0.0
cs_150km: year: 2022, total=3733648569, reference=3733648569, delta=0, percent=0.0
cs_150km: year: 2023, total=3723997875, reference=3723997875, delta=0, percent=0.0
cs_150km: year: 2024, total=3716100578, reference=3716100578, delta=0, percent=0.0
cs_150km: year: 2025, total=3709147548, reference=3709147548, delta=0, percent=0.0
states: year: 2000, total=4629463937, reference=4629464006, delta=-69, percent=-1.490453320526368e-06
states: year: 2001, total=4629463937, reference=4629464006, delta=-69, percent=-1.490453320526368e-06
states: year: 2002, total=4625916376, reference=4625916445, delta=-69, percent=-1.4915963316756362e-06
states: year: 2003, total=4625916376, reference=4625916445, delta=-69, percent=-1.4915963316756362e-06
states: year: 2004, total=4622752822, reference=4622752891, delta=-69, percent=-1.4926170969323396e-06
states: year: 2005, total=4622752822, reference=4622752891, delta=-69, percent=-1.4926170969323396e-06
states: year: 2006, total=4620606213, reference=4620606282, delta=-69, percent=-1.4933105265600296e-06
states: year: 2007, total=3879056013, reference=3879056082, delta=-69, percent=-1.7787832540029772e-06
states: year: 2008, total=3863632076, reference=3863632145, delta=-69, percent=-1.7858843029167312e-06
states: year: 2009, total=3856969774, reference=3856969843, delta=-69, percent=-1.7889691340270093e-06
states: year: 2010, total=3849169452, reference=3849169521, delta=-69, percent=-1.7925944706658194e-06
states: year: 2011, total=3842886110, reference=3842886179, delta=-69, percent=-1.7955254666937664e-06
states: year: 2012, total=3838127864, reference=3838127933, delta=-69, percent=-1.797751435191673e-06
states: year: 2013, total=3830976717, reference=3830976786, delta=-69, percent=-1.8011072333341986e-06
states: year: 2014, total=3824642124, reference=3824642193, delta=-69, percent=-1.804090331019365e-06
states: year: 2015, total=3816220356, reference=3816220425, delta=-69, percent=-1.8080716603260675e-06
states: year: 2016, total=3806701500, reference=3806701569, delta=-69, percent=-1.8125928379020771e-06
states: year: 2017, total=3798929832, reference=3798929901, delta=-69, percent=-1.8163009531141123e-06
states: year: 2018, total=3789675349, reference=3789675418, delta=-69, percent=-1.8207364058744305e-06
states: year: 2019, total=3776207575, reference=3776207644, delta=-69, percent=-1.8272300282436481e-06
states: year: 2020, total=3763573252, reference=3763573321, delta=-69, percent=-1.833364043022453e-06
states: year: 2021, total=3748846080, reference=3748846149, delta=-69, percent=-1.8405663304802643e-06
states: year: 2022, total=3733648500, reference=3733648569, delta=-69, percent=-1.8480582391416817e-06
states: year: 2023, total=3723997806, reference=3723997875, delta=-69, percent=-1.8528474589959319e-06
states: year: 2024, total=3716100509, reference=3716100578, delta=-69, percent=-1.8567850506655474e-06
states: year: 2025, total=3709147479, reference=3709147548, delta=-69, percent=-1.8602657108425171e-06
municipalities: year: 2000, total=4629464006, reference=4629464006, delta=0, percent=0.0
municipalities: year: 2001, total=4629464006, reference=4629464006, delta=0, percent=0.0
municipalities: year: 2002, total=4625916445, reference=4625916445, delta=0, percent=0.0
municipalities: year: 2003, total=4625916445, reference=4625916445, delta=0, percent=0.0
municipalities: year: 2004, total=4622752891, reference=4622752891, delta=0, percent=0.0
municipalities: year: 2005, total=4622752891, reference=4622752891, delta=0, percent=0.0
municipalities: year: 2006, total=4620606282, reference=4620606282, delta=0, percent=0.0
municipalities: year: 2007, total=3879056082, reference=3879056082, delta=0, percent=0.0
municipalities: year: 2008, total=3863632145, reference=3863632145, delta=0, percent=0.0
municipalities: year: 2009, total=3856969843, reference=3856969843, delta=0, percent=0.0
municipalities: year: 2010, total=3849169521, reference=3849169521, delta=0, percent=0.0
municipalities: year: 2011, total=3842886179, reference=3842886179, delta=0, percent=0.0
municipalities: year: 2012, total=3838127933, reference=3838127933, delta=0, percent=0.0
municipalities: year: 2013, total=3830976786, reference=3830976786, delta=0, percent=0.0
municipalities: year: 2014, total=3824642193, reference=3824642193, delta=0, percent=0.0
municipalities: year: 2015, total=3816220425, reference=3816220425, delta=0, percent=0.0
municipalities: year: 2016, total=3806701569, reference=3806701569, delta=0, percent=0.0
municipalities: year: 2017, total=3798929901, reference=3798929901, delta=0, percent=0.0
municipalities: year: 2018, total=3789675418, reference=3789675418, delta=0, percent=0.0
municipalities: year: 2019, total=3776207644, reference=3776207644, delta=0, percent=0.0
municipalities: year: 2020, total=3763573321, reference=3763573321, delta=0, percent=0.0
municipalities: year: 2021, total=3748846149, reference=3748846149, delta=0, percent=0.0
municipalities: year: 2022, total=3733648569, reference=3733648569, delta=0, percent=0.0
municipalities: year: 2023, total=3723997875, reference=3723997875, delta=0, percent=0.0
municipalities: year: 2024, total=3716100578, reference=3716100578, delta=0, percent=0.0
municipalities: year: 2025, total=3709147548, reference=3709147548, delta=0, percent=0.0

# ratio accumulated deforestation to native vegetation indicator
___

In [34]:
filename = get_ratio_deforestation_to_vegetation_filename(2000, 2025, biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ratio_accumulated_deforestation_to_vegetation_indicator_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,biome,deforestation_counts,year,vegetation_counts
0,1,1,5105507,cs_150km,Amazônia,8775.0,2000,90145.0
1,1,1,5105507,cs_150km,Amazônia,8775.0,2001,90145.0
2,1,1,5105507,cs_150km,Amazônia,10503.0,2002,88417.0
3,1,1,5105507,cs_150km,Amazônia,10503.0,2003,88417.0
4,1,1,5105507,cs_150km,Amazônia,11224.0,2004,87696.0
...,...,...,...,...,...,...,...,...
10055625,173076,9,1200427,cs_5km,Amazônia,409.0,2021,16421.0
10055626,173076,9,1200427,cs_5km,Amazônia,409.0,2022,16421.0
10055627,173076,9,1200427,cs_5km,Amazônia,409.0,2023,16421.0
10055628,173076,9,1200427,cs_5km,Amazônia,409.0,2024,16421.0
10055629,173076,9,1200427,cs_5km,Amazônia,409.0,2025,16421.0

In [35]:
assert dfr.isna().sum().sum() == 0

In [36]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        
        total1 = dfr["deforestation_counts"].sum()
        reference1 = acc_dict["cs_5km"][year]['absolute']
        delta1 = total1 - reference1
        assert delta1 == 0
        print(f"deforestation: {spatial_unit}: year: {year}, total={total1}, reference={reference1}, delta={delta1}")

        total2 = dfr["vegetation_counts"].sum()
        reference2 = total_vegetation[year]
        delta2 = total2 - reference2
        percent2 = delta2 / reference2 * 100
        assert percent2 < 0.0025
        
        print(f"vegetation: {spatial_unit}: year: {year}, total={total2}, reference={reference2}, delta={delta2}, percent={percent2}")
    print("_")

deforestation: cs_5km: year: 2000, total=14828887.0, reference=14828887, delta=0.0
vegetation: cs_5km: year: 2000, total=4629464006.0, reference=4629464006, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2001, total=14828887.0, reference=14828887, delta=0.0
vegetation: cs_5km: year: 2001, total=4629464006.0, reference=4629464006, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2002, total=18376448.0, reference=18376448, delta=0.0
vegetation: cs_5km: year: 2002, total=4625916445.0, reference=4625916445, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2003, total=18376448.0, reference=18376448, delta=0.0
vegetation: cs_5km: year: 2003, total=4625916445.0, reference=4625916445, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2004, total=21540002.0, reference=21540002, delta=0.0
vegetation: cs_5km: year: 2004, total=4622752891.0, reference=4622752891, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2005, total=21540002.0, reference=21540002, delta=0.0
vegetation: cs_5km: year: 2005, total=4622752891.0, reference=4622752891, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2006, total=23686611.0, reference=23686611, delta=0.0
vegetation: cs_5km: year: 2006, total=4620606282.0, reference=4620606282, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2007, total=765236811.0, reference=765236811, delta=0.0
vegetation: cs_5km: year: 2007, total=3879056082.0, reference=3879056082, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2008, total=780660748.0, reference=780660748, delta=0.0
vegetation: cs_5km: year: 2008, total=3863632145.0, reference=3863632145, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2009, total=787323050.0, reference=787323050, delta=0.0
vegetation: cs_5km: year: 2009, total=3856969843.0, reference=3856969843, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2010, total=795123372.0, reference=795123372, delta=0.0
vegetation: cs_5km: year: 2010, total=3849169521.0, reference=3849169521, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2011, total=801406714.0, reference=801406714, delta=0.0
vegetation: cs_5km: year: 2011, total=3842886179.0, reference=3842886179, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2012, total=806164960.0, reference=806164960, delta=0.0
vegetation: cs_5km: year: 2012, total=3838127933.0, reference=3838127933, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2013, total=813316107.0, reference=813316107, delta=0.0
vegetation: cs_5km: year: 2013, total=3830976786.0, reference=3830976786, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2014, total=819650700.0, reference=819650700, delta=0.0
vegetation: cs_5km: year: 2014, total=3824642193.0, reference=3824642193, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2015, total=828072468.0, reference=828072468, delta=0.0
vegetation: cs_5km: year: 2015, total=3816220425.0, reference=3816220425, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2016, total=837591324.0, reference=837591324, delta=0.0
vegetation: cs_5km: year: 2016, total=3806701569.0, reference=3806701569, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2017, total=845362992.0, reference=845362992, delta=0.0
vegetation: cs_5km: year: 2017, total=3798929901.0, reference=3798929901, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2018, total=854617475.0, reference=854617475, delta=0.0
vegetation: cs_5km: year: 2018, total=3789675418.0, reference=3789675418, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2019, total=868085249.0, reference=868085249, delta=0.0
vegetation: cs_5km: year: 2019, total=3776207644.0, reference=3776207644, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2020, total=880719572.0, reference=880719572, delta=0.0
vegetation: cs_5km: year: 2020, total=3763573321.0, reference=3763573321, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2021, total=895446744.0, reference=895446744, delta=0.0
vegetation: cs_5km: year: 2021, total=3748846149.0, reference=3748846149, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2022, total=910644324.0, reference=910644324, delta=0.0
vegetation: cs_5km: year: 2022, total=3733648569.0, reference=3733648569, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2023, total=920295018.0, reference=920295018, delta=0.0
vegetation: cs_5km: year: 2023, total=3723997875.0, reference=3723997875, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2024, total=928192315.0, reference=928192315, delta=0.0
vegetation: cs_5km: year: 2024, total=3716100578.0, reference=3716100578, delta=0.0, percent=0.0
deforestation: cs_5km: year: 2025, total=935145345.0, reference=935145345, delta=0.0
vegetation: cs_5km: year: 2025, total=3709147548.0, reference=3709147548, delta=0.0, percent=0.0
_
deforestation: cs_25km: year: 2000, total=14828887.0, reference=14828887, delta=0.0
vegetation: cs_25km: year: 2000, total=4629464006.0, reference=4629464006, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2001, total=14828887.0, reference=14828887, delta=0.0
vegetation: cs_25km: year: 2001, total=4629464006.0, reference=4629464006, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2002, total=18376448.0, reference=18376448, delta=0.0
vegetation: cs_25km: year: 2002, total=4625916445.0, reference=4625916445, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2003, total=18376448.0, reference=18376448, delta=0.0
vegetation: cs_25km: year: 2003, total=4625916445.0, reference=4625916445, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2004, total=21540002.0, reference=21540002, delta=0.0
vegetation: cs_25km: year: 2004, total=4622752891.0, reference=4622752891, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2005, total=21540002.0, reference=21540002, delta=0.0
vegetation: cs_25km: year: 2005, total=4622752891.0, reference=4622752891, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2006, total=23686611.0, reference=23686611, delta=0.0
vegetation: cs_25km: year: 2006, total=4620606282.0, reference=4620606282, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2007, total=765236811.0, reference=765236811, delta=0.0
vegetation: cs_25km: year: 2007, total=3879056082.0, reference=3879056082, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2008, total=780660748.0, reference=780660748, delta=0.0
vegetation: cs_25km: year: 2008, total=3863632145.0, reference=3863632145, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2009, total=787323050.0, reference=787323050, delta=0.0
vegetation: cs_25km: year: 2009, total=3856969843.0, reference=3856969843, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2010, total=795123372.0, reference=795123372, delta=0.0
vegetation: cs_25km: year: 2010, total=3849169521.0, reference=3849169521, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2011, total=801406714.0, reference=801406714, delta=0.0
vegetation: cs_25km: year: 2011, total=3842886179.0, reference=3842886179, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2012, total=806164960.0, reference=806164960, delta=0.0
vegetation: cs_25km: year: 2012, total=3838127933.0, reference=3838127933, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2013, total=813316107.0, reference=813316107, delta=0.0
vegetation: cs_25km: year: 2013, total=3830976786.0, reference=3830976786, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2014, total=819650700.0, reference=819650700, delta=0.0
vegetation: cs_25km: year: 2014, total=3824642193.0, reference=3824642193, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2015, total=828072468.0, reference=828072468, delta=0.0
vegetation: cs_25km: year: 2015, total=3816220425.0, reference=3816220425, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2016, total=837591324.0, reference=837591324, delta=0.0
vegetation: cs_25km: year: 2016, total=3806701569.0, reference=3806701569, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2017, total=845362992.0, reference=845362992, delta=0.0
vegetation: cs_25km: year: 2017, total=3798929901.0, reference=3798929901, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2018, total=854617475.0, reference=854617475, delta=0.0
vegetation: cs_25km: year: 2018, total=3789675418.0, reference=3789675418, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2019, total=868085249.0, reference=868085249, delta=0.0
vegetation: cs_25km: year: 2019, total=3776207644.0, reference=3776207644, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2020, total=880719572.0, reference=880719572, delta=0.0
vegetation: cs_25km: year: 2020, total=3763573321.0, reference=3763573321, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2021, total=895446744.0, reference=895446744, delta=0.0
vegetation: cs_25km: year: 2021, total=3748846149.0, reference=3748846149, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2022, total=910644324.0, reference=910644324, delta=0.0
vegetation: cs_25km: year: 2022, total=3733648569.0, reference=3733648569, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2023, total=920295018.0, reference=920295018, delta=0.0
vegetation: cs_25km: year: 2023, total=3723997875.0, reference=3723997875, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2024, total=928192315.0, reference=928192315, delta=0.0
vegetation: cs_25km: year: 2024, total=3716100578.0, reference=3716100578, delta=0.0, percent=0.0
deforestation: cs_25km: year: 2025, total=935145345.0, reference=935145345, delta=0.0
vegetation: cs_25km: year: 2025, total=3709147548.0, reference=3709147548, delta=0.0, percent=0.0
_
deforestation: cs_150km: year: 2000, total=14828887.0, reference=14828887, delta=0.0
vegetation: cs_150km: year: 2000, total=4629464006.0, reference=4629464006, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2001, total=14828887.0, reference=14828887, delta=0.0
vegetation: cs_150km: year: 2001, total=4629464006.0, reference=4629464006, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2002, total=18376448.0, reference=18376448, delta=0.0
vegetation: cs_150km: year: 2002, total=4625916445.0, reference=4625916445, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2003, total=18376448.0, reference=18376448, delta=0.0
vegetation: cs_150km: year: 2003, total=4625916445.0, reference=4625916445, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2004, total=21540002.0, reference=21540002, delta=0.0
vegetation: cs_150km: year: 2004, total=4622752891.0, reference=4622752891, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2005, total=21540002.0, reference=21540002, delta=0.0
vegetation: cs_150km: year: 2005, total=4622752891.0, reference=4622752891, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2006, total=23686611.0, reference=23686611, delta=0.0
vegetation: cs_150km: year: 2006, total=4620606282.0, reference=4620606282, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2007, total=765236811.0, reference=765236811, delta=0.0
vegetation: cs_150km: year: 2007, total=3879056082.0, reference=3879056082, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2008, total=780660748.0, reference=780660748, delta=0.0
vegetation: cs_150km: year: 2008, total=3863632145.0, reference=3863632145, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2009, total=787323050.0, reference=787323050, delta=0.0
vegetation: cs_150km: year: 2009, total=3856969843.0, reference=3856969843, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2010, total=795123372.0, reference=795123372, delta=0.0
vegetation: cs_150km: year: 2010, total=3849169521.0, reference=3849169521, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2011, total=801406714.0, reference=801406714, delta=0.0
vegetation: cs_150km: year: 2011, total=3842886179.0, reference=3842886179, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2012, total=806164960.0, reference=806164960, delta=0.0
vegetation: cs_150km: year: 2012, total=3838127933.0, reference=3838127933, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2013, total=813316107.0, reference=813316107, delta=0.0
vegetation: cs_150km: year: 2013, total=3830976786.0, reference=3830976786, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2014, total=819650700.0, reference=819650700, delta=0.0
vegetation: cs_150km: year: 2014, total=3824642193.0, reference=3824642193, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2015, total=828072468.0, reference=828072468, delta=0.0
vegetation: cs_150km: year: 2015, total=3816220425.0, reference=3816220425, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2016, total=837591324.0, reference=837591324, delta=0.0
vegetation: cs_150km: year: 2016, total=3806701569.0, reference=3806701569, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2017, total=845362992.0, reference=845362992, delta=0.0
vegetation: cs_150km: year: 2017, total=3798929901.0, reference=3798929901, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2018, total=854617475.0, reference=854617475, delta=0.0
vegetation: cs_150km: year: 2018, total=3789675418.0, reference=3789675418, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2019, total=868085249.0, reference=868085249, delta=0.0
vegetation: cs_150km: year: 2019, total=3776207644.0, reference=3776207644, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2020, total=880719572.0, reference=880719572, delta=0.0
vegetation: cs_150km: year: 2020, total=3763573321.0, reference=3763573321, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2021, total=895446744.0, reference=895446744, delta=0.0
vegetation: cs_150km: year: 2021, total=3748846149.0, reference=3748846149, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2022, total=910644324.0, reference=910644324, delta=0.0
vegetation: cs_150km: year: 2022, total=3733648569.0, reference=3733648569, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2023, total=920295018.0, reference=920295018, delta=0.0
vegetation: cs_150km: year: 2023, total=3723997875.0, reference=3723997875, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2024, total=928192315.0, reference=928192315, delta=0.0
vegetation: cs_150km: year: 2024, total=3716100578.0, reference=3716100578, delta=0.0, percent=0.0
deforestation: cs_150km: year: 2025, total=935145345.0, reference=935145345, delta=0.0
vegetation: cs_150km: year: 2025, total=3709147548.0, reference=3709147548, delta=0.0, percent=0.0
_
deforestation: states: year: 2000, total=14828887.0, reference=14828887, delta=0.0
vegetation: states: year: 2000, total=4629463937.0, reference=4629464006, delta=-69.0, percent=-1.490453320526368e-06
deforestation: states: year: 2001, total=14828887.0, reference=14828887, delta=0.0
vegetation: states: year: 2001, total=4629463937.0, reference=4629464006, delta=-69.0, percent=-1.490453320526368e-06
deforestation: states: year: 2002, total=18376448.0, reference=18376448, delta=0.0
vegetation: states: year: 2002, total=4625916376.0, reference=4625916445, delta=-69.0, percent=-1.4915963316756362e-06
deforestation: states: year: 2003, total=18376448.0, reference=18376448, delta=0.0
vegetation: states: year: 2003, total=4625916376.0, reference=4625916445, delta=-69.0, percent=-1.4915963316756362e-06
deforestation: states: year: 2004, total=21540002.0, reference=21540002, delta=0.0
vegetation: states: year: 2004, total=4622752822.0, reference=4622752891, delta=-69.0, percent=-1.4926170969323396e-06
deforestation: states: year: 2005, total=21540002.0, reference=21540002, delta=0.0
vegetation: states: year: 2005, total=4622752822.0, reference=4622752891, delta=-69.0, percent=-1.4926170969323396e-06
deforestation: states: year: 2006, total=23686611.0, reference=23686611, delta=0.0
vegetation: states: year: 2006, total=4620606213.0, reference=4620606282, delta=-69.0, percent=-1.4933105265600296e-06
deforestation: states: year: 2007, total=765236811.0, reference=765236811, delta=0.0
vegetation: states: year: 2007, total=3879056013.0, reference=3879056082, delta=-69.0, percent=-1.7787832540029772e-06
deforestation: states: year: 2008, total=780660748.0, reference=780660748, delta=0.0
vegetation: states: year: 2008, total=3863632076.0, reference=3863632145, delta=-69.0, percent=-1.7858843029167312e-06
deforestation: states: year: 2009, total=787323050.0, reference=787323050, delta=0.0
vegetation: states: year: 2009, total=3856969774.0, reference=3856969843, delta=-69.0, percent=-1.7889691340270093e-06
deforestation: states: year: 2010, total=795123372.0, reference=795123372, delta=0.0
vegetation: states: year: 2010, total=3849169452.0, reference=3849169521, delta=-69.0, percent=-1.7925944706658194e-06
deforestation: states: year: 2011, total=801406714.0, reference=801406714, delta=0.0
vegetation: states: year: 2011, total=3842886110.0, reference=3842886179, delta=-69.0, percent=-1.7955254666937664e-06
deforestation: states: year: 2012, total=806164960.0, reference=806164960, delta=0.0
vegetation: states: year: 2012, total=3838127864.0, reference=3838127933, delta=-69.0, percent=-1.797751435191673e-06
deforestation: states: year: 2013, total=813316107.0, reference=813316107, delta=0.0
vegetation: states: year: 2013, total=3830976717.0, reference=3830976786, delta=-69.0, percent=-1.8011072333341986e-06
deforestation: states: year: 2014, total=819650700.0, reference=819650700, delta=0.0
vegetation: states: year: 2014, total=3824642124.0, reference=3824642193, delta=-69.0, percent=-1.804090331019365e-06
deforestation: states: year: 2015, total=828072468.0, reference=828072468, delta=0.0
vegetation: states: year: 2015, total=3816220356.0, reference=3816220425, delta=-69.0, percent=-1.8080716603260675e-06
deforestation: states: year: 2016, total=837591324.0, reference=837591324, delta=0.0
vegetation: states: year: 2016, total=3806701500.0, reference=3806701569, delta=-69.0, percent=-1.8125928379020771e-06
deforestation: states: year: 2017, total=845362992.0, reference=845362992, delta=0.0
vegetation: states: year: 2017, total=3798929832.0, reference=3798929901, delta=-69.0, percent=-1.8163009531141123e-06
deforestation: states: year: 2018, total=854617475.0, reference=854617475, delta=0.0
vegetation: states: year: 2018, total=3789675349.0, reference=3789675418, delta=-69.0, percent=-1.8207364058744305e-06
deforestation: states: year: 2019, total=868085249.0, reference=868085249, delta=0.0
vegetation: states: year: 2019, total=3776207575.0, reference=3776207644, delta=-69.0, percent=-1.8272300282436481e-06
deforestation: states: year: 2020, total=880719572.0, reference=880719572, delta=0.0
vegetation: states: year: 2020, total=3763573252.0, reference=3763573321, delta=-69.0, percent=-1.833364043022453e-06
deforestation: states: year: 2021, total=895446744.0, reference=895446744, delta=0.0
vegetation: states: year: 2021, total=3748846080.0, reference=3748846149, delta=-69.0, percent=-1.8405663304802643e-06
deforestation: states: year: 2022, total=910644324.0, reference=910644324, delta=0.0
vegetation: states: year: 2022, total=3733648500.0, reference=3733648569, delta=-69.0, percent=-1.8480582391416817e-06
deforestation: states: year: 2023, total=920295018.0, reference=920295018, delta=0.0
vegetation: states: year: 2023, total=3723997806.0, reference=3723997875, delta=-69.0, percent=-1.8528474589959319e-06
deforestation: states: year: 2024, total=928192315.0, reference=928192315, delta=0.0
vegetation: states: year: 2024, total=3716100509.0, reference=3716100578, delta=-69.0, percent=-1.8567850506655474e-06
deforestation: states: year: 2025, total=935145345.0, reference=935145345, delta=0.0
vegetation: states: year: 2025, total=3709147479.0, reference=3709147548, delta=-69.0, percent=-1.8602657108425171e-06
_
deforestation: municipalities: year: 2000, total=14828887.0, reference=14828887, delta=0.0
vegetation: municipalities: year: 2000, total=4629464006.0, reference=4629464006, delta=0.0, percent=0.0
deforestation: municipalities: year: 2001, total=14828887.0, reference=14828887, delta=0.0
vegetation: municipalities: year: 2001, total=4629464006.0, reference=4629464006, delta=0.0, percent=0.0