In [1]:
import numpy as np
import pandas as pd

from pathlib import Path

# vars
___

In [2]:
ROOT_DIR = Path("/home/marcosilva/terrabrasilis/prodes/")
CACHE_DIR = ROOT_DIR / "cache"

In [3]:
LAND_USE_TYPE = "ppcdam"  # ams, ppcdam

In [4]:
reference = {}

biome = "Amazônia"

spatial_units = ["cs_5km", "cs_25km", "cs_150km", "states", "municipalities"]

In [5]:
from ams_background_tasks.tools.common import PIXEL_LAND_USE_AREA

# helpers
___

In [6]:
def get_deforestation_pixels_by_land_use_filename(year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/count/spatial_unit_deforestation_landuse_counts_b{biome}_y{year}.pkl"


def get_vegetation_pixels_by_land_use_filename(year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/count/spatial_unit_vegetation_landuse_counts_b{biome}_y{year}.pkl"


def get_annual_increase_in_deforestation_indicator_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/annual_increase_in_deforestation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_accumulated_deforestation_indicator_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/accumulated_deforestation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_vegetation_from_mask_filename(biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/vegetation_from_mask_b{biome}.pkl"


def get_vegetation_from_deforestation(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/vegetation_from_deforestation_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_total_vegetation_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/vegetation_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def get_ratio_deforestation_to_vegetation_filename(first_year, last_year, biome):
    return CACHE_DIR / f"{LAND_USE_TYPE}/ratio_accumulated_deforestation_to_vegetation_indicator_b{biome}_from_y{first_year}_to_y{last_year}.pkl"


def load_dfr(filename, filters={}):
    assert filename.exists()
    
    dfr = pd.read_pickle(filename)

    mask = pd.Series(True, index=dfr.index)

    for col, value in filters.items():
        if isinstance(value, list):
            mask &= dfr[col].isin(value)
        else:
            mask &= dfr[col] == value

    return dfr[mask]

# deforestation pixels by land use (counts)
___

## prodes 2000

### hist (gdalinfo -hist)

(gdal1) marcosilva@like01:~/terrabrasilis/prodes/tmp$ gdalinfo -hist prodes_2000.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
Driver: GTiff/GeoTIFF
Files: prodes_2000.tif
       prodes_2000.tif.aux.xml
Size is 113737, 81560
Coordinate System is:
GEOGCRS["SIRGAS 2000",
    DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
        ELLIPSOID["GRS 1980",6378137,298.257222101004,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4674]]
Data axis to CRS axis mapping: 2,1
Origin = (-73.983180000000004,5.269580000000000)
Pixel Size = (0.000268900006155,-0.000268899950956)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -73.9831800,   5.2695800) ( 73d58'59.45"W,  5d16'10.49"N)
Lower Left  ( -73.9831800, -16.6619000) ( 73d58'59.45"W, 16d39'42.84"S)
Upper Right ( -43.3993000,   5.2695800) ( 43d23'57.48"W,  5d16'10.49"N)
Lower Right ( -43.3993000, -16.6619000) ( 43d23'57.48"W, 16d39'42.84"S)
Center      ( -58.6912400,  -5.6961600) ( 58d41'28.46"W,  5d41'46.18"S)
Band 1 Block=113737x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=1.000 
  256 buckets from -0.00196078 to 1.00196:
  4752981555 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 14828887 
  NoData Value=-3.4028235e+38
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=0.0031102090111207
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=0.055682453340745
    STATISTICS_VALID_PERCENT=51.4

### validation

In [21]:
reference = 14828887
reference_2000 = reference

year = 2000

filename = get_deforestation_pixels_by_land_use_filename(year=year, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/count/spatial_unit_deforestation_landuse_counts_bAmazônia_y2000.pkl

         suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0           1            1  5105507     cs_150km  2000  Amazônia        5740
1           1            1  5106752     cs_150km  2000  Amazônia        5383
2           1            1  5106828     cs_150km  2000  Amazônia        2241
3           1            2  5106828     cs_150km  2000  Amazônia         244
4           1            6  5105507     cs_150km  2000  Amazônia       37439
...       ...          ...      ...          ...   ...       ...         ...
25292  172994           12  1506583       cs_5km  2000  Amazônia         238
25293  172994           13  1506583       cs_5km  2000  Amazônia         283
25294  173032           13  1506583       cs_5km  2000  Amazônia        1786
25295  173037           12  1506583       cs_5km  2000  Amazônia         671
25296  173037           13  1506583       cs_5km  2000  Amazônia          14

[25297 rows x 7 columns]

In [22]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["num_pixels"].sum()
    delta = total - reference
    assert delta == 0
    print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}")

cs_5km: num_pixels=14828887, reference=14828887, delta=0
cs_25km: num_pixels=14828887, reference=14828887, delta=0
cs_150km: num_pixels=14828887, reference=14828887, delta=0
states: num_pixels=14828887, reference=14828887, delta=0
municipalities: num_pixels=14828887, reference=14828887, delta=0

## prodes 2015

### hist (gdalinfo -hist)

(gdal1) marcosilva@like01:~/terrabrasilis/prodes/tmp$ gdalinfo -hist prodes_2015.tif 
0...10...20...30...40...50...60...70...80...90...100 - done.
Driver: GTiff/GeoTIFF
Files: prodes_2015.tif
Size is 113737, 81560
Coordinate System is:
GEOGCRS["SIRGAS 2000",
    DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
        ELLIPSOID["GRS 1980",6378137,298.257222101004,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4674]]
Data axis to CRS axis mapping: 2,1
Origin = (-73.983180000000004,5.269580000000000)
Pixel Size = (0.000268900006155,-0.000268899950956)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -73.9831800,   5.2695800) ( 73d58'59.45"W,  5d16'10.49"N)
Lower Left  ( -73.9831800, -16.6619000) ( 73d58'59.45"W, 16d39'42.84"S)
Upper Right ( -43.3993000,   5.2695800) ( 43d23'57.48"W,  5d16'10.49"N)
Lower Right ( -43.3993000, -16.6619000) ( 43d23'57.48"W, 16d39'42.84"S)
Center      ( -58.6912400,  -5.6961600) ( 58d41'28.46"W,  5d41'46.18"S)
Band 1 Block=113737x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=1.000 
  256 buckets from -0.00196078 to 1.00196:
  4759388674 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8421768 
  NoData Value=-3.4028235e+38
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MINIMUM=0
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=0.0017809442728521
    STATISTICS_STDDEV=0.042163639671511
    STATISTICS_VALID_PERCENT=51.25

### validation

In [9]:
reference = 8421768
reference_2015 = reference

year = 2015

filename = get_deforestation_pixels_by_land_use_filename(year=year, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/count/spatial_unit_deforestation_landuse_counts_bAmazônia_y2015.pkl

         suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0           1            1  5106828     cs_150km  2015  Amazônia        3102
1           1            2  5106828     cs_150km  2015  Amazônia          79
2           1            6  5106828     cs_150km  2015  Amazônia          15
3           1            7  5106752     cs_150km  2015  Amazônia         120
4           1            7  5106828     cs_150km  2015  Amazônia         238
...       ...          ...      ...          ...   ...       ...         ...
59615  173070           13  1300706       cs_5km  2015  Amazônia          35
59616  173070           14  1300706       cs_5km  2015  Amazônia          13
59617  173073            6  1300706       cs_5km  2015  Amazônia           1
59618  173073           12  1300706       cs_5km  2015  Amazônia          15
59619  173073           13  1300706       cs_5km  2015  Amazônia        1203

[59620 rows x 7 columns]

In [10]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["num_pixels"].sum()
    delta = total - reference
    assert delta == 0
    print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}")

cs_5km: num_pixels=8421768, reference=8421768, delta=0
cs_25km: num_pixels=8421768, reference=8421768, delta=0
cs_150km: num_pixels=8421768, reference=8421768, delta=0
states: num_pixels=8421768, reference=8421768, delta=0
municipalities: num_pixels=8421768, reference=8421768, delta=0

## prodes 2024

### hist (gdalinfo -hist)

(gdal1) marcosilva@like01:~/terrabrasilis/prodes/tmp$ gdalinfo -hist prodes_2024.tif 
0...10...20...30...40...50...60...70...80...90...100 - done.
Driver: GTiff/GeoTIFF
Files: prodes_2024.tif
Size is 113737, 81560
Coordinate System is:
GEOGCRS["SIRGAS 2000",
    DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
        ELLIPSOID["GRS 1980",6378137,298.257222101004,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4674]]
Data axis to CRS axis mapping: 2,1
Origin = (-73.983180000000004,5.269580000000000)
Pixel Size = (0.000268900006155,-0.000268899950956)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -73.9831800,   5.2695800) ( 73d58'59.45"W,  5d16'10.49"N)
Lower Left  ( -73.9831800, -16.6619000) ( 73d58'59.45"W, 16d39'42.84"S)
Upper Right ( -43.3993000,   5.2695800) ( 43d23'57.48"W,  5d16'10.49"N)
Lower Right ( -43.3993000, -16.6619000) ( 43d23'57.48"W, 16d39'42.84"S)
Center      ( -58.6912400,  -5.6961600) ( 58d41'28.46"W,  5d41'46.18"S)
Band 1 Block=113737x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=1.000 
  256 buckets from -0.00196078 to 1.00196:
  4759913145 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7897297 
  NoData Value=-3.4028235e+38
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MINIMUM=0
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=0.0016761617485929
    STATISTICS_STDDEV=0.040906628196237
    STATISTICS_VALID_PERCENT=51.25

### validation

In [11]:
reference = 7897297
reference_2024 = reference

year = 2024

filename = get_deforestation_pixels_by_land_use_filename(year=year, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/count/spatial_unit_deforestation_landuse_counts_bAmazônia_y2024.pkl

         suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0           1            1  5105507     cs_150km  2024  Amazônia          60
1           1            1  5106752     cs_150km  2024  Amazônia         682
2           1            1  5106828     cs_150km  2024  Amazônia         148
3           1            6  5105507     cs_150km  2024  Amazônia         647
4           1            6  5106828     cs_150km  2024  Amazônia         188
...       ...          ...      ...          ...   ...       ...         ...
55574  173073           13  1300706       cs_5km  2024  Amazônia         179
55575  173074           12  1300706       cs_5km  2024  Amazônia          82
55576  173074           13  1300706       cs_5km  2024  Amazônia           3
55577  173075           12  1300706       cs_5km  2024  Amazônia         139
55578  173075           13  1300706       cs_5km  2024  Amazônia          16

[55579 rows x 7 columns]

In [12]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["num_pixels"].sum()
    delta = total - reference
    assert delta == 0
    print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}")

cs_5km: num_pixels=7897297, reference=7897297, delta=0
cs_25km: num_pixels=7897297, reference=7897297, delta=0
cs_150km: num_pixels=7897297, reference=7897297, delta=0
states: num_pixels=7897297, reference=7897297, delta=0
municipalities: num_pixels=7897297, reference=7897297, delta=0

# annual increase in deforestation indicator (relative counts)
___

In [13]:
filename = get_annual_increase_in_deforestation_indicator_filename(2000, 2025, biome)
assert filename.exists()
print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/annual_increase_in_deforestation_indicator_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,year,biome,deforestation_pixels
0,1,1,5105507,cs_150km,2000,Amazônia,5740
1,1,1,5106752,cs_150km,2000,Amazônia,5383
2,1,1,5106828,cs_150km,2000,Amazônia,2241
3,1,2,5106828,cs_150km,2000,Amazônia,244
4,1,6,5105507,cs_150km,2000,Amazônia,37439
...,...,...,...,...,...,...,...
41589,173072,13,1300706,cs_5km,2025,Amazônia,66
41590,173074,12,1300706,cs_5km,2025,Amazônia,276
41591,173074,13,1300706,cs_5km,2025,Amazônia,1
41592,173075,12,1300706,cs_5km,2025,Amazônia,19
41593,173075,13,1300706,cs_5km,2025,Amazônia,1

In [16]:
reference_dict = {
    2000: reference_2000,
    2015: reference_2015,
    2024: reference_2024,
}
    
for year in [2000, 2015, 2024]:
    for spatial_unit in spatial_units:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        reference = reference_dict[year]
        total = dfr["deforestation_pixels"].sum()
        delta = total - reference
        percent = abs(delta) / reference * 100
        assert percent < 0.0025
        print(f"{spatial_unit}: year: {year}, num_pixels={total}, reference={reference}, delta={delta} perent={percent:.6f}")

cs_5km: year: 2000, num_pixels=14828865, reference=14828887, delta=-22 perent=0.000148
cs_25km: year: 2000, num_pixels=14828865, reference=14828887, delta=-22 perent=0.000148
cs_150km: year: 2000, num_pixels=14828865, reference=14828887, delta=-22 perent=0.000148
states: year: 2000, num_pixels=14828865, reference=14828887, delta=-22 perent=0.000148
municipalities: year: 2000, num_pixels=14828865, reference=14828887, delta=-22 perent=0.000148
cs_5km: year: 2015, num_pixels=8421766, reference=8421768, delta=-2 perent=0.000024
cs_25km: year: 2015, num_pixels=8421766, reference=8421768, delta=-2 perent=0.000024
cs_150km: year: 2015, num_pixels=8421766, reference=8421768, delta=-2 perent=0.000024
states: year: 2015, num_pixels=8421766, reference=8421768, delta=-2 perent=0.000024
municipalities: year: 2015, num_pixels=8421766, reference=8421768, delta=-2 perent=0.000024
cs_5km: year: 2024, num_pixels=7897297, reference=7897297, delta=0 perent=0.000000
cs_25km: year: 2024, num_pixels=7897297, reference=7897297, delta=0 perent=0.000000
cs_150km: year: 2024, num_pixels=7897297, reference=7897297, delta=0 perent=0.000000
states: year: 2024, num_pixels=7897297, reference=7897297, delta=0 perent=0.000000
municipalities: year: 2024, num_pixels=7897297, reference=7897297, delta=0 perent=0.000000

In [ ]:
7897297 * PIXEL_LAND_USE_AREA

# accumulated deforestation indicator (absolute counts)
___

In [17]:
filename = get_annual_increase_in_deforestation_indicator_filename(2000, 2025, biome)
print(filename)
assert filename.exists()

years = np.arange(2000, 2025+1, 1).tolist()

annual_dfr = load_dfr(filename)

acc_dict = {}

for spatial_unit in spatial_units:
    _abs = 0
    acc_dict[spatial_unit] = {}
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        
        _rel = dfr["deforestation_pixels"].sum()
        _abs = _abs + _rel

        acc_dict[spatial_unit].update({
            year: {
                "relative": _rel,
                "absolute": _abs,
            }
        })

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/annual_increase_in_deforestation_indicator_bAmazônia_from_y2000_to_y2025.pkl

#### validating dict

In [18]:
acc_dict

{'cs_5km': {2000: {'relative': 14828865, 'absolute': 14828865},
  2001: {'relative': 0, 'absolute': 14828865},
  2002: {'relative': 3547555, 'absolute': 18376420},
  2003: {'relative': 0, 'absolute': 18376420},
  2004: {'relative': 3163500, 'absolute': 21539920},
  2005: {'relative': 0, 'absolute': 21539920},
  2006: {'relative': 2146572, 'absolute': 23686492},
  2007: {'relative': 741549640, 'absolute': 765236132},
  2008: {'relative': 15423926, 'absolute': 780660058},
  2009: {'relative': 6662302, 'absolute': 787322360},
  2010: {'relative': 7800316, 'absolute': 795122676},
  2011: {'relative': 6283340, 'absolute': 801406016},
  2012: {'relative': 4758245, 'absolute': 806164261},
  2013: {'relative': 7151111, 'absolute': 813315372},
  2014: {'relative': 6334589, 'absolute': 819649961},
  2015: {'relative': 8421766, 'absolute': 828071727},
  2016: {'relative': 9518856, 'absolute': 837590583},
  2017: {'relative': 7771668, 'absolute': 845362251},
  2018: {'relative': 9254466, 'absolute': 854616717},
  2019: {'relative': 13467774, 'absolute': 868084491},
  2020: {'relative': 12634323, 'absolute': 880718814},
  2021: {'relative': 14727172, 'absolute': 895445986},
  2022: {'relative': 15197573, 'absolute': 910643559},
  2023: {'relative': 9650693, 'absolute': 920294252},
  2024: {'relative': 7897297, 'absolute': 928191549},
  2025: {'relative': 6953029, 'absolute': 935144578}},
 'cs_25km': {2000: {'relative': 14828865, 'absolute': 14828865},
  2001: {'relative': 0, 'absolute': 14828865},
  2002: {'relative': 3547555, 'absolute': 18376420},
  2003: {'relative': 0, 'absolute': 18376420},
  2004: {'relative': 3163500, 'absolute': 21539920},
  2005: {'relative': 0, 'absolute': 21539920},
  2006: {'relative': 2146572, 'absolute': 23686492},
  2007: {'relative': 741549640, 'absolute': 765236132},
  2008: {'relative': 15423926, 'absolute': 780660058},
  2009: {'relative': 6662302, 'absolute': 787322360},
  2010: {'relative': 7800316, 'absolute': 795122676},
  2011: {'relative': 6283340, 'absolute': 801406016},
  2012: {'relative': 4758245, 'absolute': 806164261},
  2013: {'relative': 7151111, 'absolute': 813315372},
  2014: {'relative': 6334589, 'absolute': 819649961},
  2015: {'relative': 8421766, 'absolute': 828071727},
  2016: {'relative': 9518856, 'absolute': 837590583},
  2017: {'relative': 7771668, 'absolute': 845362251},
  2018: {'relative': 9254466, 'absolute': 854616717},
  2019: {'relative': 13467774, 'absolute': 868084491},
  2020: {'relative': 12634323, 'absolute': 880718814},
  2021: {'relative': 14727172, 'absolute': 895445986},
  2022: {'relative': 15197573, 'absolute': 910643559},
  2023: {'relative': 9650693, 'absolute': 920294252},
  2024: {'relative': 7897297, 'absolute': 928191549},
  2025: {'relative': 6953029, 'absolute': 935144578}},
 'cs_150km': {2000: {'relative': 14828865, 'absolute': 14828865},
  2001: {'relative': 0, 'absolute': 14828865},
  2002: {'relative': 3547555, 'absolute': 18376420},
  2003: {'relative': 0, 'absolute': 18376420},
  2004: {'relative': 3163500, 'absolute': 21539920},
  2005: {'relative': 0, 'absolute': 21539920},
  2006: {'relative': 2146572, 'absolute': 23686492},
  2007: {'relative': 741549640, 'absolute': 765236132},
  2008: {'relative': 15423926, 'absolute': 780660058},
  2009: {'relative': 6662302, 'absolute': 787322360},
  2010: {'relative': 7800316, 'absolute': 795122676},
  2011: {'relative': 6283340, 'absolute': 801406016},
  2012: {'relative': 4758245, 'absolute': 806164261},
  2013: {'relative': 7151111, 'absolute': 813315372},
  2014: {'relative': 6334589, 'absolute': 819649961},
  2015: {'relative': 8421766, 'absolute': 828071727},
  2016: {'relative': 9518856, 'absolute': 837590583},
  2017: {'relative': 7771668, 'absolute': 845362251},
  2018: {'relative': 9254466, 'absolute': 854616717},
  2019: {'relative': 13467774, 'absolute': 868084491},
  2020: {'relative': 12634323, 'absolute': 880718814},
  2021: {'relative': 14727172, 'absolute': 895445986},
  2022: {'relative': 15197573, 'absolute': 910643559},
  2023: {'relative': 9650693, 'absolute': 920294252},
  2024: {'relative': 7897297, 'absolute': 928191549},
  2025: {'relative': 6953029, 'absolute': 935144578}},
 'states': {2000: {'relative': 14828865, 'absolute': 14828865},
  2001: {'relative': 0, 'absolute': 14828865},
  2002: {'relative': 3547555, 'absolute': 18376420},
  2003: {'relative': 0, 'absolute': 18376420},
  2004: {'relative': 3163500, 'absolute': 21539920},
  2005: {'relative': 0, 'absolute': 21539920},
  2006: {'relative': 2146572, 'absolute': 23686492},
  2007: {'relative': 741549640, 'absolute': 765236132},
  2008: {'relative': 15423926, 'absolute': 780660058},
  2009: {'relative': 6662302, 'absolute': 787322360},
  2010: {'relative': 7800316, 'absolute': 795122676},
  2011: {'relative': 6283340, 'absolute': 801406016},
  2012: {'relative': 4758245, 'absolute': 806164261},
  2013: {'relative': 7151111, 'absolute': 813315372},
  2014: {'relative': 6334589, 'absolute': 819649961},
  2015: {'relative': 8421766, 'absolute': 828071727},
  2016: {'relative': 9518856, 'absolute': 837590583},
  2017: {'relative': 7771668, 'absolute': 845362251},
  2018: {'relative': 9254466, 'absolute': 854616717},
  2019: {'relative': 13467774, 'absolute': 868084491},
  2020: {'relative': 12634323, 'absolute': 880718814},
  2021: {'relative': 14727172, 'absolute': 895445986},
  2022: {'relative': 15197573, 'absolute': 910643559},
  2023: {'relative': 9650693, 'absolute': 920294252},
  2024: {'relative': 7897297, 'absolute': 928191549},
  2025: {'relative': 6953029, 'absolute': 935144578}},
 'municipalities': {2000: {'relative': 14828865, 'absolute': 14828865},
  2001: {'relative': 0, 'absolute': 14828865},
  2002: {'relative': 3547555, 'absolute': 18376420},
  2003: {'relative': 0, 'absolute': 18376420},
  2004: {'relative': 3163500, 'absolute': 21539920},
  2005: {'relative': 0, 'absolute': 21539920},
  2006: {'relative': 2146572, 'absolute': 23686492},
  2007: {'relative': 741549640, 'absolute': 765236132},
  2008: {'relative': 15423926, 'absolute': 780660058},
  2009: {'relative': 6662302, 'absolute': 787322360},
  2010: {'relative': 7800316, 'absolute': 795122676},
  2011: {'relative': 6283340, 'absolute': 801406016},
  2012: {'relative': 4758245, 'absolute': 806164261},
  2013: {'relative': 7151111, 'absolute': 813315372},
  2014: {'relative': 6334589, 'absolute': 819649961},
  2015: {'relative': 8421766, 'absolute': 828071727},
  2016: {'relative': 9518856, 'absolute': 837590583},
  2017: {'relative': 7771668, 'absolute': 845362251},
  2018: {'relative': 9254466, 'absolute': 854616717},
  2019: {'relative': 13467774, 'absolute': 868084491},
  2020: {'relative': 12634323, 'absolute': 880718814},
  2021: {'relative': 14727172, 'absolute': 895445986},
  2022: {'relative': 15197573, 'absolute': 910643559},
  2023: {'relative': 9650693, 'absolute': 920294252},
  2024: {'relative': 7897297, 'absolute': 928191549},
  2025: {'relative': 6953029, 'absolute': 935144578}}}

In [24]:
reference_2000 - acc_dict[su][2000]['relative']

22

In [26]:
for su in spatial_units:
    assert acc_dict[su][2000]['relative'] - reference_2000 < abs(30)
    assert acc_dict[su][2000]['absolute'] - reference_2000 < abs(30)

    assert acc_dict[su][2002]['absolute'] == acc_dict[su][2000]['relative'] + acc_dict[su][2002]['relative']
    assert acc_dict[su][2002]['absolute'] == acc_dict[su][2000]['relative'] + acc_dict[su][2002]['relative']
    assert acc_dict[su][2004]['absolute'] == acc_dict[su][2000]['relative'] + acc_dict[su][2002]['relative'] + acc_dict[su][2004]['relative']

### validation
___

In [27]:
filename = get_accumulated_deforestation_indicator_filename(2000, 2025, biome)
assert filename.exists()
print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/accumulated_deforestation_indicator_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,biome,deforestation_pixels,year
0,1,1,5105507,cs_150km,Amazônia,5740,2000
1,1,1,5106752,cs_150km,Amazônia,5383,2000
2,1,1,5106828,cs_150km,Amazônia,2241,2000
3,1,2,5106828,cs_150km,Amazônia,244,2000
4,1,6,5105507,cs_150km,Amazônia,37439,2000
...,...,...,...,...,...,...,...
292604,173076,12,1302405,cs_5km,Amazônia,2,2025
292605,173076,13,1300706,cs_5km,Amazônia,11640,2025
292606,173076,13,1302405,cs_5km,Amazônia,7973,2025
292607,173076,14,1300706,cs_5km,Amazônia,141,2025
292608,173076,14,1302405,cs_5km,Amazônia,118,2025

In [28]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        total = dfr["deforestation_pixels"].sum()
        reference = acc_dict["cs_5km"][year]['absolute']
        delta = total - reference
        assert delta == 0
        print(f"{spatial_unit}: year: {year}, accumulated={total}, reference={reference}, delta={delta}")

cs_5km: year: 2000, accumulated=14828865, reference=14828865, delta=0
cs_5km: year: 2001, accumulated=14828865, reference=14828865, delta=0
cs_5km: year: 2002, accumulated=18376420, reference=18376420, delta=0
cs_5km: year: 2003, accumulated=18376420, reference=18376420, delta=0
cs_5km: year: 2004, accumulated=21539920, reference=21539920, delta=0
cs_5km: year: 2005, accumulated=21539920, reference=21539920, delta=0
cs_5km: year: 2006, accumulated=23686492, reference=23686492, delta=0
cs_5km: year: 2007, accumulated=765236132, reference=765236132, delta=0
cs_5km: year: 2008, accumulated=780660058, reference=780660058, delta=0
cs_5km: year: 2009, accumulated=787322360, reference=787322360, delta=0
cs_5km: year: 2010, accumulated=795122676, reference=795122676, delta=0
cs_5km: year: 2011, accumulated=801406016, reference=801406016, delta=0
cs_5km: year: 2012, accumulated=806164261, reference=806164261, delta=0
cs_5km: year: 2013, accumulated=813315372, reference=813315372, delta=0
cs_5km: year: 2014, accumulated=819649961, reference=819649961, delta=0
cs_5km: year: 2015, accumulated=828071727, reference=828071727, delta=0
cs_5km: year: 2016, accumulated=837590583, reference=837590583, delta=0
cs_5km: year: 2017, accumulated=845362251, reference=845362251, delta=0
cs_5km: year: 2018, accumulated=854616717, reference=854616717, delta=0
cs_5km: year: 2019, accumulated=868084491, reference=868084491, delta=0
cs_5km: year: 2020, accumulated=880718814, reference=880718814, delta=0
cs_5km: year: 2021, accumulated=895445986, reference=895445986, delta=0
cs_5km: year: 2022, accumulated=910643559, reference=910643559, delta=0
cs_5km: year: 2023, accumulated=920294252, reference=920294252, delta=0
cs_5km: year: 2024, accumulated=928191549, reference=928191549, delta=0
cs_5km: year: 2025, accumulated=935144578, reference=935144578, delta=0
cs_25km: year: 2000, accumulated=14828865, reference=14828865, delta=0
cs_25km: year: 2001, accumulated=14828865, reference=14828865, delta=0
cs_25km: year: 2002, accumulated=18376420, reference=18376420, delta=0
cs_25km: year: 2003, accumulated=18376420, reference=18376420, delta=0
cs_25km: year: 2004, accumulated=21539920, reference=21539920, delta=0
cs_25km: year: 2005, accumulated=21539920, reference=21539920, delta=0
cs_25km: year: 2006, accumulated=23686492, reference=23686492, delta=0
cs_25km: year: 2007, accumulated=765236132, reference=765236132, delta=0
cs_25km: year: 2008, accumulated=780660058, reference=780660058, delta=0
cs_25km: year: 2009, accumulated=787322360, reference=787322360, delta=0
cs_25km: year: 2010, accumulated=795122676, reference=795122676, delta=0
cs_25km: year: 2011, accumulated=801406016, reference=801406016, delta=0
cs_25km: year: 2012, accumulated=806164261, reference=806164261, delta=0
cs_25km: year: 2013, accumulated=813315372, reference=813315372, delta=0
cs_25km: year: 2014, accumulated=819649961, reference=819649961, delta=0
cs_25km: year: 2015, accumulated=828071727, reference=828071727, delta=0
cs_25km: year: 2016, accumulated=837590583, reference=837590583, delta=0
cs_25km: year: 2017, accumulated=845362251, reference=845362251, delta=0
cs_25km: year: 2018, accumulated=854616717, reference=854616717, delta=0
cs_25km: year: 2019, accumulated=868084491, reference=868084491, delta=0
cs_25km: year: 2020, accumulated=880718814, reference=880718814, delta=0
cs_25km: year: 2021, accumulated=895445986, reference=895445986, delta=0
cs_25km: year: 2022, accumulated=910643559, reference=910643559, delta=0
cs_25km: year: 2023, accumulated=920294252, reference=920294252, delta=0
cs_25km: year: 2024, accumulated=928191549, reference=928191549, delta=0
cs_25km: year: 2025, accumulated=935144578, reference=935144578, delta=0
cs_150km: year: 2000, accumulated=14828865, reference=14828865, delta=0
cs_150km: year: 2001, accumulated=14828865, reference=14828865, delta=0
cs_150km: year: 2002, accumulated=18376420, reference=18376420, delta=0
cs_150km: year: 2003, accumulated=18376420, reference=18376420, delta=0
cs_150km: year: 2004, accumulated=21539920, reference=21539920, delta=0
cs_150km: year: 2005, accumulated=21539920, reference=21539920, delta=0
cs_150km: year: 2006, accumulated=23686492, reference=23686492, delta=0
cs_150km: year: 2007, accumulated=765236132, reference=765236132, delta=0
cs_150km: year: 2008, accumulated=780660058, reference=780660058, delta=0
cs_150km: year: 2009, accumulated=787322360, reference=787322360, delta=0
cs_150km: year: 2010, accumulated=795122676, reference=795122676, delta=0
cs_150km: year: 2011, accumulated=801406016, reference=801406016, delta=0
cs_150km: year: 2012, accumulated=806164261, reference=806164261, delta=0
cs_150km: year: 2013, accumulated=813315372, reference=813315372, delta=0
cs_150km: year: 2014, accumulated=819649961, reference=819649961, delta=0
cs_150km: year: 2015, accumulated=828071727, reference=828071727, delta=0
cs_150km: year: 2016, accumulated=837590583, reference=837590583, delta=0
cs_150km: year: 2017, accumulated=845362251, reference=845362251, delta=0
cs_150km: year: 2018, accumulated=854616717, reference=854616717, delta=0
cs_150km: year: 2019, accumulated=868084491, reference=868084491, delta=0
cs_150km: year: 2020, accumulated=880718814, reference=880718814, delta=0
cs_150km: year: 2021, accumulated=895445986, reference=895445986, delta=0
cs_150km: year: 2022, accumulated=910643559, reference=910643559, delta=0
cs_150km: year: 2023, accumulated=920294252, reference=920294252, delta=0
cs_150km: year: 2024, accumulated=928191549, reference=928191549, delta=0
cs_150km: year: 2025, accumulated=935144578, reference=935144578, delta=0
states: year: 2000, accumulated=14828865, reference=14828865, delta=0
states: year: 2001, accumulated=14828865, reference=14828865, delta=0
states: year: 2002, accumulated=18376420, reference=18376420, delta=0
states: year: 2003, accumulated=18376420, reference=18376420, delta=0
states: year: 2004, accumulated=21539920, reference=21539920, delta=0
states: year: 2005, accumulated=21539920, reference=21539920, delta=0
states: year: 2006, accumulated=23686492, reference=23686492, delta=0
states: year: 2007, accumulated=765236132, reference=765236132, delta=0
states: year: 2008, accumulated=780660058, reference=780660058, delta=0
states: year: 2009, accumulated=787322360, reference=787322360, delta=0
states: year: 2010, accumulated=795122676, reference=795122676, delta=0
states: year: 2011, accumulated=801406016, reference=801406016, delta=0
states: year: 2012, accumulated=806164261, reference=806164261, delta=0
states: year: 2013, accumulated=813315372, reference=813315372, delta=0
states: year: 2014, accumulated=819649961, reference=819649961, delta=0
states: year: 2015, accumulated=828071727, reference=828071727, delta=0
states: year: 2016, accumulated=837590583, reference=837590583, delta=0
states: year: 2017, accumulated=845362251, reference=845362251, delta=0
states: year: 2018, accumulated=854616717, reference=854616717, delta=0
states: year: 2019, accumulated=868084491, reference=868084491, delta=0
states: year: 2020, accumulated=880718814, reference=880718814, delta=0
states: year: 2021, accumulated=895445986, reference=895445986, delta=0
states: year: 2022, accumulated=910643559, reference=910643559, delta=0
states: year: 2023, accumulated=920294252, reference=920294252, delta=0
states: year: 2024, accumulated=928191549, reference=928191549, delta=0
states: year: 2025, accumulated=935144578, reference=935144578, delta=0
municipalities: year: 2000, accumulated=14828865, reference=14828865, delta=0
municipalities: year: 2001, accumulated=14828865, reference=14828865, delta=0
municipalities: year: 2002, accumulated=18376420, reference=18376420, delta=0
municipalities: year: 2003, accumulated=18376420, reference=18376420, delta=0
municipalities: year: 2004, accumulated=21539920, reference=21539920, delta=0
municipalities: year: 2005, accumulated=21539920, reference=21539920, delta=0
municipalities: year: 2006, accumulated=23686492, reference=23686492, delta=0
municipalities: year: 2007, accumulated=765236132, reference=765236132, delta=0
municipalities: year: 2008, accumulated=780660058, reference=780660058, delta=0
municipalities: year: 2009, accumulated=787322360, reference=787322360, delta=0
municipalities: year: 2010, accumulated=795122676, reference=795122676, delta=0
municipalities: year: 2011, accumulated=801406016, reference=801406016, delta=0
municipalities: year: 2012, accumulated=806164261, reference=806164261, delta=0
municipalities: year: 2013, accumulated=813315372, reference=813315372, delta=0
municipalities: year: 2014, accumulated=819649961, reference=819649961, delta=0
municipalities: year: 2015, accumulated=828071727, reference=828071727, delta=0
municipalities: year: 2016, accumulated=837590583, reference=837590583, delta=0
municipalities: year: 2017, accumulated=845362251, reference=845362251, delta=0
municipalities: year: 2018, accumulated=854616717, reference=854616717, delta=0
municipalities: year: 2019, accumulated=868084491, reference=868084491, delta=0
municipalities: year: 2020, accumulated=880718814, reference=880718814, delta=0
municipalities: year: 2021, accumulated=895445986, reference=895445986, delta=0
municipalities: year: 2022, accumulated=910643559, reference=910643559, delta=0
municipalities: year: 2023, accumulated=920294252, reference=920294252, delta=0
municipalities: year: 2024, accumulated=928191549, reference=928191549, delta=0
municipalities: year: 2025, accumulated=935144578, reference=935144578, delta=0

In [ ]:
935144349 * PIXEL_LAND_USE_AREA

# native vegetation from mask (counts)
___

## hist (gdalinfo -hist)

(gdal1) marcosilva@like01:~/terrabrasilis/prodes/tmp$ gdalinfo -hist prodes_vegetation.tif 
0...10...20...30...40...50...60...70...80...90...100 - done.
Driver: GTiff/GeoTIFF
Files: prodes_vegetation.tif
Size is 113737, 81560
Coordinate System is:
GEOGCRS["SIRGAS 2000",
    DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
        ELLIPSOID["GRS 1980",6378137,298.257222101004,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4674]]
Data axis to CRS axis mapping: 2,1
Origin = (-73.983180000000004,5.269580000000000)
Pixel Size = (0.000268900006155,-0.000268899950956)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -73.9831800,   5.2695800) ( 73d58'59.45"W,  5d16'10.49"N)
Lower Left  ( -73.9831800, -16.6619000) ( 73d58'59.45"W, 16d39'42.84"S)
Upper Right ( -43.3993000,   5.2695800) ( 43d23'57.48"W,  5d16'10.49"N)
Lower Right ( -43.3993000, -16.6619000) ( 43d23'57.48"W, 16d39'42.84"S)
Center      ( -58.6912400,  -5.6961600) ( 58d41'28.46"W,  5d41'46.18"S)
Band 1 Block=113737x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=1.000 
  256 buckets from -0.00196078 to 1.00196:
  1058569990 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3709240452 
  NoData Value=-3.4028235e+38
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MINIMUM=0
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=0.77764538664898
    STATISTICS_STDDEV=0.41582813670134
    STATISTICS_VALID_PERCENT=51.25

## validation

In [29]:
reference = 3709240452

filename = get_vegetation_pixels_by_land_use_filename(year=2025, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/count/spatial_unit_vegetation_landuse_counts_bAmazônia_y2025.pkl

          suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0            1            1  5105507     cs_150km  2025  Amazônia       59973
1            1            1  5106752     cs_150km  2025  Amazônia       53122
2            1            1  5106828     cs_150km  2025  Amazônia       99806
3            1            2  5106752     cs_150km  2025  Amazônia         208
4            1            2  5106828     cs_150km  2025  Amazônia         586
...        ...          ...      ...          ...   ...       ...         ...
465290  173076            6  1300706       cs_5km  2025  Amazônia          12
465291  173076           12  1300706       cs_5km  2025  Amazônia        7170
465292  173076           12  1302405       cs_5km  2025  Amazônia          30
465293  173076           13  1300706       cs_5km  2025  Amazônia         223
465294  173076           13  1302405       cs_5km  2025  Amazônia         158

[465295 rows x 7 columns]

In [32]:
for spatial_unit in spatial_units:
    dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit})
    total = dfr["num_pixels"].sum()
    delta = total - reference
    percent = abs(delta) / reference * 100
    assert percent < 0.003
    print(f"{spatial_unit}: num_pixels={total}, reference={reference}, delta={delta}, percent={percent}")

cs_5km: num_pixels=3709147548, reference=3709240452, delta=-92904, percent=0.0025046637229977024
cs_25km: num_pixels=3709147548, reference=3709240452, delta=-92904, percent=0.0025046637229977024
cs_150km: num_pixels=3709147548, reference=3709240452, delta=-92904, percent=0.0025046637229977024
states: num_pixels=3709147479, reference=3709240452, delta=-92973, percent=0.0025065239421151442
municipalities: num_pixels=3709147548, reference=3709240452, delta=-92904, percent=0.0025046637229977024

# native vegetation from future deforestation (counts)
___

In [33]:
filename = get_vegetation_from_deforestation(first_year=2000, last_year=2025, biome=biome)
print(filename)
assert filename.exists()

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/vegetation_from_deforestation_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,biome,vegetation_pixels,year,source
0,1,1,5105507,cs_150km,Amazônia,5488,2000,deforestation
1,1,1,5106752,cs_150km,Amazônia,10511,2000,deforestation
2,1,1,5106828,cs_150km,Amazônia,36910,2000,deforestation
3,1,2,5106828,cs_150km,Amazônia,1809,2000,deforestation
4,1,6,5105507,cs_150km,Amazônia,52651,2000,deforestation
...,...,...,...,...,...,...,...,...
41589,173072,13,1300706,cs_5km,Amazônia,66,2024,deforestation
41590,173074,12,1300706,cs_5km,Amazônia,276,2024,deforestation
41591,173074,13,1300706,cs_5km,Amazônia,1,2024,deforestation
41592,173075,12,1300706,cs_5km,Amazônia,19,2024,deforestation
41593,173075,13,1300706,cs_5km,Amazônia,1,2024,deforestation

In [34]:
vegetation_from_deforestation = {}
years_dict = {}
for year1 in years:
    total = 0
    years_dict[year1] = ""
    for year2 in years:
        if year2 <= year1:
            continue
        total = total + acc_dict["cs_5km"][year2]['relative']
        years_dict[year1] = years_dict[year1] + f",{year2}"
    vegetation_from_deforestation[year1] = total

In [35]:
years_dict

{2000: ',2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2001: ',2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2002: ',2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2003: ',2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2004: ',2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2005: ',2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2006: ',2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2007: ',2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2008: ',2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2009: ',2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2010: ',2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2011: ',2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2012: ',2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2013: ',2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2014: ',2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2015: ',2016,2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2016: ',2017,2018,2019,2020,2021,2022,2023,2024,2025',
 2017: ',2018,2019,2020,2021,2022,2023,2024,2025',
 2018: ',2019,2020,2021,2022,2023,2024,2025',
 2019: ',2020,2021,2022,2023,2024,2025',
 2020: ',2021,2022,2023,2024,2025',
 2021: ',2022,2023,2024,2025',
 2022: ',2023,2024,2025',
 2023: ',2024,2025',
 2024: ',2025',
 2025: ''}

In [36]:
vegetation_from_deforestation

{2000: 920315713,
 2001: 920315713,
 2002: 916768158,
 2003: 916768158,
 2004: 913604658,
 2005: 913604658,
 2006: 911458086,
 2007: 169908446,
 2008: 154484520,
 2009: 147822218,
 2010: 140021902,
 2011: 133738562,
 2012: 128980317,
 2013: 121829206,
 2014: 115494617,
 2015: 107072851,
 2016: 97553995,
 2017: 89782327,
 2018: 80527861,
 2019: 67060087,
 2020: 54425764,
 2021: 39698592,
 2022: 24501019,
 2023: 14850326,
 2024: 6953029,
 2025: 0}

In [37]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        total = dfr["vegetation_pixels"].sum()
        reference = vegetation_from_deforestation[year]
        delta = total - reference
        assert delta == 0
        print(f"{spatial_unit}: {year}: num_pixels={total}, reference={reference}, delta={delta}")

cs_5km: 2000: num_pixels=920315713, reference=920315713, delta=0
cs_5km: 2001: num_pixels=920315713, reference=920315713, delta=0
cs_5km: 2002: num_pixels=916768158, reference=916768158, delta=0
cs_5km: 2003: num_pixels=916768158, reference=916768158, delta=0
cs_5km: 2004: num_pixels=913604658, reference=913604658, delta=0
cs_5km: 2005: num_pixels=913604658, reference=913604658, delta=0
cs_5km: 2006: num_pixels=911458086, reference=911458086, delta=0
cs_5km: 2007: num_pixels=169908446, reference=169908446, delta=0
cs_5km: 2008: num_pixels=154484520, reference=154484520, delta=0
cs_5km: 2009: num_pixels=147822218, reference=147822218, delta=0
cs_5km: 2010: num_pixels=140021902, reference=140021902, delta=0
cs_5km: 2011: num_pixels=133738562, reference=133738562, delta=0
cs_5km: 2012: num_pixels=128980317, reference=128980317, delta=0
cs_5km: 2013: num_pixels=121829206, reference=121829206, delta=0
cs_5km: 2014: num_pixels=115494617, reference=115494617, delta=0
cs_5km: 2015: num_pixels=107072851, reference=107072851, delta=0
cs_5km: 2016: num_pixels=97553995, reference=97553995, delta=0
cs_5km: 2017: num_pixels=89782327, reference=89782327, delta=0
cs_5km: 2018: num_pixels=80527861, reference=80527861, delta=0
cs_5km: 2019: num_pixels=67060087, reference=67060087, delta=0
cs_5km: 2020: num_pixels=54425764, reference=54425764, delta=0
cs_5km: 2021: num_pixels=39698592, reference=39698592, delta=0
cs_5km: 2022: num_pixels=24501019, reference=24501019, delta=0
cs_5km: 2023: num_pixels=14850326, reference=14850326, delta=0
cs_5km: 2024: num_pixels=6953029, reference=6953029, delta=0
cs_5km: 2025: num_pixels=0, reference=0, delta=0
cs_25km: 2000: num_pixels=920315713, reference=920315713, delta=0
cs_25km: 2001: num_pixels=920315713, reference=920315713, delta=0
cs_25km: 2002: num_pixels=916768158, reference=916768158, delta=0
cs_25km: 2003: num_pixels=916768158, reference=916768158, delta=0
cs_25km: 2004: num_pixels=913604658, reference=913604658, delta=0
cs_25km: 2005: num_pixels=913604658, reference=913604658, delta=0
cs_25km: 2006: num_pixels=911458086, reference=911458086, delta=0
cs_25km: 2007: num_pixels=169908446, reference=169908446, delta=0
cs_25km: 2008: num_pixels=154484520, reference=154484520, delta=0
cs_25km: 2009: num_pixels=147822218, reference=147822218, delta=0
cs_25km: 2010: num_pixels=140021902, reference=140021902, delta=0
cs_25km: 2011: num_pixels=133738562, reference=133738562, delta=0
cs_25km: 2012: num_pixels=128980317, reference=128980317, delta=0
cs_25km: 2013: num_pixels=121829206, reference=121829206, delta=0
cs_25km: 2014: num_pixels=115494617, reference=115494617, delta=0
cs_25km: 2015: num_pixels=107072851, reference=107072851, delta=0
cs_25km: 2016: num_pixels=97553995, reference=97553995, delta=0
cs_25km: 2017: num_pixels=89782327, reference=89782327, delta=0
cs_25km: 2018: num_pixels=80527861, reference=80527861, delta=0
cs_25km: 2019: num_pixels=67060087, reference=67060087, delta=0
cs_25km: 2020: num_pixels=54425764, reference=54425764, delta=0
cs_25km: 2021: num_pixels=39698592, reference=39698592, delta=0
cs_25km: 2022: num_pixels=24501019, reference=24501019, delta=0
cs_25km: 2023: num_pixels=14850326, reference=14850326, delta=0
cs_25km: 2024: num_pixels=6953029, reference=6953029, delta=0
cs_25km: 2025: num_pixels=0, reference=0, delta=0
cs_150km: 2000: num_pixels=920315713, reference=920315713, delta=0
cs_150km: 2001: num_pixels=920315713, reference=920315713, delta=0
cs_150km: 2002: num_pixels=916768158, reference=916768158, delta=0
cs_150km: 2003: num_pixels=916768158, reference=916768158, delta=0
cs_150km: 2004: num_pixels=913604658, reference=913604658, delta=0
cs_150km: 2005: num_pixels=913604658, reference=913604658, delta=0
cs_150km: 2006: num_pixels=911458086, reference=911458086, delta=0
cs_150km: 2007: num_pixels=169908446, reference=169908446, delta=0
cs_150km: 2008: num_pixels=154484520, reference=154484520, delta=0
cs_150km: 2009: num_pixels=147822218, reference=147822218, delta=0
cs_150km: 2010: num_pixels=140021902, reference=140021902, delta=0
cs_150km: 2011: num_pixels=133738562, reference=133738562, delta=0
cs_150km: 2012: num_pixels=128980317, reference=128980317, delta=0
cs_150km: 2013: num_pixels=121829206, reference=121829206, delta=0
cs_150km: 2014: num_pixels=115494617, reference=115494617, delta=0
cs_150km: 2015: num_pixels=107072851, reference=107072851, delta=0
cs_150km: 2016: num_pixels=97553995, reference=97553995, delta=0
cs_150km: 2017: num_pixels=89782327, reference=89782327, delta=0
cs_150km: 2018: num_pixels=80527861, reference=80527861, delta=0
cs_150km: 2019: num_pixels=67060087, reference=67060087, delta=0
cs_150km: 2020: num_pixels=54425764, reference=54425764, delta=0
cs_150km: 2021: num_pixels=39698592, reference=39698592, delta=0
cs_150km: 2022: num_pixels=24501019, reference=24501019, delta=0
cs_150km: 2023: num_pixels=14850326, reference=14850326, delta=0
cs_150km: 2024: num_pixels=6953029, reference=6953029, delta=0
cs_150km: 2025: num_pixels=0, reference=0, delta=0
states: 2000: num_pixels=920315713, reference=920315713, delta=0
states: 2001: num_pixels=920315713, reference=920315713, delta=0
states: 2002: num_pixels=916768158, reference=916768158, delta=0
states: 2003: num_pixels=916768158, reference=916768158, delta=0
states: 2004: num_pixels=913604658, reference=913604658, delta=0
states: 2005: num_pixels=913604658, reference=913604658, delta=0
states: 2006: num_pixels=911458086, reference=911458086, delta=0
states: 2007: num_pixels=169908446, reference=169908446, delta=0
states: 2008: num_pixels=154484520, reference=154484520, delta=0
states: 2009: num_pixels=147822218, reference=147822218, delta=0
states: 2010: num_pixels=140021902, reference=140021902, delta=0
states: 2011: num_pixels=133738562, reference=133738562, delta=0
states: 2012: num_pixels=128980317, reference=128980317, delta=0
states: 2013: num_pixels=121829206, reference=121829206, delta=0
states: 2014: num_pixels=115494617, reference=115494617, delta=0
states: 2015: num_pixels=107072851, reference=107072851, delta=0
states: 2016: num_pixels=97553995, reference=97553995, delta=0
states: 2017: num_pixels=89782327, reference=89782327, delta=0
states: 2018: num_pixels=80527861, reference=80527861, delta=0
states: 2019: num_pixels=67060087, reference=67060087, delta=0
states: 2020: num_pixels=54425764, reference=54425764, delta=0
states: 2021: num_pixels=39698592, reference=39698592, delta=0
states: 2022: num_pixels=24501019, reference=24501019, delta=0
states: 2023: num_pixels=14850326, reference=14850326, delta=0
states: 2024: num_pixels=6953029, reference=6953029, delta=0
states: 2025: num_pixels=0, reference=0, delta=0
municipalities: 2000: num_pixels=920315713, reference=920315713, delta=0
municipalities: 2001: num_pixels=920315713, reference=920315713, delta=0
municipalities: 2002: num_pixels=916768158, reference=916768158, delta=0
municipalities: 2003: num_pixels=916768158, reference=916768158, delta=0
municipalities: 2004: num_pixels=913604658, reference=913604658, delta=0
municipalities: 2005: num_pixels=913604658, reference=913604658, delta=0
municipalities: 2006: num_pixels=911458086, reference=911458086, delta=0
municipalities: 2007: num_pixels=169908446, reference=169908446, delta=0
municipalities: 2008: num_pixels=154484520, reference=154484520, delta=0
municipalities: 2009: num_pixels=147822218, reference=147822218, delta=0
municipalities: 2010: num_pixels=140021902, reference=140021902, delta=0
municipalities: 2011: num_pixels=133738562, reference=133738562, delta=0
municipalities: 2012: num_pixels=128980317, reference=128980317, delta=0
municipalities: 2013: num_pixels=121829206, reference=121829206, delta=0
municipalities: 2014: num_pixels=115494617, reference=115494617, delta=0
municipalities: 2015: num_pixels=107072851, reference=107072851, delta=0
municipalities: 2016: num_pixels=97553995, reference=97553995, delta=0
municipalities: 2017: num_pixels=89782327, reference=89782327, delta=0
municipalities: 2018: num_pixels=80527861, reference=80527861, delta=0
municipalities: 2019: num_pixels=67060087, reference=67060087, delta=0
municipalities: 2020: num_pixels=54425764, reference=54425764, delta=0
municipalities: 2021: num_pixels=39698592, reference=39698592, delta=0
municipalities: 2022: num_pixels=24501019, reference=24501019, delta=0
municipalities: 2023: num_pixels=14850326, reference=14850326, delta=0
municipalities: 2024: num_pixels=6953029, reference=6953029, delta=0
municipalities: 2025: num_pixels=0, reference=0, delta=0

# total native vegetation
___

In [38]:
filename = get_vegetation_pixels_by_land_use_filename(year=2025, biome=biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/count/spatial_unit_vegetation_landuse_counts_bAmazônia_y2025.pkl

          suid  land_use_id  geocode spatial_unit  year     biome  num_pixels
0            1            1  5105507     cs_150km  2025  Amazônia       59973
1            1            1  5106752     cs_150km  2025  Amazônia       53122
2            1            1  5106828     cs_150km  2025  Amazônia       99806
3            1            2  5106752     cs_150km  2025  Amazônia         208
4            1            2  5106828     cs_150km  2025  Amazônia         586
...        ...          ...      ...          ...   ...       ...         ...
465290  173076            6  1300706       cs_5km  2025  Amazônia          12
465291  173076           12  1300706       cs_5km  2025  Amazônia        7170
465292  173076           12  1302405       cs_5km  2025  Amazônia          30
465293  173076           13  1300706       cs_5km  2025  Amazônia         223
465294  173076           13  1302405       cs_5km  2025  Amazônia         158

[465295 rows x 7 columns]

In [39]:
total_vegetation = {}
for year in years:
    dfr = load_dfr(filename, filters={"spatial_unit": "cs_5km"})
    total_vegetation[year] = dfr["num_pixels"].sum() + vegetation_from_deforestation[year]

In [40]:
total_vegetation

{2000: 4629463261,
 2001: 4629463261,
 2002: 4625915706,
 2003: 4625915706,
 2004: 4622752206,
 2005: 4622752206,
 2006: 4620605634,
 2007: 3879055994,
 2008: 3863632068,
 2009: 3856969766,
 2010: 3849169450,
 2011: 3842886110,
 2012: 3838127865,
 2013: 3830976754,
 2014: 3824642165,
 2015: 3816220399,
 2016: 3806701543,
 2017: 3798929875,
 2018: 3789675409,
 2019: 3776207635,
 2020: 3763573312,
 2021: 3748846140,
 2022: 3733648567,
 2023: 3723997874,
 2024: 3716100577,
 2025: 3709147548}

In [41]:
filename = get_total_vegetation_filename(2000, 2025, biome)
print(filename)
assert filename.exists()

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/vegetation_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,biome,vegetation_pixels,year
0,1,1,5105507,cs_150km,Amazônia,65461,2000
1,1,1,5106752,cs_150km,Amazônia,63633,2000
2,1,1,5106828,cs_150km,Amazônia,136716,2000
3,1,2,5106752,cs_150km,Amazônia,208,2000
4,1,2,5106828,cs_150km,Amazônia,2395,2000
...,...,...,...,...,...,...,...
465290,173076,6,1300706,cs_5km,Amazônia,12,2025
465291,173076,12,1300706,cs_5km,Amazônia,7170,2025
465292,173076,12,1302405,cs_5km,Amazônia,30,2025
465293,173076,13,1300706,cs_5km,Amazônia,223,2025
465294,173076,13,1302405,cs_5km,Amazônia,158,2025

In [42]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        total = dfr["vegetation_pixels"].sum()
        reference = total_vegetation[year]
        delta = total - reference
        percent = abs(delta) / reference * 100
        assert percent < 0.003
        print(f"{spatial_unit}: year: {year}, total={total}, reference={reference}, delta={delta}, percent={percent}")

cs_5km: year: 2000, total=4629435422, reference=4629463261, delta=-27839, percent=0.0006013440096722262
cs_5km: year: 2001, total=4629435422, reference=4629463261, delta=-27839, percent=0.0006013440096722262
cs_5km: year: 2002, total=4625887867, reference=4625915706, delta=-27839, percent=0.0006018051726254261
cs_5km: year: 2003, total=4625887867, reference=4625915706, delta=-27839, percent=0.0006018051726254261
cs_5km: year: 2004, total=4622724367, reference=4622752206, delta=-27839, percent=0.0006022170075191784
cs_5km: year: 2005, total=4622724367, reference=4622752206, delta=-27839, percent=0.0006022170075191784
cs_5km: year: 2006, total=4620577795, reference=4620605634, delta=-27839, percent=0.0006024967765080641
cs_5km: year: 2007, total=3879028155, reference=3879055994, delta=-27839, percent=0.000717674610602695
cs_5km: year: 2008, total=3863604229, reference=3863632068, delta=-27839, percent=0.0007205396246338433
cs_5km: year: 2009, total=3856941927, reference=3856969766, delta=-27839, percent=0.0007217842422672493
cs_5km: year: 2010, total=3849141611, reference=3849169450, delta=-27839, percent=0.0007232469331793122
cs_5km: year: 2011, total=3842858271, reference=3842886110, delta=-27839, percent=0.0007244294835477182
cs_5km: year: 2012, total=3838100026, reference=3838127865, delta=-27839, percent=0.0007253275810288827
cs_5km: year: 2013, total=3830948915, reference=3830976754, delta=-27839, percent=0.0007266815172118373
cs_5km: year: 2014, total=3824614326, reference=3824642165, delta=-27839, percent=0.0007278850883034178
cs_5km: year: 2015, total=3816192560, reference=3816220399, delta=-27839, percent=0.000729491410068845
cs_5km: year: 2016, total=3806673704, reference=3806701543, delta=-27839, percent=0.00073131554143487
cs_5km: year: 2017, total=3798902036, reference=3798929875, delta=-27839, percent=0.0007328116315913833
cs_5km: year: 2018, total=3789647570, reference=3789675409, delta=-27839, percent=0.0007346011728045598
cs_5km: year: 2019, total=3776179796, reference=3776207635, delta=-27839, percent=0.0007372211141668326
cs_5km: year: 2020, total=3763545473, reference=3763573312, delta=-27839, percent=0.0007396959668949847
cs_5km: year: 2021, total=3748818301, reference=3748846140, delta=-27839, percent=0.0007426018289456926
cs_5km: year: 2022, total=3733620728, reference=3733648567, delta=-27839, percent=0.0007456245412612236
cs_5km: year: 2023, total=3723970035, reference=3723997874, delta=-27839, percent=0.0007475568177512874
cs_5km: year: 2024, total=3716072738, reference=3716100577, delta=-27839, percent=0.0007491454933244667
cs_5km: year: 2025, total=3709119709, reference=3709147548, delta=-27839, percent=0.0007505498133934035
cs_25km: year: 2000, total=4629435422, reference=4629463261, delta=-27839, percent=0.0006013440096722262
cs_25km: year: 2001, total=4629435422, reference=4629463261, delta=-27839, percent=0.0006013440096722262
cs_25km: year: 2002, total=4625887867, reference=4625915706, delta=-27839, percent=0.0006018051726254261
cs_25km: year: 2003, total=4625887867, reference=4625915706, delta=-27839, percent=0.0006018051726254261
cs_25km: year: 2004, total=4622724367, reference=4622752206, delta=-27839, percent=0.0006022170075191784
cs_25km: year: 2005, total=4622724367, reference=4622752206, delta=-27839, percent=0.0006022170075191784
cs_25km: year: 2006, total=4620577795, reference=4620605634, delta=-27839, percent=0.0006024967765080641
cs_25km: year: 2007, total=3879028155, reference=3879055994, delta=-27839, percent=0.000717674610602695
cs_25km: year: 2008, total=3863604229, reference=3863632068, delta=-27839, percent=0.0007205396246338433
cs_25km: year: 2009, total=3856941927, reference=3856969766, delta=-27839, percent=0.0007217842422672493
cs_25km: year: 2010, total=3849141611, reference=3849169450, delta=-27839, percent=0.0007232469331793122
cs_25km: year: 2011, total=3842858271, reference=3842886110, delta=-27839, percent=0.0007244294835477182
cs_25km: year: 2012, total=3838100026, reference=3838127865, delta=-27839, percent=0.0007253275810288827
cs_25km: year: 2013, total=3830948915, reference=3830976754, delta=-27839, percent=0.0007266815172118373
cs_25km: year: 2014, total=3824614326, reference=3824642165, delta=-27839, percent=0.0007278850883034178
cs_25km: year: 2015, total=3816192560, reference=3816220399, delta=-27839, percent=0.000729491410068845
cs_25km: year: 2016, total=3806673704, reference=3806701543, delta=-27839, percent=0.00073131554143487
cs_25km: year: 2017, total=3798902036, reference=3798929875, delta=-27839, percent=0.0007328116315913833
cs_25km: year: 2018, total=3789647570, reference=3789675409, delta=-27839, percent=0.0007346011728045598
cs_25km: year: 2019, total=3776179796, reference=3776207635, delta=-27839, percent=0.0007372211141668326
cs_25km: year: 2020, total=3763545473, reference=3763573312, delta=-27839, percent=0.0007396959668949847
cs_25km: year: 2021, total=3748818301, reference=3748846140, delta=-27839, percent=0.0007426018289456926
cs_25km: year: 2022, total=3733620728, reference=3733648567, delta=-27839, percent=0.0007456245412612236
cs_25km: year: 2023, total=3723970035, reference=3723997874, delta=-27839, percent=0.0007475568177512874
cs_25km: year: 2024, total=3716072738, reference=3716100577, delta=-27839, percent=0.0007491454933244667
cs_25km: year: 2025, total=3709119709, reference=3709147548, delta=-27839, percent=0.0007505498133934035
cs_150km: year: 2000, total=4629435422, reference=4629463261, delta=-27839, percent=0.0006013440096722262
cs_150km: year: 2001, total=4629435422, reference=4629463261, delta=-27839, percent=0.0006013440096722262
cs_150km: year: 2002, total=4625887867, reference=4625915706, delta=-27839, percent=0.0006018051726254261
cs_150km: year: 2003, total=4625887867, reference=4625915706, delta=-27839, percent=0.0006018051726254261
cs_150km: year: 2004, total=4622724367, reference=4622752206, delta=-27839, percent=0.0006022170075191784
cs_150km: year: 2005, total=4622724367, reference=4622752206, delta=-27839, percent=0.0006022170075191784
cs_150km: year: 2006, total=4620577795, reference=4620605634, delta=-27839, percent=0.0006024967765080641
cs_150km: year: 2007, total=3879028155, reference=3879055994, delta=-27839, percent=0.000717674610602695
cs_150km: year: 2008, total=3863604229, reference=3863632068, delta=-27839, percent=0.0007205396246338433
cs_150km: year: 2009, total=3856941927, reference=3856969766, delta=-27839, percent=0.0007217842422672493
cs_150km: year: 2010, total=3849141611, reference=3849169450, delta=-27839, percent=0.0007232469331793122
cs_150km: year: 2011, total=3842858271, reference=3842886110, delta=-27839, percent=0.0007244294835477182
cs_150km: year: 2012, total=3838100026, reference=3838127865, delta=-27839, percent=0.0007253275810288827
cs_150km: year: 2013, total=3830948915, reference=3830976754, delta=-27839, percent=0.0007266815172118373
cs_150km: year: 2014, total=3824614326, reference=3824642165, delta=-27839, percent=0.0007278850883034178
cs_150km: year: 2015, total=3816192560, reference=3816220399, delta=-27839, percent=0.000729491410068845
cs_150km: year: 2016, total=3806673704, reference=3806701543, delta=-27839, percent=0.00073131554143487
cs_150km: year: 2017, total=3798902036, reference=3798929875, delta=-27839, percent=0.0007328116315913833
cs_150km: year: 2018, total=3789647570, reference=3789675409, delta=-27839, percent=0.0007346011728045598
cs_150km: year: 2019, total=3776179796, reference=3776207635, delta=-27839, percent=0.0007372211141668326
cs_150km: year: 2020, total=3763545473, reference=3763573312, delta=-27839, percent=0.0007396959668949847
cs_150km: year: 2021, total=3748818301, reference=3748846140, delta=-27839, percent=0.0007426018289456926
cs_150km: year: 2022, total=3733620728, reference=3733648567, delta=-27839, percent=0.0007456245412612236
cs_150km: year: 2023, total=3723970035, reference=3723997874, delta=-27839, percent=0.0007475568177512874
cs_150km: year: 2024, total=3716072738, reference=3716100577, delta=-27839, percent=0.0007491454933244667
cs_150km: year: 2025, total=3709119709, reference=3709147548, delta=-27839, percent=0.0007505498133934035
states: year: 2000, total=4629435356, reference=4629463261, delta=-27905, percent=0.0006027696609038929
states: year: 2001, total=4629435356, reference=4629463261, delta=-27905, percent=0.0006027696609038929
states: year: 2002, total=4625887801, reference=4625915706, delta=-27905, percent=0.0006032319171706066
states: year: 2003, total=4625887801, reference=4625915706, delta=-27905, percent=0.0006032319171706066
states: year: 2004, total=4622724301, reference=4622752206, delta=-27905, percent=0.0006036447284321516
states: year: 2005, total=4622724301, reference=4622752206, delta=-27905, percent=0.0006036447284321516
states: year: 2006, total=4620577729, reference=4620605634, delta=-27905, percent=0.0006039251606903096
states: year: 2007, total=3879028089, reference=3879055994, delta=-27905, percent=0.0007193760554929489
states: year: 2008, total=3863604163, reference=3863632068, delta=-27905, percent=0.0007222478618271992
states: year: 2009, total=3856941861, reference=3856969766, delta=-27905, percent=0.0007234954301687414
states: year: 2010, total=3849141545, reference=3849169450, delta=-27905, percent=0.0007249615887915769
states: year: 2011, total=3842858205, reference=3842886110, delta=-27905, percent=0.0007261469427206106
states: year: 2012, total=3838099960, reference=3838127865, delta=-27905, percent=0.0007270471693886624
states: year: 2013, total=3830948849, reference=3830976754, delta=-27905, percent=0.0007284043154494171
states: year: 2014, total=3824614260, reference=3824642165, delta=-27905, percent=0.0007296107399370263
states: year: 2015, total=3816192494, reference=3816220399, delta=-27905, percent=0.0007312208699296354
states: year: 2016, total=3806673638, reference=3806701543, delta=-27905, percent=0.0007330493259003573
states: year: 2017, total=3798901970, reference=3798929875, delta=-27905, percent=0.0007345489629497306
states: year: 2018, total=3789647504, reference=3789675409, delta=-27905, percent=0.000736342746762141
states: year: 2019, total=3776179730, reference=3776207635, delta=-27905, percent=0.0007389688994154052
states: year: 2020, total=3763545407, reference=3763573312, delta=-27905, percent=0.0007414496194620693
states: year: 2021, total=3748818235, reference=3748846140, delta=-27905, percent=0.0007443623706573352
states: year: 2022, total=3733620662, reference=3733648567, delta=-27905, percent=0.0007473922491430887
states: year: 2023, total=3723969969, reference=3723997874, delta=-27905, percent=0.0007493291066255856
states: year: 2024, total=3716072672, reference=3716100577, delta=-27905, percent=0.0007509215485907985
states: year: 2025, total=3709119643, reference=3709147548, delta=-27905, percent=0.0007523291979863833
municipalities: year: 2000, total=4629435422, reference=4629463261, delta=-27839, percent=0.0006013440096722262
municipalities: year: 2001, total=4629435422, reference=4629463261, delta=-27839, percent=0.0006013440096722262
municipalities: year: 2002, total=4625887867, reference=4625915706, delta=-27839, percent=0.0006018051726254261
municipalities: year: 2003, total=4625887867, reference=4625915706, delta=-27839, percent=0.0006018051726254261
municipalities: year: 2004, total=4622724367, reference=4622752206, delta=-27839, percent=0.0006022170075191784
municipalities: year: 2005, total=4622724367, reference=4622752206, delta=-27839, percent=0.0006022170075191784
municipalities: year: 2006, total=4620577795, reference=4620605634, delta=-27839, percent=0.0006024967765080641
municipalities: year: 2007, total=3879028155, reference=3879055994, delta=-27839, percent=0.000717674610602695
municipalities: year: 2008, total=3863604229, reference=3863632068, delta=-27839, percent=0.0007205396246338433
municipalities: year: 2009, total=3856941927, reference=3856969766, delta=-27839, percent=0.0007217842422672493
municipalities: year: 2010, total=3849141611, reference=3849169450, delta=-27839, percent=0.0007232469331793122
municipalities: year: 2011, total=3842858271, reference=3842886110, delta=-27839, percent=0.0007244294835477182
municipalities: year: 2012, total=3838100026, reference=3838127865, delta=-27839, percent=0.0007253275810288827
municipalities: year: 2013, total=3830948915, reference=3830976754, delta=-27839, percent=0.0007266815172118373
municipalities: year: 2014, total=3824614326, reference=3824642165, delta=-27839, percent=0.0007278850883034178
municipalities: year: 2015, total=3816192560, reference=3816220399, delta=-27839, percent=0.000729491410068845
municipalities: year: 2016, total=3806673704, reference=3806701543, delta=-27839, percent=0.00073131554143487
municipalities: year: 2017, total=3798902036, reference=3798929875, delta=-27839, percent=0.0007328116315913833
municipalities: year: 2018, total=3789647570, reference=3789675409, delta=-27839, percent=0.0007346011728045598
municipalities: year: 2019, total=3776179796, reference=3776207635, delta=-27839, percent=0.0007372211141668326
municipalities: year: 2020, total=3763545473, reference=3763573312, delta=-27839, percent=0.0007396959668949847
municipalities: year: 2021, total=3748818301, reference=3748846140, delta=-27839, percent=0.0007426018289456926
municipalities: year: 2022, total=3733620728, reference=3733648567, delta=-27839, percent=0.0007456245412612236
municipalities: year: 2023, total=3723970035, reference=3723997874, delta=-27839, percent=0.0007475568177512874
municipalities: year: 2024, total=3716072738, reference=3716100577, delta=-27839, percent=0.0007491454933244667
municipalities: year: 2025, total=3709119709, reference=3709147548, delta=-27839, percent=0.0007505498133934035

# ratio accumulated deforestation to native vegetation indicator
___

In [43]:
filename = get_ratio_deforestation_to_vegetation_filename(2000, 2025, biome)
assert filename.exists()

print(filename)

dfr = load_dfr(filename)
dfr

/home/marcosilva/terrabrasilis/prodes/cache/ppcdam/ratio_accumulated_deforestation_to_vegetation_indicator_bAmazônia_from_y2000_to_y2025.pkl

,suid,land_use_id,geocode,spatial_unit,biome,deforestation_pixels,year,vegetation_pixels,counts,area,counts2
0,1,1,5105507,cs_150km,Amazônia,5740.0,2000,65461.0,5740.0,5.123040,65461.0
1,1,1,5105507,cs_150km,Amazônia,5740.0,2001,65461.0,5740.0,5.123040,65461.0
2,1,1,5105507,cs_150km,Amazônia,7213.0,2002,63988.0,7213.0,6.437715,63988.0
3,1,1,5105507,cs_150km,Amazônia,7213.0,2003,63988.0,7213.0,6.437715,63988.0
4,1,1,5105507,cs_150km,Amazônia,7809.0,2004,63392.0,7809.0,6.969655,63392.0
...,...,...,...,...,...,...,...,...,...,...,...
12800367,173076,14,1302405,cs_5km,Amazônia,118.0,2021,0.0,118.0,0.105317,0.0
12800368,173076,14,1302405,cs_5km,Amazônia,118.0,2022,0.0,118.0,0.105317,0.0
12800369,173076,14,1302405,cs_5km,Amazônia,118.0,2023,0.0,118.0,0.105317,0.0
12800370,173076,14,1302405,cs_5km,Amazônia,118.0,2024,0.0,118.0,0.105317,0.0
12800371,173076,14,1302405,cs_5km,Amazônia,118.0,2025,0.0,118.0,0.105317,0.0

In [44]:
assert dfr.isna().sum().sum() == 0

In [45]:
for spatial_unit in spatial_units:
    for year in years:
        dfr = load_dfr(filename, filters={"spatial_unit": spatial_unit, "year": year})
        
        total1 = dfr["deforestation_pixels"].sum()
        reference1 = acc_dict["cs_5km"][year]['absolute']
        delta1 = total1 - reference1
        assert delta1 == 0
        print(f"deforestation: {spatial_unit}: year: {year}, total={total1}, reference={reference1}, delta={delta1}")

        total2 = dfr["vegetation_pixels"].sum()
        reference2 = total_vegetation[year]
        delta2 = total2 - reference2
        percent2 = abs(delta2) / reference2 * 100
        assert percent2 < 0.003
        
        print(f"vegetation: {spatial_unit}: year: {year}, total={total2}, reference={reference2}, delta={delta2}, percent={percent2}")
    print("_")

deforestation: cs_5km: year: 2000, total=14828865.0, reference=14828865, delta=0.0
vegetation: cs_5km: year: 2000, total=4629435422.0, reference=4629463261, delta=-27839.0, percent=0.0006013440096722262
deforestation: cs_5km: year: 2001, total=14828865.0, reference=14828865, delta=0.0
vegetation: cs_5km: year: 2001, total=4629435422.0, reference=4629463261, delta=-27839.0, percent=0.0006013440096722262
deforestation: cs_5km: year: 2002, total=18376420.0, reference=18376420, delta=0.0
vegetation: cs_5km: year: 2002, total=4625887867.0, reference=4625915706, delta=-27839.0, percent=0.0006018051726254261
deforestation: cs_5km: year: 2003, total=18376420.0, reference=18376420, delta=0.0
vegetation: cs_5km: year: 2003, total=4625887867.0, reference=4625915706, delta=-27839.0, percent=0.0006018051726254261
deforestation: cs_5km: year: 2004, total=21539920.0, reference=21539920, delta=0.0
vegetation: cs_5km: year: 2004, total=4622724367.0, reference=4622752206, delta=-27839.0, percent=0.0006022170075191784
deforestation: cs_5km: year: 2005, total=21539920.0, reference=21539920, delta=0.0
vegetation: cs_5km: year: 2005, total=4622724367.0, reference=4622752206, delta=-27839.0, percent=0.0006022170075191784
deforestation: cs_5km: year: 2006, total=23686492.0, reference=23686492, delta=0.0
vegetation: cs_5km: year: 2006, total=4620577795.0, reference=4620605634, delta=-27839.0, percent=0.0006024967765080641
deforestation: cs_5km: year: 2007, total=765236132.0, reference=765236132, delta=0.0
vegetation: cs_5km: year: 2007, total=3879028155.0, reference=3879055994, delta=-27839.0, percent=0.000717674610602695
deforestation: cs_5km: year: 2008, total=780660058.0, reference=780660058, delta=0.0
vegetation: cs_5km: year: 2008, total=3863604229.0, reference=3863632068, delta=-27839.0, percent=0.0007205396246338433
deforestation: cs_5km: year: 2009, total=787322360.0, reference=787322360, delta=0.0
vegetation: cs_5km: year: 2009, total=3856941927.0, reference=3856969766, delta=-27839.0, percent=0.0007217842422672493
deforestation: cs_5km: year: 2010, total=795122676.0, reference=795122676, delta=0.0
vegetation: cs_5km: year: 2010, total=3849141611.0, reference=3849169450, delta=-27839.0, percent=0.0007232469331793122
deforestation: cs_5km: year: 2011, total=801406016.0, reference=801406016, delta=0.0
vegetation: cs_5km: year: 2011, total=3842858271.0, reference=3842886110, delta=-27839.0, percent=0.0007244294835477182
deforestation: cs_5km: year: 2012, total=806164261.0, reference=806164261, delta=0.0
vegetation: cs_5km: year: 2012, total=3838100026.0, reference=3838127865, delta=-27839.0, percent=0.0007253275810288827
deforestation: cs_5km: year: 2013, total=813315372.0, reference=813315372, delta=0.0
vegetation: cs_5km: year: 2013, total=3830948915.0, reference=3830976754, delta=-27839.0, percent=0.0007266815172118373
deforestation: cs_5km: year: 2014, total=819649961.0, reference=819649961, delta=0.0
vegetation: cs_5km: year: 2014, total=3824614326.0, reference=3824642165, delta=-27839.0, percent=0.0007278850883034178
deforestation: cs_5km: year: 2015, total=828071727.0, reference=828071727, delta=0.0
vegetation: cs_5km: year: 2015, total=3816192560.0, reference=3816220399, delta=-27839.0, percent=0.000729491410068845
deforestation: cs_5km: year: 2016, total=837590583.0, reference=837590583, delta=0.0
vegetation: cs_5km: year: 2016, total=3806673704.0, reference=3806701543, delta=-27839.0, percent=0.00073131554143487
deforestation: cs_5km: year: 2017, total=845362251.0, reference=845362251, delta=0.0
vegetation: cs_5km: year: 2017, total=3798902036.0, reference=3798929875, delta=-27839.0, percent=0.0007328116315913833
deforestation: cs_5km: year: 2018, total=854616717.0, reference=854616717, delta=0.0
vegetation: cs_5km: year: 2018, total=3789647570.0, reference=3789675409, delta=-27839.0, percent=0.0007346011728045598
deforestation: cs_5km: year: 2019, total=868084491.0, reference=868084491, delta=0.0
vegetation: cs_5km: year: 2019, total=3776179796.0, reference=3776207635, delta=-27839.0, percent=0.0007372211141668326
deforestation: cs_5km: year: 2020, total=880718814.0, reference=880718814, delta=0.0
vegetation: cs_5km: year: 2020, total=3763545473.0, reference=3763573312, delta=-27839.0, percent=0.0007396959668949847
deforestation: cs_5km: year: 2021, total=895445986.0, reference=895445986, delta=0.0
vegetation: cs_5km: year: 2021, total=3748818301.0, reference=3748846140, delta=-27839.0, percent=0.0007426018289456926
deforestation: cs_5km: year: 2022, total=910643559.0, reference=910643559, delta=0.0
vegetation: cs_5km: year: 2022, total=3733620728.0, reference=3733648567, delta=-27839.0, percent=0.0007456245412612236
deforestation: cs_5km: year: 2023, total=920294252.0, reference=920294252, delta=0.0
vegetation: cs_5km: year: 2023, total=3723970035.0, reference=3723997874, delta=-27839.0, percent=0.0007475568177512874
deforestation: cs_5km: year: 2024, total=928191549.0, reference=928191549, delta=0.0
vegetation: cs_5km: year: 2024, total=3716072738.0, reference=3716100577, delta=-27839.0, percent=0.0007491454933244667
deforestation: cs_5km: year: 2025, total=935144578.0, reference=935144578, delta=0.0
vegetation: cs_5km: year: 2025, total=3709119709.0, reference=3709147548, delta=-27839.0, percent=0.0007505498133934035
_
deforestation: cs_25km: year: 2000, total=14828865.0, reference=14828865, delta=0.0
vegetation: cs_25km: year: 2000, total=4629435422.0, reference=4629463261, delta=-27839.0, percent=0.0006013440096722262
deforestation: cs_25km: year: 2001, total=14828865.0, reference=14828865, delta=0.0
vegetation: cs_25km: year: 2001, total=4629435422.0, reference=4629463261, delta=-27839.0, percent=0.0006013440096722262
deforestation: cs_25km: year: 2002, total=18376420.0, reference=18376420, delta=0.0
vegetation: cs_25km: year: 2002, total=4625887867.0, reference=4625915706, delta=-27839.0, percent=0.0006018051726254261
deforestation: cs_25km: year: 2003, total=18376420.0, reference=18376420, delta=0.0
vegetation: cs_25km: year: 2003, total=4625887867.0, reference=4625915706, delta=-27839.0, percent=0.0006018051726254261
deforestation: cs_25km: year: 2004, total=21539920.0, reference=21539920, delta=0.0
vegetation: cs_25km: year: 2004, total=4622724367.0, reference=4622752206, delta=-27839.0, percent=0.0006022170075191784
deforestation: cs_25km: year: 2005, total=21539920.0, reference=21539920, delta=0.0
vegetation: cs_25km: year: 2005, total=4622724367.0, reference=4622752206, delta=-27839.0, percent=0.0006022170075191784
deforestation: cs_25km: year: 2006, total=23686492.0, reference=23686492, delta=0.0
vegetation: cs_25km: year: 2006, total=4620577795.0, reference=4620605634, delta=-27839.0, percent=0.0006024967765080641
deforestation: cs_25km: year: 2007, total=765236132.0, reference=765236132, delta=0.0
vegetation: cs_25km: year: 2007, total=3879028155.0, reference=3879055994, delta=-27839.0, percent=0.000717674610602695
deforestation: cs_25km: year: 2008, total=780660058.0, reference=780660058, delta=0.0
vegetation: cs_25km: year: 2008, total=3863604229.0, reference=3863632068, delta=-27839.0, percent=0.0007205396246338433
deforestation: cs_25km: year: 2009, total=787322360.0, reference=787322360, delta=0.0
vegetation: cs_25km: year: 2009, total=3856941927.0, reference=3856969766, delta=-27839.0, percent=0.0007217842422672493
deforestation: cs_25km: year: 2010, total=795122676.0, reference=795122676, delta=0.0
vegetation: cs_25km: year: 2010, total=3849141611.0, reference=3849169450, delta=-27839.0, percent=0.0007232469331793122
deforestation: cs_25km: year: 2011, total=801406016.0, reference=801406016, delta=0.0
vegetation: cs_25km: year: 2011, total=3842858271.0, reference=3842886110, delta=-27839.0, percent=0.0007244294835477182
deforestation: cs_25km: year: 2012, total=806164261.0, reference=806164261, delta=0.0
vegetation: cs_25km: year: 2012, total=3838100026.0, reference=3838127865, delta=-27839.0, percent=0.0007253275810288827
deforestation: cs_25km: year: 2013, total=813315372.0, reference=813315372, delta=0.0
vegetation: cs_25km: year: 2013, total=3830948915.0, reference=3830976754, delta=-27839.0, percent=0.0007266815172118373
deforestation: cs_25km: year: 2014, total=819649961.0, reference=819649961, delta=0.0
vegetation: cs_25km: year: 2014, total=3824614326.0, reference=3824642165, delta=-27839.0, percent=0.0007278850883034178
deforestation: cs_25km: year: 2015, total=828071727.0, reference=828071727, delta=0.0
vegetation: cs_25km: year: 2015, total=3816192560.0, reference=3816220399, delta=-27839.0, percent=0.000729491410068845
deforestation: cs_25km: year: 2016, total=837590583.0, reference=837590583, delta=0.0
vegetation: cs_25km: year: 2016, total=3806673704.0, reference=3806701543, delta=-27839.0, percent=0.00073131554143487
deforestation: cs_25km: year: 2017, total=845362251.0, reference=845362251, delta=0.0
vegetation: cs_25km: year: 2017, total=3798902036.0, reference=3798929875, delta=-27839.0, percent=0.0007328116315913833
deforestation: cs_25km: year: 2018, total=854616717.0, reference=854616717, delta=0.0
vegetation: cs_25km: year: 2018, total=3789647570.0, reference=3789675409, delta=-27839.0, percent=0.0007346011728045598
deforestation: cs_25km: year: 2019, total=868084491.0, reference=868084491, delta=0.0
vegetation: cs_25km: year: 2019, total=3776179796.0, reference=3776207635, delta=-27839.0, percent=0.0007372211141668326
deforestation: cs_25km: year: 2020, total=880718814.0, reference=880718814, delta=0.0
vegetation: cs_25km: year: 2020, total=3763545473.0, reference=3763573312, delta=-27839.0, percent=0.0007396959668949847
deforestation: cs_25km: year: 2021, total=895445986.0, reference=895445986, delta=0.0
vegetation: cs_25km: year: 2021, total=3748818301.0, reference=3748846140, delta=-27839.0, percent=0.0007426018289456926
deforestation: cs_25km: year: 2022, total=910643559.0, reference=910643559, delta=0.0
vegetation: cs_25km: year: 2022, total=3733620728.0, reference=3733648567, delta=-27839.0, percent=0.0007456245412612236
deforestation: cs_25km: year: 2023, total=920294252.0, reference=920294252, delta=0.0
vegetation: cs_25km: year: 2023, total=3723970035.0, reference=3723997874, delta=-27839.0, percent=0.0007475568177512874
deforestation: cs_25km: year: 2024, total=928191549.0, reference=928191549, delta=0.0
vegetation: cs_25km: year: 2024, total=3716072738.0, reference=3716100577, delta=-27839.0, percent=0.0007491454933244667
deforestation: cs_25km: year: 2025, total=935144578.0, reference=935144578, delta=0.0
vegetation: cs_25km: year: 2025, total=3709119709.0, reference=3709147548, delta=-27839.0, percent=0.0007505498133934035
_
deforestation: cs_150km: year: 2000, total=14828865.0, reference=14828865, delta=0.0
vegetation: cs_150km: year: 2000, total=4629435422.0, reference=4629463261, delta=-27839.0, percent=0.0006013440096722262
deforestation: cs_150km: year: 2001, total=14828865.0, reference=14828865, delta=0.0
vegetation: cs_150km: year: 2001, total=4629435422.0, reference=4629463261, delta=-27839.0, percent=0.0006013440096722262
deforestation: cs_150km: year: 2002, total=18376420.0, reference=18376420, delta=0.0
vegetation: cs_150km: year: 2002, total=4625887867.0, reference=4625915706, delta=-27839.0, percent=0.0006018051726254261
deforestation: cs_150km: year: 2003, total=18376420.0, reference=18376420, delta=0.0
vegetation: cs_150km: year: 2003, total=4625887867.0, reference=4625915706, delta=-27839.0, percent=0.0006018051726254261
deforestation: cs_150km: year: 2004, total=21539920.0, reference=21539920, delta=0.0
vegetation: cs_150km: year: 2004, total=4622724367.0, reference=4622752206, delta=-27839.0, percent=0.0006022170075191784
deforestation: cs_150km: year: 2005, total=21539920.0, reference=21539920, delta=0.0
vegetation: cs_150km: year: 2005, total=4622724367.0, reference=4622752206, delta=-27839.0, percent=0.0006022170075191784
deforestation: cs_150km: year: 2006, total=23686492.0, reference=23686492, delta=0.0
vegetation: cs_150km: year: 2006, total=4620577795.0, reference=4620605634, delta=-27839.0, percent=0.0006024967765080641
deforestation: cs_150km: year: 2007, total=765236132.0, reference=765236132, delta=0.0
vegetation: cs_150km: year: 2007, total=3879028155.0, reference=3879055994, delta=-27839.0, percent=0.000717674610602695
deforestation: cs_150km: year: 2008, total=780660058.0, reference=780660058, delta=0.0
vegetation: cs_150km: year: 2008, total=3863604229.0, reference=3863632068, delta=-27839.0, percent=0.0007205396246338433
deforestation: cs_150km: year: 2009, total=787322360.0, reference=787322360, delta=0.0
vegetation: cs_150km: year: 2009, total=3856941927.0, reference=3856969766, delta=-27839.0, percent=0.0007217842422672493
deforestation: cs_150km: year: 2010, total=795122676.0, reference=795122676, delta=0.0
vegetation: cs_150km: year: 2010, total=3849141611.0, reference=3849169450, delta=-27839.0, percent=0.0007232469331793122
deforestation: cs_150km: year: 2011, total=801406016.0, reference=801406016, delta=0.0
vegetation: cs_150km: year: 2011, total=3842858271.0, reference=3842886110, delta=-27839.0, percent=0.0007244294835477182
deforestation: cs_150km: year: 2012, total=806164261.0, reference=806164261, delta=0.0
vegetation: cs_150km: year: 2012, total=3838100026.0, reference=3838127865, delta=-27839.0, percent=0.0007253275810288827
deforestation: cs_150km: year: 2013, total=813315372.0, reference=813315372, delta=0.0
vegetation: cs_150km: year: 2013, total=3830948915.0, reference=3830976754, delta=-27839.0, percent=0.0007266815172118373
deforestation: cs_150km: year: 2014, total=819649961.0, reference=819649961, delta=0.0
vegetation: cs_150km: year: 2014, total=3824614326.0, reference=3824642165, delta=-27839.0, percent=0.0007278850883034178
deforestation: cs_150km: year: 2015, total=828071727.0, reference=828071727, delta=0.0
vegetation: cs_150km: year: 2015, total=3816192560.0, reference=3816220399, delta=-27839.0, percent=0.000729491410068845
deforestation: cs_150km: year: 2016, total=837590583.0, reference=837590583, delta=0.0
vegetation: cs_150km: year: 2016, total=3806673704.0, reference=3806701543, delta=-27839.0, percent=0.00073131554143487
deforestation: cs_150km: year: 2017, total=845362251.0, reference=845362251, delta=0.0
vegetation: cs_150km: year: 2017, total=3798902036.0, reference=3798929875, delta=-27839.0, percent=0.0007328116315913833
deforestation: cs_150km: year: 2018, total=854616717.0, reference=854616717, delta=0.0
vegetation: cs_150km: year: 2018, total=3789647570.0, reference=3789675409, delta=-27839.0, percent=0.0007346011728045598
deforestation: cs_150km: year: 2019, total=868084491.0, reference=868084491, delta=0.0
vegetation: cs_150km: year: 2019, total=3776179796.0, reference=3776207635, delta=-27839.0, percent=0.0007372211141668326
deforestation: cs_150km: year: 2020, total=880718814.0, reference=880718814, delta=0.0
vegetation: cs_150km: year: 2020, total=3763545473.0, reference=3763573312, delta=-27839.0, percent=0.0007396959668949847
deforestation: cs_150km: year: 2021, total=895445986.0, reference=895445986, delta=0.0
vegetation: cs_150km: year: 2021, total=3748818301.0, reference=3748846140, delta=-27839.0, percent=0.0007426018289456926
deforestation: cs_150km: year: 2022, total=910643559.0, reference=910643559, delta=0.0
vegetation: cs_150km: year: 2022, total=3733620728.0, reference=3733648567, delta=-27839.0, percent=0.0007456245412612236
deforestation: cs_150km: year: 2023, total=920294252.0, reference=920294252, delta=0.0
vegetation: cs_150km: year: 2023, total=3723970035.0, reference=3723997874, delta=-27839.0, percent=0.0007475568177512874
deforestation: cs_150km: year: 2024, total=928191549.0, reference=928191549, delta=0.0
vegetation: cs_150km: year: 2024, total=3716072738.0, reference=3716100577, delta=-27839.0, percent=0.0007491454933244667
deforestation: cs_150km: year: 2025, total=935144578.0, reference=935144578, delta=0.0
vegetation: cs_150km: year: 2025, total=3709119709.0, reference=3709147548, delta=-27839.0, percent=0.0007505498133934035
_
deforestation: states: year: 2000, total=14828865.0, reference=14828865, delta=0.0
vegetation: states: year: 2000, total=4629435356.0, reference=4629463261, delta=-27905.0, percent=0.0006027696609038929
deforestation: states: year: 2001, total=14828865.0, reference=14828865, delta=0.0
vegetation: states: year: 2001, total=4629435356.0, reference=4629463261, delta=-27905.0, percent=0.0006027696609038929
deforestation: states: year: 2002, total=18376420.0, reference=18376420, delta=0.0
vegetation: states: year: 2002, total=4625887801.0, reference=4625915706, delta=-27905.0, percent=0.0006032319171706066
deforestation: states: year: 2003, total=18376420.0, reference=18376420, delta=0.0
vegetation: states: year: 2003, total=4625887801.0, reference=4625915706, delta=-27905.0, percent=0.0006032319171706066
deforestation: states: year: 2004, total=21539920.0, reference=21539920, delta=0.0
vegetation: states: year: 2004, total=4622724301.0, reference=4622752206, delta=-27905.0, percent=0.0006036447284321516
deforestation: states: year: 2005, total=21539920.0, reference=21539920, delta=0.0
vegetation: states: year: 2005, total=4622724301.0, reference=4622752206, delta=-27905.0, percent=0.0006036447284321516
deforestation: states: year: 2006, total=23686492.0, reference=23686492, delta=0.0
vegetation: states: year: 2006, total=4620577729.0, reference=4620605634, delta=-27905.0, percent=0.0006039251606903096
deforestation: states: year: 2007, total=765236132.0, reference=765236132, delta=0.0
vegetation: states: year: 2007, total=3879028089.0, reference=3879055994, delta=-27905.0, percent=0.0007193760554929489
deforestation: states: year: 2008, total=780660058.0, reference=780660058, delta=0.0
vegetation: states: year: 2008, total=3863604163.0, reference=3863632068, delta=-27905.0, percent=0.0007222478618271992
deforestation: states: year: 2009, total=787322360.0, reference=787322360, delta=0.0
vegetation: states: year: 2009, total=3856941861.0, reference=3856969766, delta=-27905.0, percent=0.0007234954301687414
deforestation: states: year: 2010, total=795122676.0, reference=795122676, delta=0.0
vegetation: states: year: 2010, total=3849141545.0, reference=3849169450, delta=-27905.0, percent=0.0007249615887915769
deforestation: states: year: 2011, total=801406016.0, reference=801406016, delta=0.0
vegetation: states: year: 2011, total=3842858205.0, reference=3842886110, delta=-27905.0, percent=0.0007261469427206106
deforestation: states: year: 2012, total=806164261.0, reference=806164261, delta=0.0
vegetation: states: year: 2012, total=3838099960.0, reference=3838127865, delta=-27905.0, percent=0.0007270471693886624
deforestation: states: year: 2013, total=813315372.0, reference=813315372, delta=0.0
vegetation: states: year: 2013, total=3830948849.0, reference=3830976754, delta=-27905.0, percent=0.0007284043154494171
deforestation: states: year: 2014, total=819649961.0, reference=819649961, delta=0.0
vegetation: states: year: 2014, total=3824614260.0, reference=3824642165, delta=-27905.0, percent=0.0007296107399370263
deforestation: states: year: 2015, total=828071727.0, reference=828071727, delta=0.0
vegetation: states: year: 2015, total=3816192494.0, reference=3816220399, delta=-27905.0, percent=0.0007312208699296354
deforestation: states: year: 2016, total=837590583.0, reference=837590583, delta=0.0
vegetation: states: year: 2016, total=3806673638.0, reference=3806701543, delta=-27905.0, percent=0.0007330493259003573
deforestation: states: year: 2017, total=845362251.0, reference=845362251, delta=0.0
vegetation: states: year: 2017, total=3798901970.0, reference=3798929875, delta=-27905.0, percent=0.0007345489629497306
deforestation: states: year: 2018, total=854616717.0, reference=854616717, delta=0.0
vegetation: states: year: 2018, total=3789647504.0, reference=3789675409, delta=-27905.0, percent=0.000736342746762141